### ISSUE TITLE
sales tax query: add postal code to where clause

### ISSUE THREAD

**Issue by jake-101** [wp-graphql/wp-graphql-woocommerce#105]
it would be useful to be able to query for a sales tax rate by searching for the postal code. I will try to set this up and make a pull request

**Comment by jake-101** [comment]
I wasn't able to figure out how to do the wp query join to make this work. I need to make a new factory function I think?

**Comment by kidunot89** [comment]
Finally, got around to addressing this. See [PR](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/231) here

**Comment by kidunot89** [comment]
@jake-101 :point_up:

**Comment by jake-101** [comment]
@kidunot89 you're the man! I was trying to update to newer versions of WPGraphQL and woographql last night. I had to switch to taxjar for the new US sales tax laws 😭😭😭😭
