### ISSUE TITLE
customerRegister mutation resolves wrong object for `viewer` field

### ISSUE THREAD

**Issue by mlipscombe** [wp-graphql/wp-graphql-woocommerce#111]
**Describe the bug**
The resolver for the `viewer` field of the `customerRegister` mutation returns a `WPGraphQL\Model\User`, but the JWT plugin expects a `\WP_User` object.

Attempting to use any JWT fields in the resulting `viewer` field gives the following error:

`Argument 1 passed to WPGraphQL\JWT_Authentication\ManageTokens::WPGraphQL\JWT_Authentication\{closure}() must be an instance of WP_User, instance of WPGraphQL\Model\User given`

**To Reproduce**
Install `wp-graphql-jwt-authentication`, and perform the following mutatoin:

```graphql
mutation RegisterMutation($input: RegisterCustomerInput!) {
  registerCustomer(input: $input) {
    viewer {
      jwtAuthToken
      jwtRefreshToken
    }
  }
}
```

**Comment by kidunot89** [comment]
Yes, the User model is being resolved incorrectly. However as of `0.2.0`, you should be able to get the JWT fields on the `customer` type too.

**Comment by mlipscombe** [comment]
This appears to be a bug in the JWT plugin, not this one, so closing this.  Sorry for the noise!
