### ISSUE TITLE
Sorting of products, Categories etc

### ISSUE THREAD

**Issue by dksami** [wp-graphql/wp-graphql-woocommerce#138]
**Is your feature request related to a problem? Please describe.**
Product Sorting features is what really missing with in your Project, Project Sorting can be of different type. Right now filtering is available but sorting is much more need.
**Types of Sorting that are required.**

- Products by Highest and lowest views (Solution Ref [Link])(https://stackoverflow.com/questions/50518802/sort-products-by-most-viewed/50607712)
- Products by Recommended based on his cart or wish list or order list (GOLD OPTION) [LINK](https://stackoverflow.com/a/42805409/9638167)
- Related Products [Link](http://www.wpdevcodes.com/how-to-display-related-products-in-woocommerce/)

**Describe the solution you'd like**
I have attached link and the code will pretty much gonna help you with the function itself all you have to do it make it accessible with Graphql.

**Comment by dksami** [comment]
Hey Really interested in this feature, when can it be done?

**Comment by kidunot89** [comment]
Soon hopefully, still working out all the sorting fields to be added to the `WCConnectionOrderbyEnum`. So far I've have `averageRating`, `dateOnSaleFrom`, `dateOnSaleTo`, and `totalSales`. I'm not sure if I should add any other fields.

**Comment by dksami** [comment]
There is perpage view meta i guess in wp add by most views to or by comments.

**Comment by kidunot89** [comment]
Implemented in #145. I've also implemented a few hooks for adding more meta fields to each of the new enumerations.

**Comment by dksami** [comment]
Great i am gonna test today.
