### ISSUE TITLE
subcategory shows empty when image field is present

### ISSUE THREAD

**Issue by Dongerina** [wp-graphql/wp-graphql-woocommerce#140]
**Describe the bug**
When the subcategory and image fields are together then the subcategory field always shows empty when the product does have a subcategory.

**To Reproduce**
1.  Make a query for a product that you know has a subcategory
2. Add the image field and the subcategory field in the query.
3. The query will display empty in the subcategories
4. Remove image and the subcategories will show up.

**Expected behaviour**
The expected behaviour is that the subcategories should show up even if the image field is present. 

**Screenshots**
![Screenshot 2019-09-13 at 11 17 50](https://user-images.githubusercontent.com/13951980/64851681-2df37580-d618-11e9-9549-7d8a326dad39.png)
**1. query for a product with both image and subcategory field**

![Screenshot 2019-09-13 at 11 18 41](https://user-images.githubusercontent.com/13951980/64851726-4bc0da80-d618-11e9-9b6f-f6dcb167a42f.png)
 **2. query for a product with only the subcategory field** 

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome]
 - Version 75.0.3770.142 (Official Build) (64-bit)

**Comment by kidunot89** [comment]
I'm having a problem recreating the problem. Here the results I get. 
![product-subcategory-query](https://user-images.githubusercontent.com/13604318/65819582-5bc9e400-e1ec-11e9-9e73-13828300380b.png)
Can you tell me which versions of WooGraphQL and WPGraphQL you're using?

**Comment by kidunot89** [comment]
@Dongerina This is actually being cause by an issue in **WPGraphQL**. See **WPGraphQL** [#887](https://github.com/wp-graphql/wp-graphql/issues/887)

**Comment by kidunot89** [comment]
This was patch in #150
