### ISSUE TITLE
Customer checkout and order mutations are not working

### ISSUE THREAD

**Issue by khuramdogar** [wp-graphql/wp-graphql-woocommerce#147]
**Describe the bug**
I am using graphql for create orders from the postman. queries are working fine but I can't run any mutations there is always customer capability error. I am also sending the Bearer token in header to authenticate the customer

**To Reproduce**
1. http://localhost:8888/testsite/graphql or https://woographql.axistaylor.com/graphql
2. Headers 
`Content-Type:application/graphql
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczpcL1wvd29vZ3JhcGhxbC5heGlzdGF5bG9yLmNvbSIsImlhdCI6MTU3MDAyMTg1OCwibmJmIjoxNTcwMDIxODU4LCJleHAiOjE1NzAwMjIxNTgsImRhdGEiOnsidXNlciI6eyJpZCI6IjMifX19.7drzb9beicfl-SqbPZvzseBGoY4Cf30eoS0x1wyGQIE`
3. run this mutation
  ```
mutation MyMutation {
  createOrder(input: {clientMutationId: "CreateOrder", customerId: 6, paymentMethod: "bacs", paymentMethodTitle: "Direct Bank Transfer", billing: {address1: "969 Market", city: "San Francisco", address2: "", company: "", country: US, email: "john.doe@example.com", firstName: "John", lastName: "Doe", phone: "12903402832", postcode: "94103", state: "CA"}, shippingLines: {methodId: "flat_rate", methodTitle: "flat_rate", total: "10"}, shipping: {address1: "969 Market", address2: "", city: "San Francisco", country: US, email: "john.doe@example.com", firstName: "JOhn", lastName: "Doe", phone: "180923843204", postcode: "94103", state: "CA"}, isPaid: true, lineItems: {productId: 30, quantity: 1}}) {
    clientMutationId
    order {
      cartHash
      currency
    }
  }
}

```
**Expected behavior**
The order should be created

**Screenshots**
Request Screenshot

![image](https://user-images.githubusercontent.com/15875273/66047158-b93d9800-e540-11e9-8353-72e09a19df3c.png)

Screenshot 2
<img width="968" alt="Screenshot 2019-10-02 at 5 48 38 PM" src="https://user-images.githubusercontent.com/15875273/66045332-f6a02680-e53c-11e9-9179-872f9db42c94.png">
Screenshot 3
![image](https://user-images.githubusercontent.com/15875273/66045384-120b3180-e53d-11e9-869f-8a730d4f1d01.png)

**Comment by kidunot89** [comment]
`createOrder` by default requires that current user have `edit-order` capability. A capability only found on users with admin or shop manager roles. For public applications it's recommended that the `checkout` mutation be used instead, however the `checkout` mutation is still in a experimental phase in my opinion and if you still wish to use the `createOrder` mutation instead the is a hook you can use to modify the cap check. Here is an example.
```
function authorized( $authorized ) {
	$authorized = true;
	return $authorized;
}
add_filter( 'authorized_to_create_orders', 'authorized' );
```
I recommend doing query validation of some kind and not just returning `true` like in the example.

**Comment by khuramdogar** [comment]
Thanks @kidunot89 for your reply but when I query on checkout I got this.

I am sending right authorize header 
![image](https://user-images.githubusercontent.com/15875273/66051652-a8912000-e548-11e9-814e-09788da0b20c.png)

**Comment by khuramdogar** [comment]
I have been stuck on this for 2 days. I am experienced JS person and it is my first time interacting  with wordpress

**Comment by kidunot89** [comment]
Also, I haven't done much in the way of documentation, but I create detailed PR summaries. Here a list of a the major ones. Click the link at the end of bullet point to be taken to any sub PR with example and more details

- [Release v0.1.0 - Cart mutations](https://github.com/wp-graphql/wp-graphql-woocommerce/issues/74)
- [Release v0.1.2 - Cart Session Handling](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/86)
- [Release v0.2.0 - Order/Checkout mutations](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/96)
- [Release v0.2.1 - New Product connection filters and checkout mutation bugfixes](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/114)

**Comment by umairraza101** [comment]
@khuramdogar  & @kidunot89 , I'm facing same issue, Please let me know if you find any solution.

**Comment by AliHussainciit** [comment]
@khuramdogar, have you found anything?  I am facing some similar issues. Please post if you find anything.

**Comment by kidunot89** [comment]
@khuramdogar @umairraza101 @AliHussainciit the `woocommerce-session` HTTP header is needed for use of the `cart` and `checkout` mutation to work properly. You can find an example of how to implement it using React and Apollo [here](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/88)

**Comment by khuramdogar** [comment]
@kidunot89 Thank you very much. Is there any way I can test this with Postman or any other rest client.

**Comment by kidunot89** [comment]
Hmm, I don't believe so. The header value is return in GraphQL response of any mutations that change that data, this current includes `addToCart` and `login`. I'm not sure how you would retrieve this value in Postman.

**Comment by dksami** [comment]
> `createOrder` by default requires that current user have `edit-order` capability. A capability only found on users with admin or shop manager roles. For public applications it's recommended that the `checkout` mutation be used instead, however the `checkout` mutation is still in a experimental phase in my opinion and if you still wish to use the `createOrder` mutation instead, there is a filter you can use to modify the cap check. Here is a basic example.
> 
> ```
> function authorized( $authorized ) {
> 	$authorized = true;
> 	return $authorized;
> }
> add_filter( 'authorized_to_create_orders', 'authorized' );
> ```
> 
> I recommend doing query validation of some kind and not just returning `true` like in the example.

Even after having those rights, its showing me the error having no rights to make that change :/

**Comment by kidunot89** [comment]
@dksami sorry, about the trouble. I found a bug related to user capabilities, it been patched on the `develop` branch and will be included in the upcoming release. Try downloading or pulling the `develop` branch and trying again.

**Comment by topheroes** [comment]
> 
> 
> `createOrder` by default requires that current user have `edit-order` capability. A capability only found on users with admin or shop manager roles. For public applications it's recommended that the `checkout` mutation be used instead, however the `checkout` mutation is still in a experimental phase in my opinion and if you still wish to use the `createOrder` mutation instead, there is a filter you can use to modify the cap check. Here is a basic example.
> 
> ```
> function authorized( $authorized ) {
> 	$authorized = true;
> 	return $authorized;
> }
> add_filter( 'authorized_to_create_orders', 'authorized' );
> ```
> 
> I recommend doing query validation of some kind and not just returning `true` like in the example.

It looks like it works on the older versions and doesn't work on the recent one. Is there an alternative?

**Comment by jonlovera** [comment]
@dksami @topheroes the filter name changed on the newer versions. Now it's called `graphql_woocommerce_authorized_to_create_orders` as you can see in [line 32](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/36fdf0c48a5c404c17e2522653de337fd8dcff34/includes/data/mutation/class-order-mutation.php#L32).

So it would end up looking like this:

```
function authorized( $authorized ) {
	$authorized = true;
	return $authorized;
}
add_filter( 'graphql_woocommerce_authorized_to_create_orders', 'authorized' );
```

Hope that helps :)

**Comment by kidunot89** [comment]
@jonlovera Thanks so much for catching that i should have made some notes on the hook name changes in the release summary. :sweat_smile: 
@dksami @topheroes My bad :man_shrugging:

**Comment by felipepxavier** [comment]
Hi @jonlovera , does this solution of yours solve the problem of orders being linked only to a guest account?

I entered your code in function.php but orders are still linking guest accounts only ..

**Comment by jonlovera** [comment]
Hi @felipepxavier, are you using [wp-graphql-jwt-authentication](https://github.com/wp-graphql/wp-graphql-jwt-authentication)?

Might be worth checking what does `wp_get_current_user()` prints out

**Comment by felipepxavier** [comment]
@jonlovera, thanks for the feedback!
Yes, I am using wp-graphql-jwt-authentication, but it was badly configured, solved! ;)

**Comment by muhaimincs** [comment]
Hello,

I have a specific rule if customer wants to checkout. My current WP settings require Delivery date as well as the time to place the order. But I couldn't find any docs related to these fields. Any help?

Thanks in advance

**Comment by topheroes** [comment]
Do I understand it correctly, that when using checkout mutation one has to specify 
account:{username: "username", password:"passowrd"} 
despite having woocommerce-session and Authorization headers?

**Comment by topheroes** [comment]
@felipepxavier Can you share the details about your wp-graphql-jwt-authentication configutation? How did you solve the problem with orders being linked only to a guest account?

Thank you in advance!

**Comment by diamondigital** [comment]
Hello, in our case, we were using the `createOrder` mutation, which is meant for internal order creation. For a standard checkout process, you should use the `checkout` mutation.

**Comment by jakubmas** [comment]
Is there a way to specify currency in `checkout` mutation? I see that this is an option in `createOrder` but I'm getting `User does not have the capabilities necessary to create an order.` error.

**Comment by diamondigital** [comment]
Have you specified the currency in the WooCommerce settings?

**Comment by diamondigital** [comment]
> Is there a way to specify currency in `checkout` mutation? I see that this is an option in `createOrder` but I'm getting `User does not have the capabilities necessary to create an order.` error.

Have you specified the currency in the WooCommerce settings?

**Comment by jakubmas** [comment]
Yes I did, default currency for my WC is USD but I need to allow also EUR.

**Comment by erikdemarco** [comment]
> Hi @felipepxavier, are you using [wp-graphql-jwt-authentication](https://github.com/wp-graphql/wp-graphql-jwt-authentication)?
> 
> Might be worth checking what does `wp_get_current_user()` prints out

@jonlovera I'm new to wpgraphql. And confuse how to usecreateOrder for guest checkout. do we also need jwt for this? do you mind to explain how to do it step by step? Because currently the documentation on this just give very little information about this: https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/docs/using-checkout-mutation-and-order-mutations.md#using-the-createorder-mutation

**Comment by codedope-agency** [comment]
> > Hi [@felipepxavier](https://github.com/felipepxavier), are you using [wp-graphql-jwt-authentication](https://github.com/wp-graphql/wp-graphql-jwt-authentication)?
> > Might be worth checking what does `wp_get_current_user()` prints out
> 
> [@jonlovera](https://github.com/jonlovera) I'm new to wpgraphql. And confuse how to usecreateOrder for guest checkout. do we also need jwt for this? do you mind to explain how to do it step by step? Because currently the documentation from [@kidunot89](https://github.com/kidunot89) on this matter just give a clue it can be done without relying on WooCommerce's session management but doesnt explain how: https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/docs/using-checkout-mutation-and-order-mutations.md#using-the-createorder-mutation

Did you find any answer ?

**Comment by kidunot89** [comment]
@Blackpearl1981 Create WP User with shop manager credentials to act as a cashier of sorts, then generate an Application password for this user. Using this application password run the createOrder mutation and set the `customerId` and/or `billing.email` to the end-user corresponding data. I also highly recommend that you run the mutation from within a serverless function or something similar, e.g. Next route handler.

**Comment by doyint** [comment]
@kidunot89 Do you have an example for this, createorder is not working for me when I am testing it out,
