### ISSUE TITLE
Pagination with orderby when fetching Products causes products to be skipped

### ISSUE THREAD

**Issue by ChrisDalley** [wp-graphql/wp-graphql-woocommerce#153]
I've been working with paginating through products combined with custom filters and sorting which has led to some strange behaviour where products are skipped over and cursors ignored. 

Paginating through a list of products returned from `products` for a category seems to work fine, but when I add an order I see the following. 

If I start with a category that has 8 products in it and I fetch all 8 at once, they are ordered correctly as expected: 

Query
```
query getProduct {
  products(where: {orderby: {field: PRICE, order: DESC}, categoryId: 24}, first: 8, after: "") {
    pageInfo {
      startCursor
      endCursor
    }
    nodes {
      name
      id
      price
    }
  }
}
```
Returns
```
{
  "data": {
    "products": {
      "pageInfo": {
        "startCursor": "YXJyYXljb25uZWN0aW9uOjIwMDY=",
        "endCursor": "YXJyYXljb25uZWN0aW9uOjEyMzM="
      },
      "nodes": [
        {
          "name": "Product A",
          "id": "cHJvZHVjdDoyMDA2",
          "price": "£13.95"
        },
        {
          "name": "Product B",
          "id": "cHJvZHVjdDoxMjM2",
          "price": "£12.95"
        },
        {
          "name": "Product C",
          "id": "cHJvZHVjdDoxMjI2",
          "price": "£12.95"
        },
        {
          "name": "Product D",
          "id": "cHJvZHVjdDoxNDAy",
          "price": "£10.95"
        },
        {
          "name": "Product E",
          "id": "cHJvZHVjdDoxMjMy",
          "price": "£7.95"
        },
        {
          "name": "Product F",
          "id": "cHJvZHVjdDoxOTgy",
          "price": "£4.95"
        },
        {
          "name": "Product G",
          "id": "cHJvZHVjdDoxOTcy",
          "price": "£4.95"
        },
        {
          "name": "Product H",
          "id": "cHJvZHVjdDoxMjMz",
          "price": "£3.95"
        }
      ]
    }
  }
}
```
All good so far...

Now if I limit the page size to 2, I get the first two results as expected...

Query:
```
query getProduct {
  products(where: {orderby: {field: PRICE, order: DESC}, categoryId: 24}, first: 2, after: "") {
    pageInfo {
      startCursor
      endCursor
    }
    nodes {
      name
      id
      price
    }
  }
}
```
Returns
```
{
  "data": {
    "products": {
      "pageInfo": {
        "startCursor": "YXJyYXljb25uZWN0aW9uOjIwMDY=",
        "endCursor": "YXJyYXljb25uZWN0aW9uOjEyMzY="
      },
      "nodes": [
        {
          "name": "Product A",
          "id": "cHJvZHVjdDoyMDA2",
          "price": "£13.95"
        },
        {
          "name": "Product B",
          "id": "cHJvZHVjdDoxMjM2",
          "price": "£12.95"
        }
      ]
    }
  }
}
```

Again, this seems fine. However if I now use the end cursor value to fetch the next page, I see the following. 

Query
```
query getProduct {
  products(where: {orderby: {field: PRICE, order: DESC}, categoryId: 24}, first: 2, after: "YXJyYXljb25uZWN0aW9uOjEyMzY=") {
    pageInfo {
      startCursor
      endCursor
    }
    nodes {
      name
      id
      price
    }
  }
}
```
Returns
```
{
  "data": {
    "products": {
      "pageInfo": {
        "startCursor": "YXJyYXljb25uZWN0aW9uOjEyMzI=",
        "endCursor": "YXJyYXljb25uZWN0aW9uOjEyMzM="
      },
      "nodes": [
        {
          "name": "Product E",
          "id": "cHJvZHVjdDoxMjMy",
          "price": "£7.95"
        },
        {
          "name": "Product H",
          "id": "cHJvZHVjdDoxMjMz",
          "price": "£3.95"
        }
      ]
    }
  }
}
```

For some reason, using the cursors and paginating while having ordered by price causes `Products C, D, F and G` to be skipped. If I look at their cursors using the `edges`  value and then fetch by their individual cursors, I can still retrieve them. 

Also I have no other plugins installed beyond the basic WPGraphQl setup so there shouldn't be anything conflicting. 

I'm new to Wordpress so if there is anything else that would be useful for me to add to the issue to help debug this, let me know!

**Comment by kidunot89** [comment]
@ChrisDalley have you confirmed if this isn't happening for post or page connections too?

**Comment by ChrisDalley** [comment]
@kidunot89 - I've just had a test with normal post types and a combination of different orderby values with the same pagination/cursor behaviour and all seems fine. (Also made sure on latest version of wp-graphql and wp-graphql-wordpress).

**Comment by kidunot89** [comment]
Turns out this was issue was being caused by a bug in WPGraphQL. This [PR](https://github.com/wp-graphql/wp-graphql/pull/1015) was opened to resolve this issue.

**Comment by arwebz** [comment]
This bug also occurs when using Custom Post Type, the first result is always duplicated on every page
