### ISSUE TITLE
Order mutations

### ISSUE THREAD

**Issue by kidunot89** [wp-graphql/wp-graphql-woocommerce#16]
#### Description
Mutations for manipulating `Orders`. Capability checks will be implemented so this mutations won't be usable for user without them.

#### Mutations
- `createOrder` - creates a order
- `updateOrder` - modifies an existing order
- `deleteOrder` - deletes a order
- `checkout` - creates order from cart

**Comment by rotexhawk** [comment]
Any updates on these? I am currently using the plugin and noticed there is no way to place an order.

**Comment by kidunot89** [comment]
Not as yet, still working out a bugs in the `cart` and shaping the `shipping method` and `payment` mutations. It's not far off tho.

**Comment by dksami** [comment]
Is it being done? Can we now place an order?
