### ISSUE TITLE
Duplicate Connections being registered

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-woocommerce#169]
**Describe the bug**
The connections registered on the Product interface are duplicately registered on the Types that implement the Product Interface and are throwing errors which prevent the Schema from loading. 

This is something that should ideally be fixed centrally in the WPGraphQL plugin, but I've got a temporary fix I'll pr for this repo. 

--- 

This issue occurs when using WPGraphQL with Interface Inheritance merged (https://github.com/wp-graphql/wp-graphql/pulls?q=is%3Apr+is%3Aclosed)

**Comment by kidunot89** [comment]
This issue is fixed in #165. Just waiting on [WPGraphQL #1005](https://github.com/wp-graphql/wp-graphql/pull/1005) before merging
