### ISSUE TITLE
Price not showing on products query

### ISSUE THREAD

**Issue by mehidi258** [wp-graphql/wp-graphql-woocommerce#176]
I am using wp-graphql-woocommerce with wp-graphql and wp-graphiql
here is my query `query MyQuery {
  products(first: 20) {
    nodes {
      productId
      slug
      name
      price
    }
  }
}
`

it gives me an error `Cannot query field "price" on type "Product".`

**Comment by kidunot89** [comment]
@mehidi258 the schema design was changed drastically in v0.3.0, if you are using WPGraphiQL, I recommend using the Explorer panel to view and get a general idea of what the schema shape

**Comment by ganeshpprasad** [comment]
I searched for price in wpgraphiql explorer but did not find. Can somebody please let me know how I can find price in products query

**Comment by kidunot89** [comment]
@ganeshpprasad Here's an example query. Prices fields only exist on the `SimpleProduct` and `VariableProduct` type.
```
query ( $id: ID!, $format: PostObjectFieldFormatEnum ) {
	product(id: $id) {
                id
		productId
		name
		... on SimpleProduct {
			price
			regularPrice
			salePrice
			dateOnSaleFrom
			dateOnSaleTo
		}
		... on VariableProduct {
			price
			regularPrice
			salePrice
			dateOnSaleFrom
			dateOnSaleTo
		}
	}
}
```

**Comment by sinapirani** [comment]
when I do this give this error:
` "type": "DUPLICATE_FIELD",
        "message": "You cannot register duplicate fields on the same Type. The field 'isPrimary' already exists on the type 'ProductToPaAmperageConnectionEdge'. Make sure to give the field a unique name.",
        "field_name": "isPrimary",
        "type_name": "ProductToPaAmperageConnectionEdge",`
