### ISSUE TITLE
Latest Update - Breaks Product Query

### ISSUE THREAD

**Issue by rotexhawk** [wp-graphql/wp-graphql-woocommerce#179]
After the latest update, I am not able to run basic product queries, like the one below. Also the stack trace is gone, so I have no idea where to look for an issue. 

Online Example is broken too
https://docs.wpgraphql.com/extensions/wpgraphql-woocommerce/

```
query{
  products {
        nodes {
            id
            name
            slug
            sku
            price
          
        }
    }
}
```
```
{
  "errors": [
    {
      "debugMessage": "You cannot register duplicate fields on the same Type. The field 'galleryImages' already exists on the type 'VariableProduct'. Make sure to give the field a unique name.",
      "message": "Internal server error",
      "category": "internal"
    }
  ]
}
```

**Comment by kidunot89** [comment]
@rotexhawk Are you using WooGraphQL `v0.3.1`? Big changes were made to the `Product` queries in `v0.3.0`, use WPGraphiQL's Explorer to view them. And sorry about the docs, I'm working on a dedicated WooGraphQL but it'll take some time.

**Comment by rotexhawk** [comment]
After your recent commits I am able to query products. I noticed that Product is changed to interface, which is great. 

**Have to query products like this now.** 
```
query products{ 
  products{
    edges{
      node{
       ... on VariableProduct{
        id
        name
      }
      ...on SimpleProduct { 
        id 
        name 
        price
      }
      }
    }
  }
}
```
