### ISSUE TITLE
Can't find woocommerce in graphql schema

### ISSUE THREAD

**Issue by D19cannon** [wp-graphql/wp-graphql-woocommerce#191]
**Describe the bug**
Can't see any woocommerce fields in: http://localhost:8000/___graphql

**To Reproduce**
Simple WP installation
plugins: acf-to-rest-api, woocommerce, woocommerce-admin,  WP Graphql, WPGraphql Woocommerce
Set some information in products including some acf fields

**Expected behavior**
Being able to see some fields in graphql

**Screenshots**
Can't find anything in here (also not under  allWordpressAcfProduct)
<img width="292" alt="Screenshot 2019-12-16 at 18 28 52" src="https://user-images.githubusercontent.com/14916043/70924293-effc5800-2031-11ea-9832-14e8326998f6.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina

**Comment by jasonbahl** [comment]
@D19cannon it looks like you are using Gatsby and `gatsby-source-wordpress` which wraps the WordPress REST API. 

If you want to use WPGraphQL and WPGraphQL for WooCommerce, you'll need to use `gatsby-source-graphql` (see: https://www.gatsbyjs.org/packages/gatsby-source-graphql/)

**Comment by jasonbahl** [comment]
@D19cannon previous conversation may serve as a refresher on configuration: https://github.com/wp-graphql/wp-graphql/issues/969

**Comment by D19cannon** [comment]
@jasonbahl thanks for the quick response! I am actually using them both currently. The wpgrapqhl is at the bottom of the list in the left. I have also searched in that field, but couldn’t find it (except for the regular pages and posts). I will send you a screenshot aprrox 10min from now.

**Comment by jasonbahl** [comment]
any WooCommerce fields will be nested under your `graphQLSource` field then. 

So it would be something like: 

```
{
  graphQLSource {
     products {
        nodes {
           id
           title
        }
     }
  }
}
```

**Comment by D19cannon** [comment]
@jasonbahl 

 Here are some screenshots (from what I can see):
<img width="244" alt="Screenshot 2019-12-16 at 19 07 07" src="https://user-images.githubusercontent.com/14916043/70927267-546de600-2037-11ea-942f-16fe410eef68.png">
<img width="251" alt="Screenshot 2019-12-16 at 19 07 15" src="https://user-images.githubusercontent.com/14916043/70927268-546de600-2037-11ea-88be-21084ec17d03.png">

**Comment by jasonbahl** [comment]
ah, so it wouldn't be under `graphQLSource` based on your screenshot, it would be under `wpgraphql`. 

Did you have Gatsby running while activating WPGraphQL for WooCommerce, etc? If so, you'll need to restart Gatsby to get the external WordPress Schema changes to show up again.

**Comment by D19cannon** [comment]
WP GraphQL:  **active**
WPGraphQL WooCommerce (WooGraphQL):  **active**
WooCommerce: **active**

Restarted the project quite a few times already.

**Comment by jasonbahl** [comment]
can you query products using WPGraphiQL in the WP admin (not using Gatsby)? https://github.com/wp-graphql/wp-graphiql

If so, that means they're in the Schema, but Gatsby isn't picking them up. 

Maybe try: `gatsby clean` to remove the cache and start again?

**Comment by D19cannon** [comment]
@jasonbahl you're an absolute legend. Gatsby clean did the trick. I didn't think that would actually do the job. I will add that as default to the script so I won't forget in the future.

Thank you so much again!

(also, I WPGraphiQL also worked and the products are visible)
<img width="244" alt="Screenshot 2019-12-16 at 19 22 38" src="https://user-images.githubusercontent.com/14916043/70928314-71a3b400-2039-11ea-8cfb-78024e279e33.png">

**Comment by D19cannon** [comment]
Quick update to make myself a bit more clear.

childWordPressAcfDetails has a repeater --> adv_fields
childWordPressAcfProductDetails suppose to have a repeater --> lijst (but won't show)

<img width="1280" alt="Screenshot 2019-12-16 at 19 24 57" src="https://user-images.githubusercontent.com/14916043/70928594-0b6b6100-203a-11ea-8a3e-1147863c206f.png">

**Comment by jasonbahl** [comment]
@D19cannon the query you're using above is using Gatsby + Gatsby Source WordPress and the WP REST API, not WPGraphQL or WPGraphQL for WooCommerce, so this isn't the right support channel for that.

**Comment by D19cannon** [comment]
Oeps my bad, thought I was in the right thread. Will move the comment to the right place.
