### ISSUE TITLE
Make package available through composer

### ISSUE THREAD

**Issue by zamson** [wp-graphql/wp-graphql-woocommerce#202]
First off, thanks for working on this project. Most of the wp-graphql packages are available trough packagist, but not this one. Would be nice to see it available as a composer package.

**Comment by kidunot89** [comment]
@jasonbahl :point_up_2:

**Comment by kidunot89** [comment]
Added -> https://packagist.org/packages/wp-graphql/wp-graphql-woocommerce

**Comment by zamson** [comment]
Thanks for adding the package. Is there any particular reason why v0.1.0-beta is the latest version available? I realised this today when I ran into some problems. Had to manually update to v0.3.2-beta.

**Comment by kidunot89** [comment]
It may have something to do with the way I manage

**Comment by kidunot89** [comment]
I think I have been create **tags** incorrectly can because of that, a stable minimum release can't be determined. I try and remedy this with the next release.

**Comment by kidunot89** [comment]
The issue has been resolved as of `v0.3.3`.
