### ISSUE TITLE
Hook into WC customer created on registration

### ISSUE THREAD

**Issue by saleebm** [wp-graphql/wp-graphql-woocommerce#204]
**Is your feature request related to a problem? Please describe.**
It would be nice for the registerCustomer mutation to also call the action similarly to the WooCommerce plugin itself, 'woocommerce_created_customer' located [here](https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/includes/wc-user-functions.php#L105). This will trigger the WooCommerce new customer email to be sent to the registrant.

**Describe the solution you'd like**
Internal implementation of this hook perhaps.

**Describe alternatives you've considered**
`add_action( 'graphql_user_object_mutation_update_additional_data', static function ( $user_id, $input, $mutation_name, $context, $info ) {
	do_action( 'woocommerce_created_customer', $user_id, null, false );
}, 10, 5 );`

**Additional context**
The main issue I had with the registerCustomer mutation was that I used a password field in my registration form, and this would cause WordPress to send an email,  `send_password_change_email`, but this seems to relate more to how WPGraphQL registers users by creating them first, then adding additional input fields.

Also, it would be my preference to allow for customer registration without enabling user registration on the WordPress settings, as WooCommerce does by [`wc_create_new_customer`](https://github.com/woocommerce/woocommerce/blob/7701d4b57cb20dc89e25bb7bf2ff872d85f4c535/includes/wc-user-functions.php#L105) function.

Thank you.

edit:
[I created an example of how I'm actually going around this here as a gist.](https://gist.github.com/saleebm/4797350cf191f3cea3beb57f8498a6fc#file-class-customer-register-proper-php)

**Comment by kidunot89** [comment]
The `wc_create_new_customer` doesn't actually add the `shipping` or `billing` meta data, but I can incorporate it into the mutation.

**Comment by saleebm** [comment]
Nice, I am glad you caught that. I also have an idea, because WooCommerce allows users to choose if they would like automatic password creation. I finally figured out how to fork and I'm trying to create a pull request for this now.
