### ISSUE TITLE
Need price in main products nodes

### ISSUE THREAD

**Issue by keshavk2910** [wp-graphql/wp-graphql-woocommerce#206]
I am using wordpress with graphql in react but when I try to get price under 
... on SimpleProduct
I'm getting null in products response 

my query 

```javascript
   products {
    nodes {
      id
      description
      image {
        sourceUrl
      }
      name
      productId
      slug
      ... on SimpleProduct {
        price
      }
    }
  }
```
Please tell me how can I get price like this in latest version

```javascript
   products {
    nodes {
      id
      description
      image {
        sourceUrl
      }
      name
      productId
      slug
     price
    }
  }
```

OR how can I add price to products>nodes

**Comment by zamson** [comment]
This works for me:

> query MyQuery {
  wpgraphql {
    products {
      edges {
        node {
          ... on WPGraphQL_SimpleProduct {
            price
          }
        }
      }
    }
  }
}


What versions are you using?

I'm on _wp-graphql-woocommerce 0.3.2_ and _wp-graphql 0.5.1_

This works for me:


query MyQuery {
  wpgraphql {
    products {
      edges {
        node {
          ... on WPGraphQL_SimpleProduct {
            price
          }
        }
      }
    }
  }
}

**Comment by keshavk2910** [comment]
Thank you so much for the quick reply
wp-graphql-woocommerce - I'm on version 0.3.2 
I found the solution though as I'm new to graphql I didnt knew that much but after searching for about a hour I found that inmemorycache was having issue registering and fetching data from cache as I'm using apollo client to fetch data so I had to use IntrospectionFragmentMatcher instead and it works great now.

Though can you help me find a way to fetch products of specific category by using slug as I'm ussing next.js and dont want to add Id to url

Thanks

**Comment by kidunot89** [comment]
@keshavk2910 Not all product types contain a pricing so it's not made available on the `Product` interface, but it is available on the default types that support like @zamson should above. This also include this `VariableProduct` as well.
