### ISSUE TITLE
Price RAW format returns null

### ISSUE THREAD

**Issue by zamson** [wp-graphql/wp-graphql-woocommerce#207]
**Describe the bug**
When getting price on product nodes formatted as RAW return value is NULL.
 
**To Reproduce**
```
query MyQuery {
  wpgraphql {
    products {
      edges {
        node {
          ... on WPGraphQL_SimpleProduct {
            price(format: RAW)
          }
        }
      }
    }
  }
}
```

**Expected behavior**
Get price with without currency symbol

**Screenshots**
```
{
  "data": {
    "wpgraphql": {
      "products": {
        "edges": [
          {
            "node": {
              "price": null
            }
          },
          {
            "node": {
              "price": null
            }
          },
          {
            "node": {
              "price": null
            }
          },
          {
            "node": {}
          },
          {
            "node": {
              "price": null
            }
          }
        ]
      }
    }
  }
}
```

**Version (please complete the following information):**
wp-graphql  0.5.1
wp-graphql-woocommerce 0.3.2

**Comment by kidunot89** [comment]
The user must have the `edit-product` capability to access the `RAW` format. You can change this behavior using the WPGraphQL `graphql_model_field_capability` hook defined here -> https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/Model.php#L324-#L337

**Comment by aresrioja10** [comment]
Hi @kidunot89 !

Could you explain how to use the graphql_model_field_capability hook?

**Comment by kidunot89** [comment]
@aresrioja10 Why? There are no longer any restrictions on the price formatting. So this :point_down: 
```graphql
{
  products {
    nodes {
      ... on SimpleProduct {
        price(format: RAW)
      }
    }
  }
}
```
is possible for everyone. 

Also, I doubt I can explain it any better than the [docblock above the hook](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/Model.php#L322-L334).

**Comment by aresrioja10** [comment]
My fault! I'm sorry.

I was using the Versión 0.5.0

Thanks!

**Comment by nguyenhuutinh** [comment]
hi, how did they use it?
I try 
.```
.. on WpSimpleProduct {
          price(format: RAW)
        }
```

but got error when compile.

thanks

**Comment by dgorczyca** [comment]
@aresrioja10 , this works indeed
> @aresrioja10 Why? There are no longer any restrictions on the price formatting. So this 👇
> 
> ```graphql
> {
>   products {
>     nodes {
>       ... on SimpleProduct {
>         price(format: RAW)
>       }
>     }
>   }
> }
> ```
> 
> is possible for everyone.
> 
> Also, I doubt I can explain it any better than the [docblock above the hook](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/Model.php#L322-L334).

Unfortunately if you run the same query in Gatsby using VariableProduct type like that:
```
... on WPGraphQL_VariableProduct {
        variations {
           nodes {
              regularPrice(format: RAW)
              salePrice(format: RAW)
              price(format: RAW)
          }
      }
}
```
all values are null (when in Gatsby).

Strangely when I run the same query inside Wordpress WPGraphiQL I get values.
The difference between the two is that I am logged in in Wordpress as admin and queries at the moment are unauthenticated.
Do you think that Is that because of capabilities hook, or would that be a `gatsby-source-graphql` bug?

If it is because of the lack of authentication, could you please point to a good guide where it is explained how to do GraphQL authentication in Gatsby.

**Comment by akshaykatale99** [comment]
> @aresrioja10 , this works indeed
> 
> > @aresrioja10 Why? There are no longer any restrictions on the price formatting. So this 👇
> > ```graphql
> > {
> >   products {
> >     nodes {
> >       ... on SimpleProduct {
> >         price(format: RAW)
> >       }
> >     }
> >   }
> > }
> > ```
> > 
> > 
> > is possible for everyone.
> > Also, I doubt I can explain it any better than the [docblock above the hook](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/Model.php#L322-L334).
> 
> Unfortunately if you run the same query in Gatsby using VariableProduct type like that:
> 
> ```
> ... on WPGraphQL_VariableProduct {
>         variations {
>            nodes {
>               regularPrice(format: RAW)
>               salePrice(format: RAW)
>               price(format: RAW)
>           }
>       }
> }
> ```
> 
> all values are null (when in Gatsby).
> 
> Strangely when I run the same query inside Wordpress WPGraphiQL I get values.
> The difference between the two is that I am logged in in Wordpress as admin and queries at the moment are unauthenticated.
> Do you think that Is that because of capabilities hook, or would that be a `gatsby-source-graphql` bug?
> 
> If it is because of the lack of authentication, could you please point to a good guide where it is explained how to do GraphQL authentication in Gatsby.

Same behavior for me also. getting null for price, salePrice, stockQuantity.

![image](https://user-images.githubusercontent.com/12472207/102894811-ad156180-4489-11eb-84db-d12a5d68d826.png)
