### ISSUE TITLE
addToCart mutation returns error on multiple calls when variationId is set.

### ISSUE THREAD

**Issue by ardiewen** [wp-graphql/wp-graphql-woocommerce#209]
**Describe the bug**

When using the addToCart mutation, running a simple incremental mutation works when productId is set, but not when both productId and variationId are set.

1. When a the productId is specified in input parameters, and the variationId is not, the client can call the same mutation multiple times, and the quantity in cart will update incrementally.

2. When both the productId and variationId are specified in input parameters, the client receives an error on the second mutation attempt.

**To Reproduce**

##### 1. Test a simple mutation with productId set only:
```
mutation ADD_TO_CART {
  addToCart(input: {clientMutationId: "someID", productId: 828 }) {
    ...
    contents {
      nodes {
        quantity
        subtotal
      }
    }
  }
}
```

First mutation returns:
```
        "contents": {
          "nodes": [
            {
              "quantity": 1,
              "subtotal": "$6.00"
            }
          ]
        }
```
Second mutation and beyond returns:
```
        "contents": {
          "nodes": [
            {
              "quantity": 2,
              "subtotal": "$12.00"
            }
          ]
        }
```
##### 2. Test with both productId and variationId set.
```
mutation ADD_TO_CART {
  addToCart(input: {clientMutationId: "someID", productId: 828, variationId: 838 }) {
    ...
    contents {
      nodes {
        quantity
        subtotal
      }
    }
  }
}
```

First mutation returns: 
```
        "contents": {
          "nodes": [
            {
              "quantity": 1,
              "subtotal": "$6.00"
            }
          ]
        }
```

Second mutation and beyond returns:
```
{
  "errors": [
    {
      "message": "Failed to add cart item. Please check input.",
      "category": "user",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "addToCart"
      ]
    }
  ],
  "data": {
    "addToCart": null
  }
}
```

**Expected behavior**

Expect that incrementing quantity for addToCart mutations with variationId set should work the same was if it were just productId only.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Chrome 
 - Version: 79

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kidunot89** [comment]
@ardiewen This actually isn't bug, the `addToCart` wasn't design to be used that way. I'd recommend using the `updateItemQuantities` to increment the quantities of items in the cart. 

It's also a pretty powerful mutations have both the ability to remove and an item from the cart by change the item quantity to `0` as well as add/restore an item to the cart by increasing the quantity of an cart item that not in the cart above `0` using the cart item key.

*Small note: A cart item key is just a serialize string of the cart item data provided in the `addToCart` mutation and the `WC_Cart::add_to_cart()` function. See the function that create it [here](https://github.com/woocommerce/woocommerce/blob/master/includes/class-wc-cart.php#L958-#L995)*

**Comment by ardiewen** [comment]
@kidunot89 thanks! that makes sense. I had been using the updateItemQuantities mutation in the mean time so it's good to know that it is the recommended approach anyway.

With regards to using the cart item key and updateItemQuantities, I just tried to add a new item to cart via that method and it returned an Internal Server error.

For example, here's a backend generated key for one of my items fetched from a previous cart:
```
          "nodes": [
            {
              "key": "1c9c40879d9104561af235249918b878",
              "quantity": 9,
              "subtotal": "$108.00"
            }
          ]
```

If I run an emptyCart mutation followed by the following updateItemQuantities mutation ($key = "1c9c40879d9104561af235249918b878"):
```
mutation UPDATE_ITEM_QUANTITY($clientMutationId: String!, $key: ID!, $qty: Int!) {
  updateItemQuantities(input: {clientMutationId: $clientMutationId, items: {key: $key, quantity: $qty}}) {
    items {
      key
      quantity
      subtotal
    }
  }
}
```

I get the following response data:
```
{
  "errors": [
    {
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "updateItemQuantities"
      ]
    }
  ],
  "data": {
    "updateItemQuantities": null
  }
}
```

**Comment by kidunot89** [comment]
@ardiewen I had actually changed that code, a few release back. Use the `restoreCartItems` instead. Sorry about the misinformation. :man_facepalming:
