### ISSUE TITLE
Cart Query

### ISSUE THREAD

**Issue by huniqcast** [wp-graphql/wp-graphql-woocommerce#224]
Hi thanks for your work.

I use your plugin to develop a react-native apps. 

But I have a problem when I add a item to the cart and try to fetch the cart after. The cart is empty.

I have read the code a bit and set the woocommerce-session header with the one the addToCart mutation return, but I still have an empty cart. 

Can you give me a hint I will explore it and post the result here for others, who may encounter this problem later.

**Comment by kidunot89** [comment]
@huniqcast Make sure you implemented retrieved and stash the woocommerce session took to send with your GraphQL request. [Here](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/88) is an example with React/Apollo

**Comment by huniqcast** [comment]
Hi @kidunot89  you are a rock thanks again. it's perfect.
When I will finish with the checkout process I will show you the result of this react native apps.

**Comment by muhaimincs** [comment]
hi @huniqcast , would you mind share apollo config?

**Comment by akshaykatale99** [comment]
> @huniqcast Make sure you implemented retrieved and stash the woocommerce session took to send with your GraphQL request. [Here](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/88) is an example with React/Apollo

hi @huniqcast , i am trying to do the same and getting same results as you described. can you please share your example that how you resolve this. thanks
