### ISSUE TITLE
Version number not updated

### ISSUE THREAD

**Issue by zamson** [wp-graphql/wp-graphql-woocommerce#225]
**Describe the bug**
Just noticed version 0.4.2 in still presented as 0.4.1. in wp-graphql-woocommerce.php. Won't make a PR since I guess @kidunot89 wants to bump the version anyhow in the next release.

**Comment by kidunot89** [comment]
Sorry, about that. I fixed it in the `develop` and `master` branch tho. Can't really do anything for the release.
