### ISSUE TITLE
CORS issue

### ISSUE THREAD

**Issue by szvest** [wp-graphql/wp-graphql-woocommerce#228]
I've just upgraded from WP GraphQL WooCommerce **Version 0.2.1** to (WPGraphQL WooCommerce (WooGraphQL) **Version 0.4.2**) and I am having issues with CORS. 

This is the console error I am getting

_Access to fetch at 'https://x.dev/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._

I have tried these in vain...

a) changing _httpLinkOptions_
`credentials: 'same-origin'`
to 
`credentials: 'include'`

b) activating and setting **wp-graphql-cors** plugin

c) setting headers in **.htaccess**

**Comment by szvest** [comment]
Fixed. It seems that it was an apollo-graphql issue.

Added 
```
fetchOptions: {
    mode: 'no-cors'
  }
```
to **apollo-link-http**

**Comment by kidunot89** [comment]
@szvest What settings are you using in WPGraphQL-CORS?

**Comment by szvest** [comment]
Thanks, kidunot89. Much appreciated.

**Comment by MANTENN** [comment]
Even with the send site credentials and using the `credentials: "include",` option the server still sends `*` as the response for `Access-Control-Allow-Origin`.

**Comment by MANTENN** [comment]
Nevermind had a typo in one of my domains and forgot to include the two `//` after `http:`.

**Comment by ebisLab** [comment]
how did you install  the wp-graphql-cors plugin  

> I've just upgraded from WP GraphQL WooCommerce **Version 0.2.1** to (WPGraphQL WooCommerce (WooGraphQL) **Version 0.4.2**) and I am having issues with CORS.
> 
> This is the console error I am getting
> 
> _Access to fetch at 'https://x.dev/graphql' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled._
> 
> I have tried these in vain...
> 
> a) changing _httpLinkOptions_
> `credentials: 'same-origin'`
> to
> `credentials: 'include'`
> 
> b) activating and setting **wp-graphql-cors** plugin
> 
> c) setting headers in **.htaccess**

**Comment by tBorbas** [comment]
@ebisLab  hey dude, did you managed to install this plugin? since I am getting fatal error
