### ISSUE TITLE
wp-graphql-woocommerce-0.4.2 contains a virus !!

### ISSUE THREAD

**Issue by saifulazfar** [wp-graphql/wp-graphql-woocommerce#230]
got a weird message today said that wp-graphql-woocommerce contains a virus when tried to upload and extract on cpanel file manager because upload the plugin from wordpress itself return 406 error...anyone ?

`The file you uploaded, wp-graphql-woocommerce-0.4.2.rar, contains a virus so the upload was canceled: {HEX}Malware.Expert.malware.url.fallagassrini.xx.tn.0.UNOFFICIAL FOUND`

![cPanel File Manager v3 - File Upload](https://user-images.githubusercontent.com/8967580/73713012-d4b2ec80-4746-11ea-956a-bdfd32338f68.png)

**Comment by dksami** [comment]
Rar donot work with the hosting and not even with the wordpress, zip it

**Comment by saifulazfar** [comment]
just forget the rar...its just an attempt because i thought the zip file problem...regardless compression format...its still return the same error...and return 406 : Not acceptable error when try install plugin through wordpress itself...

**Comment by kidunot89** [comment]
@saifulazfar That file `{HEX}Malware.Expert.malware.url.fallagasrini.xx.tn.).UNOFFICIAL` does not exist anywhere in the repo, or anywhere in project dependencies.

Most importantly, there is a protocol for handling security flaws on the [README](https://github.com/wp-graphql/wp-graphql-woocommerce#you-found-a-vulnerability-or-security-flaw).
**Please do not under any circumstance report them here in the repository.** You can DM me @kidunot89  or @jasonbahl in WPGraphQL Slack channel or email [support@axistaylor.com](mailto:support@axistaylor.com)__.
