### ISSUE TITLE
Address and Userinfo

### ISSUE THREAD

**Issue by dksami** [wp-graphql/wp-graphql-woocommerce#232]
The feature is Requested.

Well so I am creating a Woo-commerce Mobile app, right now I cannot add anything like address or bunch of shipping address.  SO the actual feature request is to add an address object and a shipping array with objects, so the person can just simply use the last known address. and it all should be authenticated by a header.

**Comment by kidunot89** [comment]
Use the `updateCustomer` mutation.

**Comment by kidunot89** [comment]
@dksami :point_up:

**Comment by dksami** [comment]
Thanks that is what I was looking for.

**Comment by trevorblades** [comment]
> Use the updateCustomer mutation. The works for both authenticated and guest users

@kidunot89 how should I go about updating guest users? I get 500 status codes when I try to do this. I'm guessing this is because I'm not sending a JWT token with the request. Can you confirm if a JWT is required for guest user updates? If so, where should I get that JWT from?

**Comment by kidunot89** [comment]
A JWT token is needed for the `updateCustomer` mutation work for an unauthenticated user.

**Comment by trevorblades** [comment]
I was just able to get it to work by setting `input.id` to `null` for unauthenticated users!
