### ISSUE TITLE
Add product UnionTypes to Orders directly

### ISSUE THREAD

**Issue by henrikwirth** [wp-graphql/wp-graphql-woocommerce#233]
**Is your feature request related to a problem? Please describe.**

When querying `orders` of a customer or in general, I'd like to be able to use the Product UnionTypes to define the same return values.

Here is the query as it does look like now:

```graphql
{
  customer(customerId: 13) {
    firstName
    email
    orders {
      nodes {
        downloadableItems {
          nodes {
            downloadId
            name
            url
            product {
              name
              ... on SimpleProduct {
                name
                productId
              }
            }
          }
        }
      }
    }
  }
}
```

**Describe the solution you'd like**

Here is an example of what would make more sense:

**Note: Actually, the prefered solution is further down**

```graphql
    query GetCustomer($id: ID!) {
        customer(id: $id) {
            customerId
            orders {
                nodes {
                    orderId
                    ... on SimpleProduct {
                        name
                        image
                        price
                        downloadableItems {
                            nodes {
                                downloadId
                                name
                                url
                            }
                        }
                    }
                }
            }
        }
    }
```

So the idea is, to have the `product` field inside order with its union types and then only `on SimpleProduct` (I think thats the only one that can have downloads) you get the downloadable items.

The problem is that each download belongs to a product. The implementation at the moment would mean, that I have to get the product for each downloadableItem and then filter in the frontend, to see if they all belong to the same product.

**The preferred way: Describe alternatives you've considered**

Maybe this is already kind of right, when I look at `lineItem`. They have a `product` field with UnionTypes. But then the the `downloads` field of SimpleProduct should simply add the `url` field.

So the Query should look like this with the added url field:

```graphql
{
  customer(customerId: 13) {
    firstName
    email
    orders {
      nodes {
        lineItems {
          nodes {
            product {
              ... on SimpleProduct {
                id
                name
                downloads {
                  name
                  url
                }
              }
            }
          }
        }
      }
    }
  }
}
```

And if we wanna make things super convenient, it would be even more amazing to have the `downloadableItems` anyways directly on the `customer` like this:

```graphql
{
  customer(customerId: 13) {
    hasDownloadableItem
    downloadableItems {
      name
      url
      product {
        ...
      }
    }
  }
}
```

It doesn't need to relate to an order at this point.

**Comment by kidunot89** [comment]
@henrikwirth, The short answer is, No it 's not possible to change the shape of the `downloadableItems`. Downloadable items are have a layer of information regarding usage, that doesn't exist on the `ProductDownload`. Going even further `ProductDownload` may become a restricted type in the future for improved security of downloads.

**Comment by henrikwirth** [comment]
I see your point:

How about something like this then ?:

```
{
  customer(customerId: 13) {
    virtualProducts {
      nodes {
        name
        ...
        hasDownloadableItem
        downloadableItems {
          name
          url
          ...
        }
      }
    }
  }
}
```

**Comment by kidunot89** [comment]
@henrikwirth Creating a relationship from the `*Product` types to the `DownloadableItem` could possibly lead to a security risk for the downloads. I would prefer to keep the relationship reversed, but I think I understand your dilemma now. I could create a connection from the `Customer` type to the `DownloadableItem` type.
```
{
  customer {
    hasDownloadableItems
    downloadableItems {
      nodes {
        name
        url
      }
    }
  }
}
```

### Quick Tip
Avoid using the `customer` query with the `id` fields in public applications.
This query is design to target the current user/customer without exposing the `customer`'s DATABASE ID. **Note: no argument in the query**.
```
customer {
  id
  firstName
  lastName
}
```
If the customer isn't logged in, the resolver looks for a woocommerce session and retrieves the customer data connected to it, if found.

**Comment by henrikwirth** [comment]
Okay makes sense. Well If it could be directly inside customer, that would be cool then.

Aaaand thanks for the quick tip :)
