### ISSUE TITLE
Finalize the checkout process - payment service (stripe)

### ISSUE THREAD

**Issue by huniqcast** [wp-graphql/wp-graphql-woocommerce#241]
First of all, thank for your hard work.

I have developed a react native e-commerce app using this amazing plugin, and in the checkout process I need a way to get the currency character and the total amount's order (in RAW format) to be able to finally the payment process using the stripe service. 

When creating a payment intent, I need to pass these informations.

Right now I don't see any way to get the current currency used by the shop.

Is there a way to get currency character or the total amount's order in RAW format?

Thanks in advance.

**Comment by renatonascalves** [comment]
@huniqcast Just following up, were you able to get the information you needed?

**Comment by huniqcast** [comment]
Hi
I have implemented a custom plugin to handle the payment process usgin the wordpress REST API.

**Comment by aidnurs** [comment]
Hey @huniqcast, 
I saw that there are some endpoints to process payment in WooCommerce settings, but I couldn't find in documentation how to use them. Can you please share your plugin or the way how you implemented it? 
Thanks!
