### ISSUE TITLE
Product categories come back HTML escaped but maybe shouldn't

### ISSUE THREAD

**Issue by ricokahler** [wp-graphql/wp-graphql-woocommerce#244]
**Describe the bug**
> A clear and concise description of what the bug is.

One of our product categories has an `&` in it

![image](https://user-images.githubusercontent.com/10551026/75566801-59c7b380-5a1e-11ea-9e3f-de91c645ad3e.png)

It comes back from WPGraphQL like so:

![image](https://user-images.githubusercontent.com/10551026/75567008-c2af2b80-5a1e-11ea-9d91-de5a785dbe35.png)

**To Reproduce**
1. Go to Products
2. Click on New Product
3. Add Product with an `&` or `>` in it.
4. Go to graphql and query for it
5. See `&amp;`

**Expected behavior**
> A clear and concise description of what you expected to happen.

Since the form in WP Admin doesn't let you format the text, I think it makes sense to expect this field to come back unescaped. 

**Additional context**
> Add any other context about the problem here.

(woographql is awesome lol)

**Comment by kidunot89** [comment]
@ricokahler This is most likely related to a bigger issue in WPGraphQL. @jasonbahl Any ideas?

**Comment by renatonascalves** [comment]
A simple `html_entity_decode` might do. Otherwise, the js app would be responsible to dealing with that. Not sure how the core plugin is handling that.

**Comment by kidunot89** [comment]
@renatonascalves Because the `productCategories` are registered using the core filters, meaning all the functionality related to the `productCategories` resolution is defined in core

**Comment by renatonascalves** [comment]
I see it! So maybe we need to add the `html_entity_decode` here: https://github.com/wp-graphql/wp-graphql/blob/0453d4c7e2c91679e5f129bcb2b7b03816b03737/src/Model/Term.php#L82

It is outputting straight from the `WP_Term`  object.

**Comment by jasonbahl** [comment]
@renatonascalves I agree this is something we need to address in WPGraphQL core. . .I noted some duplicate issues over here: https://github.com/wp-graphql/wp-graphql/issues/1169

I don't feel like I have a lot of clarity on what to do to address this. I think _something_ should be done for sure, but I'm not sure the best approach. 🤔
