### ISSUE TITLE
Show color in product attributes

### ISSUE THREAD

**Issue by ricokahler** [wp-graphql/wp-graphql-woocommerce#245]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

I apologize if I missed this feature, however, I don't think WooGraphQL currently returns the color of product attributes or any other related fields inside of the product attribute.

                  E.g. these fields 👇👇👇
![image](https://user-images.githubusercontent.com/10551026/75711682-cb109c00-5c94-11ea-93cb-356c24c87cbe.png)

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.

Again, I apologize if this ability already exists. I was just expecting it to show up under `paExampleAttributes`/`paExampleAttribute`.

**Additional context**
> Add any other context or screenshots about the feature request here.

Thanks for any help! Let me know if you need more context or if I'm just missing something! ❤️

**Comment by kidunot89** [comment]
@ricokahler I don't believe those meta exist on core WooCommerce product attributes. Here of a screenshot of the product attribute editor page with just WooCommerce installed.
![image](https://user-images.githubusercontent.com/13604318/75997648-a94e2980-5ecd-11ea-85c3-7ded53be386d.png)

**Comment by ricokahler** [comment]
Oh jeez. I didn't realize that this wasn't built in. I installed "Variation Swatches for WooCommerce" to a vanilla instance and it showed up. 🤦‍♀️
