### ISSUE TITLE
Composer dependecy breaks install

### ISSUE THREAD

**Issue by zamson** [wp-graphql/wp-graphql-woocommerce#246]
**Describe the bug**
Seems like a dependency breaks the composer package, please see error below:

**To Reproduce**
1. Run `composer require wp-graphql/wp-graphql`

The error below is thrown:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wp-graphql/wp-graphql-woocommerce ^0.4.4 -> satisfiable by wp-graphql/wp-graphql-woocommerce[v0.4.4].
    - Conclusion: remove firebase/php-jwt v4.0.0
    - Conclusion: don't install firebase/php-jwt v4.0.0
    - wp-graphql/wp-graphql-woocommerce v0.4.4 requires firebase/php-jwt ^5.0 -> satisfiable by firebase/php-jwt[v5.0.0, v5.1.0].
    - Can only install one of: firebase/php-jwt[v5.0.0, v4.0.0].
    - Can only install one of: firebase/php-jwt[v5.1.0, v4.0.0].
    - Installation request for firebase/php-jwt (locked at v4.0.0) -> satisfiable by firebase/php-jwt[v4.0.0].


```

**Comment by kidunot89** [comment]
This is related to the [wp-graphql/wp-graphql-jwt-authentication#76](https://github.com/wp-graphql/wp-graphql-jwt-authentication/issues/76).

**Comment by efoken** [comment]
Also related to https://github.com/wp-graphql/wp-graphql-jwt-authentication/issues/67 

If all `wp-graphql` plugins should be compatible with each other as Composer dependency, we have to ensure that they all use same versions of vendor dependencies, i.e. `firebase/php-jwt` has to be wether ^5.0 or ^4.0 in all packages

**Comment by efoken** [comment]
Should be fixed with https://github.com/wp-graphql/wp-graphql-jwt-authentication/pull/84

I cannot reproduce this error anymore

**Comment by zamson** [comment]
I can also confirm it's now working as expected.
