### ISSUE TITLE
Can't query all products

### ISSUE THREAD

**Issue by aidenBarrett96** [wp-graphql/wp-graphql-woocommerce#248]
**Describe the bug**

I can query everything else with no problem but when I attempt to query "products" I get an error 500. After enabling wp-debugging and attempting to query for products in the browser I get the error: 

Fatal error: Class WPGraphQL\WooCommerce\Data\Connection\Product_Connection_Resolver contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (WPGraphQL\Data\Connection\AbstractConnectionResolver::get_loader_name, WPGraphQL\Data\Connection\AbstractConnectionResolver::get_ids) in /home1/npkmedia/public_html/staging/wp-content/plugins/wp-graphql-woocommerce-develop/includes/data/connection/class-product-connection-resolver.php on line 24

**To Reproduce**
1. Go to 'http://n0domain.xyz/staging/graphql?query=query%20MyQuery%20%7B%0A%20%20products%20%7B%0A%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20name%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=MyQuery'

**Expected behavior**
For the query to return all of the products in JSON format

**Screenshots**
![image](https://user-images.githubusercontent.com/46399495/77436229-2426a800-6ddb-11ea-99a1-2ff85e23ef92.png)

**Desktop (please complete the following information):**
 - Browser [chrome]

**Additional context**
I am trying to set up a graphql API to create a Gatsby front end for the store.

**Comment by jasonbahl** [comment]
@aidenBarrett96 this looks like a version conflict with WPGraphQL v0.8.0 and WPGraphQL for WooCommerce.

There were some breaking changes in yesterday's WPGraphQL release, and I believe @kidunot89 has a release for WooGraphQL coming shortly to bring it up to compatibility with those breaking changes.

**Comment by jasonbahl** [comment]
You might want to downgrade WPGraphQL back to v0.7.1 until @kidunot89 releases his update.

**Comment by aidenBarrett96** [comment]
Sounds great thanks for the quick response!

**Comment by yondifon** [comment]
I think the newer release of WPGraphql (1.3.50 brought about another bug similar to this.

```
PHP message: PHP Fatal error:  Class WPGraphQL\Extensions\WooCommerce\Data\Connection\Product_Connection_Resolver contains 3 
abstract methods and must therefore be declared abstract or implement the remaining methods (WPGraphQL\Data\Connection\AbstractConnectionResolver::get_loader_name, WPGraphQL\Data\Connection\Abstrac
tConnectionResolver::get_ids, WPGraphQL\Data\Connection\AbstractConnectionResolver::is_valid_offset) in /home/malico/html/poslogic/public/wp-content/plugins/wp-graphql-woocommerce/includes/data/con
nection/class-product-connection-resolver.php on line 25
```

**Comment by niklas-lovgren-beleco** [comment]
> I think the newer release of WPGraphql (1.3.50 brought about another bug similar to this.

Which version WooGraphQL are you using? Not getting this error on latest version of WooGraphQL (0.8.1), but did see it in an older version (somewhere around 0.4.4, if I recall correctly).

**Comment by niklaslovgren** [comment]
Which version WooGraphQL are you using? Not getting this error on latest version of WooGraphQL (0.8.1), but did see it in an older version (somewhere around 0.4.4, if I recall correctly).
