### ISSUE TITLE
Payment Gateway API schema shape

### ISSUE THREAD

**Issue by kidunot89** [wp-graphql/wp-graphql-woocommerce#25]
**Overview**
- *WPInterface Type required*
- Mutations and Queries needed for `customer-level` functionality

**Comment by jake-101** [comment]
This plugin (https://wordpress.org/plugins/wc-rest-payment/) kind of has it right but Stripe introduced the SCA-compliant PaymentIntent way of charging customers. https://stripe.com/docs/strong-customer-authentication

I think having a way to get the token from the server's installed payment plugin is a nice way to handle payments. Stripe, Paypal, and maybe Braintree?

Check out these links too for more inspiration or references of use cases:

https://www.joshuaiz.com/words/no-woocommerce-cart-api-no-problem
https://scottbolinger.com/process-payments-woocommerce-rest-api/

**Comment by dksami** [comment]
Something like a WordPress website link where it is secured to do would also work.

**Comment by kidunot89** [comment]
This I've reached the best compromise possible with this PR #735 . Doesn't seem to be possible to create mutations for token creation that would supported by most payment gateway, but there is another solution for this I will demonstrate in the docs.
