### ISSUE TITLE
Add Support for product type Subscription.

### ISSUE THREAD

**Issue by ivanjeremic** [wp-graphql/wp-graphql-woocommerce#258]
Many people depend on the official premium plugin from WooCommerce called WooCommerce Subscriptions [Plugin](https://woocommerce.com/products/woocommerce-subscriptions/)

However, for now, WooGraphQL throws this error: `GraphQL error: The "subscription" product type is not supported by the core WPGraphQL WooCommerce (WooGraphQL) schema.`

Since this Plugin is very popular in the Premium Ecommerce world and also made by the WooCommerce Team, it would make sense to add support for it in WooGraphQL so people who have a Subscription-based shop can use it. 

**What WooGraphQL need to have?**
All queries & mutations possible to integrate from Woo Subscriptions & Payment Processing,
Cancel / Activate Subscription + Details.

**Comment by renatonascalves** [comment]
I don't disagree the necessity for it from people that are using the plugin but I don't think it should come bundled with this extension, neither that we should strive to support it.

Support for it should be added in a separate extension (paid or open ousrce) just like WooCommerce doesn't bundle with support for it.

:)

**Comment by ivanjeremic** [comment]
> I don't disagree the necessity for it from people that are using the plugin but I don't think it should come bundled with this extension, neither that we should strive to support it.
> 
> Support for it should be added in a separate extension (paid or open ousrce) just like WooCommerce doesn't bundle with support for it.
> 
> :)

Yeah thinking about it again it makes more sense to have this as a separate plugin if there are any other devs who need this I would love to have someone who could help me developing a plugin for wpgraphql-subscription
