### ISSUE TITLE
Checkout mutation payload contains WooCommerce error HTML and breaks JSON

### ISSUE THREAD

**Issue by zamson** [wp-graphql/wp-graphql-woocommerce#265]
**Describe the bug**
I've encountered a strange bug that only happens on one of my sites. When running the checkout mutation WooCommerce seems to output some errror HTML in payload and thus breaks the JSON formatting. 

**To Reproduce**
1. Run the checkout mutation
2. Order gets created in WooCommerce dashboard
3. Network error is returned and the function does not finish, can't run any functions in the callback and response comes back as undefined.

**Expected behavior**
Order should be created in WooCommerce and response data should be given

**Screenshots**
![image-1](https://user-images.githubusercontent.com/11811478/80185316-bcb08200-863e-11ea-91b6-36aa98da7e1b.png)

**Comment by zamson** [comment]
Okay it seems one particular payment gateway is issuing the alert. Have to do some further investigations.

**Comment by zamson** [comment]
After further investigation it seems my gateway is making an API request upon order creation. It's using a custom meta orderId that at the time of the request is NULL. Does woocommerce-graphql first create the order and then add the meta fields? I suspect the custom meta value is not available when the request is made.

**Comment by kidunot89** [comment]
@zamson here are the steps of the `checkout` mutation.
1. Process input values.
2. Create order 
3. Add meta new order
4. Process payment.

If your gateway requires meta, you can use the `metaData` field on the `CheckoutInput` type.

**Comment by zamson** [comment]
I'm already supplying the meta values in the input of the checkout mutation.
The payments processes without problem when testing with a WP theme in WP and same gateway. I've also made sure the values are present and the same as a normal WP order, so I'ms till thinking the value is not there when my gateway receives the order.

![Screenshot 2020-04-27 at 20 54 48](https://user-images.githubusercontent.com/11811478/80374521-5b501380-88c9-11ea-9ff5-1dc790d02a20.png)

**Comment by kidunot89** [comment]
:thinking: I'll have to look into the Klarna payment gateway.

**Comment by zamson** [comment]
Btw, it says paymentMethod: cod in my screenshot, but this was just temporary. When testing it was set to "kco".

**Comment by zamson** [comment]
I had `isPaid: false`, Klarna Payment Processor needed this to be `isPaid: true` (since payment is paid... 🤦‍♂️)
