### ISSUE TITLE
Update Customer mutation allows for invalid shipping input variables

### ISSUE THREAD

**Issue by ardiewen** [wp-graphql/wp-graphql-woocommerce#269]
**Describe the bug**

When running the `updateCustomer` mutation, the allowed shipping input variables include:

`email`
`phone`

According to The [WC REST API Customer Properties documentation](https://woocommerce.github.io/woocommerce-rest-api-docs/?javascript#customer-properties), these are not valid properties of the Shipping object. 

**To Reproduce**
1. Create an `updateCustomer` mutation:

**With email input variable:**
```
mutation UPDATE_CUSTOMER {
  updateCustomer(input: {shipping: { email: "test@test.com"}, clientMutationId: "some-set-of-strings"}) {
    clientMutationId
  }
}
```

**Response:**
```
{
  "errors": [
    {
      "debugMessage": "Call to undefined method WC_Customer::set_shipping_email()",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateCustomer"
      ]
    }
  ],
  "data": {
    "updateCustomer": null
  }
}
```

**With phone input variable:**
```
mutation UPDATE_CUSTOMER {
  updateCustomer(input: {shipping: {phone: "+19175551234", }, clientMutationId: "some-set-of-strings"}) {
    clientMutationId
  }
}
```

**Response:**
```
{
  "errors": [
    {
      "debugMessage": "Call to undefined method WC_Customer::set_shipping_phone()",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "updateCustomer"
      ]
    }
  ],
  "data": {
    "updateCustomer": null
  }
}
```

**Expected behavior**

Shouldn't have the option to add shipping email or phone as input variables.

**Screenshots**

<img width="320" alt="Screen Shot 2020-04-29 at 11 44 09 AM" src="https://user-images.githubusercontent.com/39966887/80617444-1b477880-8a10-11ea-8ed8-eff37ab8043e.png">

**Comment by kidunot89** [comment]
@ardiewen Yea, the `CustomerAddressInput` type used by the billing and shipping address. it should be fine, if the mutation resolver just ignores the `email` and `phone` fields on the `shipping` field. :thinking:
