### ISSUE TITLE
Product Categories - "Display" and "Menu Order" attributes

### ISSUE THREAD

**Issue by ardiewen** [wp-graphql/wp-graphql-woocommerce#277]
**Describe the bug**

When querying for `Product Categories`, two attributes that are available on WP-Admin are not available via graphql query:

`display` - String: Category archive display type. Options: default, products, subcategories and both.

`menu_order` - Integer: Menu order, used to custom sort the resource.

Any chance we can get these added? Would be helpful for things like megamenu construction, category archive pages, etc.

[WooCommerce REST API reference](https://woocommerce.github.io/woocommerce-rest-api-docs/?javascript#product-categories)

**Comment by kidunot89** [comment]
@ardiewen  Can you give me some example queries your using?

**Comment by ardiewen** [comment]
@kidunot89 apologies for the late reply. i see that this has been linked to a PR already. did you still want some clarification or sample queries?

**Comment by kidunot89** [comment]
@ardiewen I think I got, but if you'd pull down the branch in the PR and confirm it

**Comment by ardiewen** [comment]
@kidunot89 Confirmed! Thanks again.
