### ISSUE TITLE
Inconsistent value for ProductAttribute name and option in LocalProductAttribute and GlobalProductAttribute

### ISSUE THREAD

**Issue by hwsiew** [wp-graphql/wp-graphql-woocommerce#280]
**Describe the bug**
When query the attributes of a variable product, the name field of LocalProductAttribute return the **name** of attribute, but the name of GlobalProductAttribute return the **slug** of attribute. The same result goes to the options field for both. 

**To Reproduce**
1. Add both global and local attributes (use Capital letter for attribute's name to see the different between slug and name) in a variable product. 
2. Query the product attributes' name. 
3. Notice that for global attribute, the name field prefix 'pa_' which is the slug of the attribute.
4. Check the local attribute, the name field is the attribute's name. Why? because slug will be sanitize and no space or capital letter should be in the field.
5. Same goes to the options field

**Expected behavior**
the name and option fields should be either slug or name of attribute for both local and global attribute. 

**Screenshots**
![image](https://user-images.githubusercontent.com/51040350/81711367-2e455880-94a6-11ea-934b-6b369f705129.png)

**Comment by thetre97** [comment]
Similarly, the values for these also differ in casing - the list of options under the global attribute are all lowercase, while the global attribute value for a variant is in uppercase:
![image](https://user-images.githubusercontent.com/12587127/82693981-642ecd80-9c5a-11ea-8bce-1bd309651a8b.png)

**Comment by kireSuomi** [comment]
This still dosent work as its supposed to
The "label" field does not reflect its actual value.

@kidunot89 

![bild](https://user-images.githubusercontent.com/61624704/226382084-d8f3b24f-229e-4213-b43c-189e279bd029.png)

![bild](https://user-images.githubusercontent.com/61624704/226381997-6da6b6ae-2357-4a85-90e5-e014c5a4b169.png)

**Comment by kireSuomi** [comment]
But the name is stored on the product in the database, im just supprised WCGraphql dosent cover it..
