### ISSUE TITLE
[Question] - more than one variation of the product image

### ISSUE THREAD

**Issue by rodrigoreeis** [wp-graphql/wp-graphql-woocommerce#282]
Is there a plugin where you support more than one image in the product variation?

Because there are some plugins that do this but do not return in graphql probably because there is no integration of graphql with the plugin.

<img width="733" alt="Screen Shot 2020-05-12 at 2 30 18 PM" src="https://user-images.githubusercontent.com/37749408/81726060-21504700-945d-11ea-85c8-479744a81466.png">

**Comment by kidunot89** [comment]
@rodrigoreeis Those images are stored under the `galleryImages` field.

**Comment by rodrigoreeis** [comment]
@kidunot89 I know, but they are "global" and are not slipped in the product variation

**Comment by kidunot89** [comment]
While it would be easy to patch in an `galleryImages` connection field on the `ProductVariation` type. It would be impossible to make one solution work for all plugins. :man_shrugging:

**Comment by rodrigoreeis** [comment]
I understand this was exactly my question, I know that there are thousands of plugins and obviously it would not be possible to implement them at all, but the question was whether there were at least 1 that works on the issue of `galleryImages` to product variation

**Comment by kidunot89** [comment]
Not that I know of

**Comment by rodrigoreeis** [comment]
@kidunot89 probably but which plugin?? there are several 🧐

**Comment by kidunot89** [comment]
That's up to whoever decide to use or develop it :man_shrugging:
