### ISSUE TITLE
addToCart Mutation Does Not Work With Product Variations 

### ISSUE THREAD

**Issue by hwsiew** [wp-graphql/wp-graphql-woocommerce#283]
**Describe the bug**
addToCart mutation does not work when variation input ( variation: [ProductAttributeInput] ) is provided. Although the mutation return successfully, it causes error on Woocoomerce's cart page. 

query ->
```
mutation addCart(
  $clientId : String!,
  $productId :Int!,
  $quantity : Int,
  $variationId :Int,
  $variation : [ProductAttributeInput]
){
  addToCart(
    input: 
    	{ 
        clientMutationId: $clientId, 
        productId: $productId, 
        quantity: $quantity,
        variationId :$variationId,
        variation : $variation
      }
  ){
    cart{
      isEmpty:
      contents{
        itemCount
        productCount
        edges{
          node{
            variation{
              name
              variationId
              attributes{
                nodes{
                  name
                  value
                }
              }
            }
          }
        }
      }
    }
  }
}
```

variable ->
```
{
  "clientId" : "unqietId",
  "productId": 36,
  "variationId": 114,
  "variation": [
    {
      "attribute": "pattern",
      "attributeTerm": "Pattern 3"
    },
    {
      "attribute": "size",
      "attributeTerm": "Large L"
    },{
      "attribute": "pa_color",
      "attributeTerm": "blue"
    }
  ]
}
```
A little debugging shows that the following is the variation argument pass into WC_Cart::add_to_cart(), when

1) add variable product from the shop page.
![image](https://user-images.githubusercontent.com/51040350/81895277-78345880-95e4-11ea-94d1-f637f94c154e.png)

2) add variable product via addToCart mutation.
![image](https://user-images.githubusercontent.com/51040350/81895296-82eeed80-95e4-11ea-9d46-d268c02161b8.png)
And the resulted error:
![image](https://user-images.githubusercontent.com/51040350/81901659-758c3000-95f1-11ea-8c48-6d28e86606e5.png)

**To Reproduce**
1. execute addToCart mutation with variation input set.
2. check the woocommerce cart page.

**Expected behavior**
Variation should be set accordingly in cart page.

![image](https://user-images.githubusercontent.com/51040350/81901986-f9deb300-95f1-11ea-9ae2-7a99fb9b7577.png)

**Comment by kidunot89** [comment]
@hwsiew the field you want is `extraData` not `variation { attributes }`. Try this mutation
```
mutation addCart(
  $clientId : String!,
  $productId :Int!,
  $quantity : Int,
  $variationId :Int,
  $variation : [ProductAttributeInput]
){
  addToCart(
    input: 
    	{ 
        clientMutationId: $clientId, 
        productId: $productId, 
        quantity: $quantity,
        variationId :$variationId,
        variation : $variation
      }
  ){
    cart{
      isEmpty:
      contents{
        itemCount
        productCount
        edges{
          node{
            extraData {
              key
              value
            }
          }
        }
      }
    }
  }
}
```
The `variation` array is actually store as cart item meta by WooCommerce and used to create the attribute list in the cart you are referring to.

**Comment by hwsiew** [comment]
Hi @kidunot89, the `extraData` field return empty array. The `addToCart` mutation causes a php warning, and the added product cannot properly display in woocoomerce cart page.  
 
![image](https://user-images.githubusercontent.com/51040350/82001226-40352000-968d-11ea-8f60-f374825b26ce.png)

I noticed the `variation` argument passed to `WC_Cart::add_to_cart()` are different when you add the product from woocommerce default product page and using the `addToCart` mutation.

1) when add to cart from woocommerce product page.
![image](https://user-images.githubusercontent.com/51040350/82001582-10d2e300-968e-11ea-9b12-d9d11e1e4021.png)

2) when `addToCart` mutation
![image](https://user-images.githubusercontent.com/51040350/82001617-25af7680-968e-11ea-80bb-ef6968ccd496.png)

**Comment by kidunot89** [comment]
@hwsiew I updated the `ProductAttributeInput` field, and modified the processing of the `variation` data passed. You no longer have to pass `attribute` or `attribute_pa` just the attribute base name.

Also, please note that you must pass the `variation` data of any product attributes that are variation attributes set to `any` on the variation like the Blue variation in the image below.
![image](https://user-images.githubusercontent.com/13604318/96191465-246ec800-0f12-11eb-9464-8a83f5c0a105.png)

For example if the Product ID is `12` to add that variation to the cart the mutation input would look like this.
```json
{
    "input": {
        "clientMutationId": "someId",
        "productId": 12,
        "quantity": 1,
        "variationId": 35,
        "variation": [
            {
                "attributeName": "logo",
                "attributeValue": "Yes"
            }
        ]
    }
}
```

**Comment by dpacmittal** [comment]
@kidunot89 I was able to add product variation to cart which had their option set as 'Any'. I can see the correct option was selected in the admin panel after I do the checkout, but cart query returns attribute value as "", and extraData is empty as well.

```json
             "variation": {
                "attributes": {
                  "nodes": [
                    {
                      "name": "male-size",
                      "label": "Male-size",
                      "value": "",
                      "attributeId": 0,
                      "id": "Mjk1OTh8fG1hbGUtc2l6ZXx8",
                      "__typename": "VariationAttribute"
                    },
                    {
                      "name": "female-size",
                      "label": "Female-size",
                      "value": "",
                      "attributeId": 0,
                      "id": "Mjk1OTh8fGZlbWFsZS1zaXplfHw=",
                      "__typename": "VariationAttribute"
                    }
                  ],
                  "__typename": "ProductVariationToVariationAttributeConnection"
                },
                "__typename": "ProductVariation"
              },
```
