### ISSUE TITLE
Missing CartItem Variation Field in Cart Query

### ISSUE THREAD

**Issue by hwsiew** [wp-graphql/wp-graphql-woocommerce#284]
**Describe the bug**
There are cases where product variation's attributes can be set to 'Any' instead of particular selection as shown below. Currently, to query cart items with variable product, one can only get the attribute variation from product (e.g. ProductVariation ). This will work provided all attributes in variation product is set to specific value, for instance, the Pattern and Size attributes in the following attachment. However, if one of the attribute is set to 'Any', in this case the 'Color'. product variation for that attribute (i.e Color) will return empty string. There is no field available to query CartItem's variation for now.  

![image](https://user-images.githubusercontent.com/51040350/81911051-572d3100-95ff-11ea-9136-551a27964237.png)

![image](https://user-images.githubusercontent.com/51040350/81911114-6ca25b00-95ff-11ea-8ab3-488aa1efe709.png)

![image](https://user-images.githubusercontent.com/51040350/81912271-f30b6c80-9600-11ea-8c0a-04a3d983bb31.png)

**To Reproduce**
1. Create variable product with 'Any' variations.
2. Add the product variation with addToCart mutation 
3. Query the Cart
4. Check the CartItem's Product Variation

**Expected behavior**
To be able to display selected attributes for CartItem like in the woocommerce cart page. 

![image](https://user-images.githubusercontent.com/51040350/81912652-7462ff00-9601-11ea-8762-934d953ce74a.png)

**Comment by kidunot89** [comment]
@hwsiew If you don't have a color assigned to the variation it will return a empty field. This behavior is correct.

**Comment by hwsiew** [comment]
Hi @kidunot89, customer will still need to choose one for the 'Any' attribute.  So how can i get the field for the cart item? In this case, e.g. the 'Color' attribute is set to 'Any', how do i get the field if customer chose 'Green'? Like the one in woocommerce cart page, the cart item selected attributes can be listed down even for the 'Any' attribute.

![image](https://user-images.githubusercontent.com/51040350/82000928-65755e80-968c-11ea-8948-c62ce4b29477.png)

**Comment by kidunot89** [comment]
@hwsiew Then you should use the `color` attribute on the `product` not the `variation`.

**Comment by hwsiew** [comment]
Hi @kidunot89, thanks for the prompt reply.

This is the variable product setting. Each variation has 3 attributes. Among these attributes, `Color` is set to `Any` in each variation. You are right, for attribute set to `Any` the query of the field will be empty `""`. I believe this is where the problem. In the case of all attributes in a variation product is set to specific value other than `Any` and query the variation of the product in `Cart`, basically can tell the customer selection for each attributes (since each attribute is set to one value). But in the case of attribute is set to `Any` in a variation, the variation attribute field will be `""`. Unless there is other field i missed to get the customer selected option for `Any` attribute?

![image](https://user-images.githubusercontent.com/51040350/82004187-dae52d00-9694-11ea-93e7-7b6fddce740b.png)

**Comment by kidunot89** [comment]
@hwsiew That is correct. You can obtaining the options for the color field by queries `attributes` field on the parent product.

**Comment by hwsiew** [comment]
@kidunot89, Yup, it has been set to `Any` and the value from parent attributes is `""`. How to get the selected value by customer?

**Comment by kidunot89** [comment]
@hwsiew I said parent product, not parent attributes.
The `attributes` field on the `Product` is very different than the `attributes` field on `ProductVariation`.

**Comment by hwsiew** [comment]
I think i get your point. By the current design, they are correct. Rather than saying this is a bug, i would say an enhancement for `CartItem.variation` instead. Currently the type of `CartItem.variation` is set to `ProductVariation`. It is required to resolve `ProductVariation` Object from `$source['variation_id']`

https://github.com/wp-graphql/wp-graphql-woocommerce/blob/01df7b879b765f8cdbe90429309e0032fcb5f6aa/includes/type/object/class-cart-type.php#L299-L307

However, according to WC, CartItem.variation is more likely a taxonomy-ish key-value pair as follow. Notice that, even though color attribute is set to `Any`, the customer selected value is in the cartitem data.
```
{
   "key":"9ab0ede7f3b012aaaccdad439979ebd9",
   "product_id":36,
   "variation_id":114,
  "variation":{
      "attribute_pattern":"Pattern 3",
      "attribute_size":"Large L",
      "attribute_pa_color":"blue"
   },
   "quantity":1,
   "data":{

   },
   "data_hash":"e8badf94e79d313381e705040724aa42",
   "line_tax_data":{
      "subtotal":[

      ],
      "total":[

      ]
   },
   "line_subtotal":30,
   "line_subtotal_tax":0,
   "line_total":30,
   "line_tax":0
}
```
Related portion of WC code  -> 
https://github.com/woocommerce/woocommerce/blob/41ff8ec073c312f0802156172cba87c6f5aecaa0/includes/wc-template-functions.php#L3538-L3570

**Comment by kidunot89** [comment]
@hwsiew  See [this](https://github.com/wp-graphql/wp-graphql-woocommerce/issues/283#issuecomment-709618933) comment.
