### ISSUE TITLE
Guest cart session is not synced with Woocommerce cart session

### ISSUE THREAD

**Issue by hwsiew** [wp-graphql/wp-graphql-woocommerce#285]
**Describe the bug**
If you add an item in cart as a guest using mutation, the Woocommerce cart session will remain empty. That means the cart sessions are different for mutation and Woocommerce.

**To Reproduce**
1. Add an item to cart using `addToCart` mutation as a Guest in browser.
2. Confirm the item is added in cart.
3. Check the Woocommerce cart page

**Expected behavior**
Woocommerce cart page should have the same item added as `addToCart` mutation. 

**Additional context**
latest wp-graphql and wp-graphql-woocommerce

**Comment by kidunot89** [comment]
@hwsiew You need to use a WooCommerce Session Token for in order to use the cart. See this for a React/Apollo example 👉 https://github.com/wp-graphql/wp-graphql-woocommerce/pull/88

**Comment by hwsiew** [comment]
Hi @kidunot89, 

I implemented the guide as in #88 with graphql JWT plugin. The cart is persistent in graphql as guest. So I will be able to add item to cart using mutation and get the cart items with query.  But when I check the default Woocommerce cart page. The items added with `addToCart` mutation are not listed in default cart page.

**Comment by kidunot89** [comment]
This because they don't share the same session. WooGraphQL uses a custom session handling method then WooCommerce core. WooCommerce core uses HTTP Cookies to store the session credentials unlike WooGraphQL which uses a JWT.

**Comment by hwsiew** [comment]
I see. Thank you for the explanation.

**Comment by guilhermejbranco** [comment]
@kidunot89 Is there a way to sync the guest cart to the user cart when the user logs in?

**Comment by sorensenjg** [comment]
Im having the exact same issue. I would like to use the default checkout process instead of rebuilding all that logic on the react side. Is there an example or direction on how to sync session so the default checkout can be used? I know @jacobarriola  has done this, maybe he can chime in?

Its probably way more straight forward than I'm thinking... Im just stumped.
