### ISSUE TITLE
Query on Products fails

### ISSUE THREAD

**Issue by guilhermejbranco** [wp-graphql/wp-graphql-woocommerce#289]
![Screenshot 2020-06-02 at 16 12 34](https://user-images.githubusercontent.com/11890261/83537062-fac97d00-a4eb-11ea-994f-a174c04ebf10.png)

I'm getting the following error with the query:

```
query{
 products{
  nodes{
   id
  }
 }
}
```

Any ideas?

**Comment by kidunot89** [comment]
Can you tell me the versions for WPGraphQL and WooGraphQL you're using?

**Comment by guilhermejbranco** [comment]
Sure!

WooCommerce - 4.1.1
WP GraphQL - 0.6.0
WooGraphQL - 0.5.1

I only have those plugins activated, and default theme selected without any changes to the functions.php

**Comment by kidunot89** [comment]
@guilhermejbranco Update WPGraphQL

**Comment by kidunot89** [comment]
@guilhermejbranco Has the issue been resolved with updating WPGraphQL?

**Comment by guilhermejbranco** [comment]
Yes that worked. 

Thank you so much!
