### ISSUE TITLE
query for Product Reviews does not include rating

### ISSUE THREAD

**Issue by ardiewen** [wp-graphql/wp-graphql-woocommerce#291]
**Describe the bug**

With #259 we're now able to use product review mutations which include an input parameter for `rating`.

However, once we create the review, the rating cannot be retrieved as part of the `review` object.

**To Reproduce**

1. Create a review with a mutation like so:

```
mutation CREATE_REVIEW {
  writeReview(input: {clientMutationId: "some-set-of-strings", rating: 4, commentOn: 811, content: "Test review 4", userId: 1}) {
    rating
    review {
      content
    }
  }
}
```

It works, with the response:

```
{
  "data": {
    "writeReview": {
      "rating": 4,
      "review": {
        "content": "<p>Test review 4</p>\n"
      }
    }
  }
}
```

However, we can already see here in the response data that the rating falls outside of the review object.

2. Attempt to query the product with id `811` and get the review object with all possible field selected.

```
query GET_REVIEWS_FOR_PRODUCT {
  product(id: "811", idType: DATABASE_ID) {
    averageRating
    reviewCount
    reviewsAllowed
    reviews {
      nodes {
        agent
        approved
        author {
          ... on User {
            firstName
            userId
          }
        }
        authorIp
        children {
          nodes {
            content
          }
        }
        commentId
        commentOn {
          __typename
        }
        content
        date
        dateGmt
        id
        isRestricted
        karma
        parent {
          content
        }
        type
      }
    }
  }
}
```

As you can see, there is no available data for `rating`.

**Expected behavior**

Either an inclusion of `rating` in the review object, or perhaps another way to access this within the Product data?

**Additional context**

WPGraphql v0.8.4
WooGraphql v0.5.1

**Comment by kidunot89** [comment]
@ardiewen Sorry, it took so long for me to look into this. This is not a bug. `rating` is a edge field. You can't retrieve it from the comment type node. See the query below to figure out how to access it.

```
query GET_REVIEWS_FOR_PRODUCT {
  product(id: "811", idType: DATABASE_ID) {
    averageRating
    reviewCount
    reviewsAllowed
    reviews {
      edges {
        rating
        node {
          ... node fields.
        }
      }
    }
  }
}
```

**Comment by ardiewen** [comment]
@kidunot89 apologies for the late reply, just surfaced from some other projects. thanks for the clarification!
