### ISSUE TITLE
Access to undeclared static property in Checkout Mutation

### ISSUE THREAD

**Issue by hwsiew** [wp-graphql/wp-graphql-woocommerce#295]
**Describe the bug**
When checkout with existing logged in customer, the `checkout` mutation throw an error
 `Access to undeclared static property:WPGraphQL\WooCommerce\Data\Mutation\Checkout_Mutation::$logged_in_customer`

**To Reproduce**
1. add product to cart
2. checkout with logged in customer
3. an error will be thrown. 

**Expected behavior**
checkout successfully

**Screenshots**
![image](https://user-images.githubusercontent.com/51040350/83854875-e5518e80-a749-11ea-9830-e45bd20d3a15.png)

**Additional context**
https://github.com/wp-graphql/wp-graphql-woocommerce/blob/01df7b879b765f8cdbe90429309e0032fcb5f6aa/includes/data/mutation/class-checkout-mutation.php#L668

**Comment by felipepxavier** [comment]
Hello, how to solve this problem?
help me haha
