### ISSUE TITLE
Unable to query 'Orders' under Root

### ISSUE THREAD

**Issue by hwsiew** [wp-graphql/wp-graphql-woocommerce#299]
**Describe the bug**
Not sure if this is a bug or by design, but it causes usability issue. I am unable to query `Orders` under `Root`.
```
query GetOrders {
    orders{
        edges{
            node{
                orderId
           }
        }
    }
}
```
But it works for query `Customer.Orders`
```
query GetCustomer(
     customer(
         customerId: 8
     ){
            ...otherFields
            orders{
                 edges{
                      node{
                          orderId
                       }
                 }
            }
     }
}
```
For both queries, i had the customer logged in with valid jwt access token. It causes some problems, for example, pagination of customer orders. I will be able to fetch the first page of orders together with `Customer.Orders`, but for the subsequent pages i will need to fetch more orders together with the redundant `Customer` orther fields.

**To Reproduce**
1. Log in as customer
2. query customer's orders using root query 
3. you should get an empty array for the orders field

**Expected behavior**
Return of a list of orders belongs to the logged customer.

**Additional context**
wp-graph-woocommerce 0.5.1

**Comment by kidunot89** [comment]
The root `orders` query is restricted to admin/shop managers. Orders that belong to the current customer can be viewed using the following.
```
query {
  customer {
    orders {
       ...
    }
  }
}
```

**Comment by hwsiew** [comment]
Yup, understood. But if i want to fetch the second pages of customer's order, i will need to query the whole customer object again?

**Comment by kidunot89** [comment]
Hmm :thinking: that is correct. I can see how that would be an issue.

It maybe possible to turn the `orders` query into `customer { orders }` for non-admin users. I'll look into it
