### ISSUE TITLE
EmptyCartPayload return the cart before empty

### ISSUE THREAD

**Issue by hwsiew** [wp-graphql/wp-graphql-woocommerce#300]
**Describe the bug**
If I try to empty the cart using the `emptyCart` mutation, the `cart` payload return the cart contents before `emptyCart`. The mutation is successful, but the `cart` payload does not reflect the updated cart. According to the code, it return the clone of the original cart.

https://github.com/wp-graphql/wp-graphql-woocommerce/blob/13a5bf032f5e657b4528bf5e81df3aecc761a5a2/includes/mutation/class-cart-empty.php#L52-L83

**To Reproduce**
1. add something to the cart 
2. execute `emptyCart` mutation to empty existing cart
3. check the payload return by the mutation. 
4, the cart is not empty.

**Expected behavior**
After a cart is emptied, the empty cart should be return instead of the cart before emtpy.

**Comment by renatonascalves** [comment]
It is a common behavior in GraphQL mutations to return the just deleted "thing". Always with a label to confirm it was deleted correctly.

On that pespective, I'm not sure this is a bug. Maybe you would expect empty but having the previous deleted object at hand can be useful in several situations.

So maybe the only thing missing is a label to confirm that was deleted. That would aliviate the impression that it was not deleted.

@hwsiew I'd recommend checking the content of the `\WC()->cart` which should be empty.

But I'll defer to @kidunot89

**Comment by kidunot89** [comment]
@renatonascalves Is correct that is how the `emptyCart` mutation is designed, but it go against the patterns of the other cart mutations. :thinking: 

I'm open to any suggestions on the matter, however I believe having copy of the old cart state is very important, seeing as removed cart items can be restored with cart item keys of the deleted item.

**Comment by renatonascalves** [comment]
On the BuddyPress GraphQL extension, I'm returning the previous object with a label with the status for the `delete` mutations.

```
// The deleted group status and the previous group object.
return [
    'deleted'        => true,
    'previousObject' => $previous_group,
];
```

And returning an `UserError` if the delete request failed.
