### ISSUE TITLE
GraphQL error: Expired token

### ISSUE THREAD

**Issue by zamson** [wp-graphql/wp-graphql-woocommerce#305]
**Describe the bug**
I'm trying to implement the cart with GrahpQL but after i few days I get this error: `Uncaught (in promise) Error: GraphQL error: Expired token`. Unfortunately this error is keeping me from going into production. I can't load the cart, and I can't add to cart. The woocommerce-session is present client side and if I clear it everything works as expected. I'm fetching stock and prices with Apollo and that's working.

[Here](https://gist.github.com/zamson/6b0ee34d279c3791004655e2a6295739) is my Apollo client.js. I'm using GatsbyJS.

Any help appreciated.

**To Reproduce**
1. Add something to cart.
2. Wait 24-48H
3. Try to load cart

**Expected behavior**
Should recognise session token and load cart.

**Screenshots**
<img width="750" alt="Screenshot 2020-06-22 at 13 50 20" src="https://user-images.githubusercontent.com/11811478/85252814-59509e00-b48f-11ea-8603-700c77bcc3df.png">

**Comment by zamson** [comment]
I reckon I have to implement a token refresh mechanism in my Apollo client. But I'm unsure of what token the error is referring to? I'm not using auth for my site, does the add to cart mutation send a JWT token? As i understand the woocommerce-session token should stay the same since I want to persist the cart between sessions. Can anyone point me in the right direction? 🙏

**Comment by dawgor** [comment]
Hi @zamson, have you fixed it? Having the same problem, but as far as I know, as of now, only te AddToCart mutation is capable of generating a new token.

**Comment by zamson** [comment]
@dawgor The token is a JWT token that contains a expiry. Our solution was to check for expiry (~48h) and remove the token if it has expired. Maybe not the best solution but one that is working.

Sharing the code [here](https://gist.github.com/zamson/068d4dfb9147f075b7236632e720c20d).

**Comment by dawgor** [comment]
@zamson Oh, i see. Thank you!
