### ISSUE TITLE
Checkout mutation 'isPaid' and setting payment status to 'processing'

### ISSUE THREAD

**Issue by jake-101** [wp-graphql/wp-graphql-woocommerce#309]
**Describe the bug**
I am trying to create an order using the `createOrder` mutation and set isPaid to true, with an order status of "processing". I need order.payment_details.paid to be set as true when hit from the WC REST API. I am only able to do that with an order status of "completed", setting the order status to "processing" and `isPaid` to true doesn't mark the order as paid.

**To Reproduce**
1. send order to WPGraphQL
```
mutation createOrder {
  createOrder(input: {clientMutationId: "oslEahZa9qdfsasdfl48gvYeNKOHe5eV", transactionId: "oslEahZa9ql4sdfds8gvYeNKOHe5eV", paymentMethod: "showroom", paymentMethodTitle: "Square Retail POS", lineItems: [{name: "", sku: "POS-CUSTOM", taxClass: ZERO_RATE, quantity: 1, total: "0.75", subtotal: "0.75"}], billing: {firstName: "Showroom Guest", lastName: ""}, shippingLines: {methodTitle: "Local Pickup", methodId: "local_pickup", total: "0"}, isPaid: true, status: PROCESSING}) {
    order {
      orderId
      transactionId
      status
      orderNumber
      modified
      needsProcessing
      needsPayment
      paymentMethod
      paymentMethodTitle
      lineItems {
        nodes {
          product {
            name
            sku
            productId
          }
        }
      }
      total
      createdVia
    }
  }
}
```

2. Hit WC Rest API /wc-api/v2/orders/<order-id>
3. Scroll down to payment_details.paid
4. See it says false. The return from WPGraphQL says needsPayment = false 

**Expected behavior**
Maybe I am doing it incorrectly but I am expecting to see needsPayment in GraphQL and `order.payment_details.paid` in WC REST API to have the same state. Not setting a status when creating the order will make `order.payment_details.paid` = true but will make the status "completed", which I don't want. I tried to set this up in a custom payment gateway plugin but I don't see the status setting from there either.

**Env:**
 - WPGraphQL 0.6.1
 - WooGraphQL 0.4.2

**Comment by kidunot89** [comment]
@jake-101 This is the correct behavior. The `Processing` order status means the order has been and the customer is awaiting shipping/deliver of the item purchased. You read the more about the order status meaning [here](https://docs.woocommerce.com/document/managing-orders/). If the purchased items don't require shipping, like virtual and downloadable items, the status will be set to `Complete` because no further action is needed on the shop management's side. If you wish to have the order status set to complete you can use the `updateOrder()` mutation.

**Comment by jake-101** [comment]
I see. The integration is for pickup orders so I guess that is correct that the order is complete. I will work around that now that I know. Thanks a lot.
