### ISSUE TITLE
Link user logged in at checkout

### ISSUE THREAD

**Issue by felipepxavier** [wp-graphql/wp-graphql-woocommerce#320]
**Describe the bug**

Hello, I would like to know how to link a user logged in to a mutation at checkout?
I'm using "wp-graphql-jwt-authentication", so I have the user id, but I don't know how to insert it in mutation, any suggestions?

**my mutation**
const CHECKOUT_MUTATION = gql`
mutation CHECKOUT_MUTATION( $input: CheckoutInput! ) {
  checkout(input: $input) {
    clientMutationId

    order {
      id
      orderId
      refunds {
        nodes {
          amount
        }
      }
      status
    }

    customer {
      id
    }
     
    result
    redirect
  }
}
`;

**Comment by kidunot89** [comment]
@felipepxavier Have you tried looking at this pinned issue? #147 
It contains the info you seek, plus more info on creating order.

If you're in a hurry just look for a link containing **QL Session Handler** in the label. It'll take you to a PR summary with a React/Apollo example of what you need to implement in your client side application.

For future reference, you can find the link in the repo README.

**Comment by felipepxavier** [comment]
Hi @kidunot89 !
Thanks for the feedback, but I had looked at this issue. I can create orders, so I create a session and send it through the header, my problem is to create an order that is not linked to the invited user, but rather to the logged in user.

**Comment by aresrioja10** [comment]
Hello @felipepxavier!

Have you fixed this issue? I'm facing the same problem here. My orders are always linked to the invited user.
