### ISSUE TITLE
Do WooCommerce-Extensions work with wp-graphql-woocommerce?

### ISSUE THREAD

**Issue by kaspolar** [wp-graphql/wp-graphql-woocommerce#324]
For a client project I have to make a Webshop and I want to make it with headless wordpress and also use GraphQl. During my research I found an extension called _Shipping Multiple Addresses_, developed by WooCommerce, which would be perfect for my usecase. Now I want to know, if I can use wp-graphql-woocommerce to interact with this extension. I haven't found any Information about that, or if it is even integrated into the WooCommerce Rest API, by searching the internet. Is this possible or if not, how could I interact with this exension through GraphQl in general (I have almost no experience working with headless Wordpress)?

**Comment by kidunot89** [comment]
@kaspolar The Multiple Shipping Addresses plugin would require some custom schema implemention in order to work with WooGraphQL, because it relies on data not found in WooCommerce core which is what WooGraphQL aims to cover out of the box.
