### ISSUE TITLE
[Question] GraphQLError: Schema is not configured for mutations.

### ISSUE THREAD

**Issue by kenchoong** [wp-graphql/wp-graphql-woocommerce#328]
Hey wanna to know, what possible reason I get this error: 

`GraphQLError: Schema is not configured for mutations.`

When I run this following query: 

```
mutation {
  addToCart(input: {clientMutationId: "someId" productId: 22, quantity: 2}) {
    clientMutationId
    cartItem {
      key
      product {
        id
        productId
        name
      }
      quantity
      subtotal
      total
    }
    cart {
      contents(first: 10) {
        edges {
          cursor
          node {
            key
            quantity
            subtotal
            total
          }
        }
      }
      subtotal
      total
    }
  }
}
```

Step to reproduce: 

Install WpGraphQL
Install WpGraphql- woocommerce 
Then I use this plugin for gatsby https://github.com/pasdo501/gatsby-source-woocommerce

But I get this error: 

`GraphQLError: Schema is not configured for mutations.`

So how can I solve this problem ya?

**Comment by jasonbahl** [comment]
@kenchoong there's a couple issues here. 

The plugin `gatsby-souce-woocommerce` uses the WordPress REST API, not WPGraphQL or WPGraphQL for WooCommerce, so this isn't the proper repo for issues related to `gatsby-source-woocommerce`.

If you're looking to use WPGraphQL and WPGraphQL for WooCommerce, I'd recommend using `gatsby-source-wordpress-experimental`: https://github.com/gatsbyjs/gatsby-source-wordpress-experimental

This is the new source plugin we're working on at Gatsby and will be supporting long-term. It sources data using WPGraphQL (not the WP REST API).

**Mutations in Gatsby**
In either case though, Gatsby's GraphQL API doesn't currently support mutations. If you want to use Mutations with WPGraphQL for WooCommerce + Gatsby, you'd need to do them on the client. 

I recommend using something like [Apollo Client](https://www.apollographql.com/docs/react/) to connect your Gatsby site to your live WPGraphQL endpoint and make mutations directly to your WPGraphQL endpoint. 

Here's a repo that shows how to use Apollo Client with Gatsby: https://github.com/jlengstorf/gatsby-with-apollo

**Comment by kenchoong** [comment]
@jasonbahl  Thanks a lot sir
