### ISSUE TITLE
Get Cart query always return blank result

### ISSUE THREAD

**Issue by kenchoong** [wp-graphql/wp-graphql-woocommerce#333]
**I have a mutation to Add to cart  like this:** 

```
import { gql } from '@apollo/client';

const ADD_TO_CART = gql`
  mutation ($input: AddToCartInput!) {
    addToCart(input: $input) {
      cartItem {
        key
        product {
          id
         ... some other field here
        }
        variation {
          id
          variationId
          name
         ... some other field here
        }
        quantity
        total
        subtotal
        subtotalTax
      }
    }
  }
`;

export default ADD_TO_CART;
```

**This is Get Cart query:** 

```
const GET_CART = gql`
  query GetCart {
    cart {
      contents {
        nodes {
          key
          product {
            id
            productId
            name
            description
            
            .. some other field here
          }
          variation {
            id
            variationId
            name
            description
            .. some other field here
          } 
          quantity
          total
          subtotal
          subtotalTax
        }
      }
    
      subtotal
      subtotalTax
     
      .. some other field here
    }
  }
`;

export default GET_CART;
```

**Then I call this mutation like this:** 

```
// here define the addToCartInput!
const addToCartInput = {
        clientMutationId: v4(),
        productId: productId,
        quantity: 1,
        variationId: product.variationId
    }

// Call to GET_CART query above 
const { loading, error, data, refetch } = useQuery(GET_CART, {
		notifyOnNetworkStatusChange: true,
		onCompleted: () => {
			
                console.log(data) // <-- this always return the blank cart

		}
	});

// Call to ADD_TO_CART mutation above 
const [addToCart,
        { loading: addToCartLoading, error: addToCartError, data: addToCartData }]
        = useMutation(ADD_TO_CART, {
            variables: {
                input: addToCartInput,
            },
            onCompleted: () => {
              
                console.log("completed add to cart")
                refetch(); // Refetch the query again for Updated cart by calling the GET_CART query above again 
            
            },
            onError: (error) => {
                // present the error 
                console.log(error)
            }
        });

```

As you can see above, I `refetch()` the `GET_CART` query when the `onCompleted()` of the `addToCart` mutation.

**What I expect:** 
Therefore what I expect should be, initial it will be a blank cart(subtotal 0.00) , then when successful mutation, it will have the product inside it. 

**End Result:** 
But end up, everytime the `GET_CART` query will return the blank cart even the `addToCart` mutation is successful. 

But weird thing is, when I using GraphiQL in `wp-admin` dashboard, it works as expected in **What I expect** section . If I having the successful mutation in GraphiQL, I get the data in cart using the `GET_CART` query. 

So what I missing out? Cause I can't find any documentation on this. Cause when I checked the docs about the cart, I found this, https://woographql.com/guides/create-react-app/3-creating-the-cart which I didnt see any documentation. 

Any help will be appreciated. 

@kidunot89

**Comment by kidunot89** [comment]
@kenchoong Sounds like your missing the WooCommerce Session JWT. It allows WooCommerce keeps track of the session. See this [React/Apollo example](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/88) for more info on implementation.

Sorry, about the lack of documentation. I'm actually working on it, but it's slow going.

**Comment by kenchoong** [comment]
@kidunot89 thanks a lot for your help.. You doing great plugin. 

As state in the example provided, so means that I need to add `middleware` and `afterware` into the `ApolloClient` object right? Then the `GET_CART` query will work?

**Comment by kidunot89** [comment]
Yes, it work like an HTTP Authorization token like when using a plugin WPGraphQL-JWT-Authentication.

The Apollo middleware will pass the WooCommerce session if it's found in local storage or whatever storage method you prefer and it will the be pass as an HTTP header on every request. 

When the request is being processed by the server, WooGraphQL retrieves and decodes the token, then passing the session user ID to WooCommerce and the session data is identified in the data and loaded.

WooCommerce Session data includes any customer data for users not registered and cart data.

Session data is periodically deleted with WP-Cron if I'm not mistaken.

Also if you wish to login register customers, you have to use an plugin for user authentication like [WPGraphQL-JWT-Authentication](https://github.com/wp-graphql/wp-graphql-jwt-authentication)

**Comment by kenchoong** [comment]
Wow.. thanks a lot.. Now I have the basic concept, let me try this later.. Thank you very much

**Comment by kenchoong** [comment]
It works after implement the Middleware and Afterware into ApolloClient.. Thank you very much!!

**Comment by Manorama-Singh** [comment]
@kidunot89 I providing JWT token but session not work for AddToCart, getCart and  CustomerQuery......Please help me.

**Comment by AmirAmArA** [comment]
is someone still follwoing here? @kidunot89  
i have the same problem , I even tried it using the playground on Wordpress still returns blank

**Comment by kidunot89** [comment]
@AmirAmArA have you read the [docs](https://woographql.com/docs/configuring-graphql-client-for-user-session) on configuring the client and updated to the latest version of all WPGraphQL/WooGraphQL plugins
