### ISSUE TITLE
Make 'username' field optional in registerCustomer Mutation

### ISSUE THREAD

**Issue by HiepVu511** [wp-graphql/wp-graphql-woocommerce#335]
**Is your feature request related to a problem? Please describe.**
Default WooCommerce's customer registration flow doesn't require `username`.
![image](https://user-images.githubusercontent.com/13346949/91792005-b9598280-ec3e-11ea-81ca-0ad46fa75678.png)

**Describe the solution you'd like**
Make `username` field in `registerCustomer` mutation optional.

I'm happy to create a PR, just need some directions first.

**Comment by kidunot89** [comment]
@HiepVu511 I didn't realize it wasn't require by default. And PR are very much welcome. 
The change shouldn't be too drastic, just overwrite the `username` field to be in this function [here](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/mutation/class-customer-register.php#L45).

And remove the conditional [here](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/mutation/class-customer-register.php#L96)

**Comment by kidunot89** [comment]
This issue has been resolve in the [PR](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/381)
