### ISSUE TITLE
Expose uri field in Product type

### ISSUE THREAD

**Issue by jacobarriola** [wp-graphql/wp-graphql-woocommerce#336]
**Is your feature request related to a problem? Please describe.**
It would be great if the Product type exposed the `uri` field similar to other core types such as `Page` and `Post`.

**Describe the solution you'd like**
Add the `uri` field to the `Product` type

**Describe alternatives you've considered**
Using the `slug` field.

**Comment by kidunot89** [comment]
@jacobarriola Have you tried the `permalink` field?

**Comment by jacobarriola** [comment]
@kidunot89 I haven't tried that field yet; I could try a `replace()` on that string on my app, but it would be cool if the server handles that for consumers so that there's parity between `Product` and other core types.

**Comment by kidunot89** [comment]
@jacobarriola As of v0.6.0 you can access the `uri` field like this .
```graphql
query{
  product(...) {
    ... on ContentNode {
      uri
    }
  }
}
```
