### ISSUE TITLE
paColors and paSizes return all attributes, not connected ones

### ISSUE THREAD

**Issue by jacobarriola** [wp-graphql/wp-graphql-woocommerce#345]
**Describe the bug**
Upon updating from 0.5.x to 0.6.1, when querying a variable product and its color and size attributes, the result is all attributes return, not the connected ones to the given product.

**To Reproduce**
Run the following query (variable product):

```graphql
query SingleProduct {
  product(id: 372620, idType: DATABASE_ID) {
    name
    paColors {
      nodes {
        slug
        name
        termTaxonomyId
      }
    }
    paSizes {
      nodes {
        slug
        name
        termTaxonomyId
      }
    }
  }
}
```

**Expected behavior**
Only the colors and sizes that are associated with the product should return. In this product's case: color: gray, white, navy; size: ysm, ymd, ylg.

**Actual behavior**
All `paColor` and `paSize` entries return, regardless of whether they're connected to the product.

```json
{
  "data": {
    "product": {
      "name": "Super Soft T-Shirt | RUDIS Supply",
      "paColors": {
        "nodes": [
          {
            "slug": "aqua",
            "name": "Aqua",
            "termTaxonomyId": 278
          },
          {
            "slug": "army-green",
            "name": "Army Green",
            "termTaxonomyId": 5055
          },
          {
            "slug": "black",
            "name": "Black",
            "termTaxonomyId": 228
          },
          {
            "slug": "black-camo",
            "name": "Black Camo",
            "termTaxonomyId": 5728
          },
          {
            "slug": "black-electric-black",
            "name": "Black Electric/Black",
            "termTaxonomyId": 711
          },
          {
            "slug": "black-electric-pink",
            "name": "Black Electric/Pink",
            "termTaxonomyId": 712
          },
          {
            "slug": "black-bag",
            "name": "Black Gearpack",
            "termTaxonomyId": 267
          },
          {
            "slug": "black-color-gradient",
            "name": "Black-Color Gradient",
            "termTaxonomyId": 5670
          },
          {
            "slug": "black-gray-gradient",
            "name": "Black-Gray Gradient",
            "termTaxonomyId": 5671
          },
          {
            "slug": "black-orange-2",
            "name": "black-orange",
            "termTaxonomyId": 793
          }
        ]
      },
      "paSizes": {
        "nodes": [
          {
            "slug": "1",
            "name": "1",
            "termTaxonomyId": 719
          },
          {
            "slug": "10",
            "name": "10",
            "termTaxonomyId": 734
          },
          {
            "slug": "10-5",
            "name": "10.5",
            "termTaxonomyId": 735
          },
          {
            "slug": "11",
            "name": "11",
            "termTaxonomyId": 736
          },
          {
            "slug": "11-5",
            "name": "11.5",
            "termTaxonomyId": 5668
          },
          {
            "slug": "12",
            "name": "12",
            "termTaxonomyId": 737
          },
          {
            "slug": "13",
            "name": "13",
            "termTaxonomyId": 738
          },
          {
            "slug": "14",
            "name": "14",
            "termTaxonomyId": 739
          },
          {
            "slug": "2",
            "name": "2",
            "termTaxonomyId": 720
          },
          {
            "slug": "2xl",
            "name": "2XL",
            "termTaxonomyId": 223
          }
        ]
      }
    }
  }
}
```

**Screenshots**
Entry in WooCommerce:
![image](https://user-images.githubusercontent.com/1371573/96189384-3c841e80-0ef5-11eb-8854-f756b902adf2.png)

**Additional context**
For brevity, I didn't add `first` arguments to each of the `paColors` and `paSizes`; otherwise the data json would be too long.

**Comment by kidunot89** [comment]
I rewrote a lot of the logic related to the term connections, I probably made a mistake somewhere. [Here](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/connection/class-wc-terms.php#L31-L65) is the logic that registers the product attribute connections.

**Comment by jacobarriola** [comment]
Looks like you've added a new resolver. I'll see if I can debug that and narrow it down.

**Comment by jacobarriola** [comment]
Ok, so the `set_query_arg()` function seems off. Specifically, the `$source->{"{$taxonomy}_ids"}` value that is passed to `term_taxonomy_id`.  In the case of `Color`, it translates to `$source->color_ids`, which returns null.

What seems to work is getting the ids from the `$source->attributes` array instead.

```php
// Current - not working
$resolver->set_query_arg( 'term_taxonomy_id', $source->{"{$taxonomy}_ids"} );

// This works
$resolver->set_query_arg( 'term_taxonomy_id', $source->attributes[$tax_object->name]['options'] );
```

**null value for $source->color_ids**

![Screen Shot 2020-10-15 at 3 48 26 PM](https://user-images.githubusercontent.com/1371573/96194186-b240b800-0efe-11eb-90a2-2a0c319110e1.png)

**ids for $source->attributes[$tax_object->name]['options']**

![Screen Shot 2020-10-15 at 3 49 55 PM](https://user-images.githubusercontent.com/1371573/96194206-bc62b680-0efe-11eb-9876-6b1702390adb.png)

**Result (success)**

![Screen Shot 2020-10-15 at 3 44 25 PM](https://user-images.githubusercontent.com/1371573/96194215-c2589780-0efe-11eb-94a1-6eb2cf2abb3a.png)

**Comment by jacobarriola** [comment]
@kidunot89 would you like me to put this in a PR? Thanks!

**Comment by kidunot89** [comment]
@jacobarriola Sure, but try using `$taxonomy` where you use `tax_object->name` first.

**Comment by ardiewen** [comment]
I may have created a duplicate issue. Looks like this is happening on custom taxonomies assigned to products as well. See #348

**Comment by jacobarriola** [comment]
Yeah, see if the develop branch fixes your issue since the PR that fixes
the issue hasn't been released.

**Comment by ardiewen** [comment]
thanks @jacobarriola, I tried the develop branch and actually now the opposite is happening:

Querying the custom taxonomy now returns no terms, even when there are ones associated with the product. I'll update this on the other ticket as to not obfuscate this one.
