### ISSUE TITLE
Documentation of breaking change: "typeId" fields replaced by "databaseId"

### ISSUE THREAD

**Issue by ardiewen** [wp-graphql/wp-graphql-woocommerce#347]
**Describe the bug**

Hey @kidunot89,  just upgraded from 0.5.1 to 0.6.1 and during testing found this breaking change (for me at least) that wasn't highlighted in the CHANGELOG.md:

https://github.com/wp-graphql/wp-graphql-woocommerce/commit/449d3b16743aaa65de3eeb5cbfe7cc5fa589da99

I did a quick pass on the documentation too, and there doesn't seem to be any significant mention of using things like productId, variationId, etc. so that's good.

One instance here, but its interpretation is ambiguous since productId is a valid input parameter for mutations:
https://woographql.com/guides/create-react-app/1-creating-the-product-list

Not sure if this is easier for you to fix, or if you'd like a PR for your documentation. Happy to help. Thanks!

**Comment by kidunot89** [comment]
:man_facepalming: My bad, I made those changes early on and forgot to document them in the release summary.

**Comment by kidunot89** [comment]
`postTypeId` fields have been replaced with `databaseId` for consistency with the WPGraphQL core post type design and so support could be add for some of core Interfaces on the `Product`, `ProductVariation`, and `Order` types.
