### ISSUE TITLE
Consumer Key

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [wp-graphql/wp-graphql-woocommerce#349]
I've just install this plugin and got it all working, it's really useful! But doesn't it open access to everything? The woocommerce rest api uses a consumer key as a kind of application level permission so that only clients with the key can access it's endpoints, I don't see any such system in this plugin. Am I missing something here is there a similar thing in this plugin or is it not required?

**Comment by jacobarriola** [comment]
From my understanding, WPGraphQL adheres to common WordPress authentication and authorization best practices. Meaning, non-public data isn't expose to unauthenticated users and their capabilities.  Likewise, WPGraphQL checks for user capabilities during mutations.


Docs: https://docs.wpgraphql.com/guides/authentication-and-authorization/#authorization-with-wpgraphql

**Comment by PaperPlaneSoftware** [comment]
Yes I was just going to post this. You're quite correct, I can't access any non-public data without authentication. Thanks for the quick answer. I really like this project 👍
