### ISSUE TITLE
Order query is returning null 

### ISSUE THREAD

**Issue by pmventura** [wp-graphql/wp-graphql-woocommerce#352]
**Describe the bug**
I'm trying to extract a particular order via Postman but it's returning a `null` order. However, when trying to query via GraphiQL, it works as expected. 

Query:
```
query Orders {
  order(orderId: 7400) {
    orderId
    metaData {
      key
      value
    }
    billing {
      firstName
      address1
      address2
      postcode
      state
      phone
      email
      country
      company
      city
    }
    lineItems {
      nodes {
        product {
          name
          productId
          productCategories {
            edges {
              node {
                name
              }
            }
          }
          productTags {
            nodes {
              name
            }
          }
        }
      }
    }
  }
}
```

**Expected behavior**
Should return order

**Screenshots**
<img width="1168" alt="Screenshot 2020-10-22 at 1 52 51 PM" src="https://user-images.githubusercontent.com/4361782/96830346-e4f22f80-146d-11eb-8c87-5dbd7729a043.png">

**Comment by jacobarriola** [comment]
Sounds like you need to add authentication, since the `Order` type isn't publicly accessible. It works in your GraphiQL because you're logged into WordPress while making those queries.

**Comment by kidunot89** [comment]
@pmventura The `orders` root-level query is inaccessible for unauthenticated users. If the order was made by a guest, you user need at least a session token to query their own orders.

**Comment by pmventura** [comment]
@jacobarriola @kidunot89 I see. Thank you for the explanation

**Comment by brianpereradap** [comment]
@kidunot89 I'm trying the get an order of a guest user and its returning null. I updated the billing email of the guest user is already updated on the session and I'm passing the woocommerce-session token on the request header. But still, the order query is returning null. Im using the plugin version 0.10.4. Am I passing the session correctly? 

The same query for logged-in users are working as expected.

Any help will be appreciated.

**Comment by kidunot89** [comment]
@brianpereradap How are you creating the guest order? `checkout`, `createOrder`, or passing to a hosted checkout page?

**Comment by brianpereradap** [comment]
@kidunot89 Im using the checkout mutation to create the order and then use Paypal to collect the payment. Once the payment is completed I used the updateOrder mutation to update the status from Pending to Processing (had to add graphql_woocommerce_authorized_to_update_orders filter to get past auth).
Once all this done, I'm redirect the user the order confirmation page to show the order details.

I can confirm that the customer->billing->email and order billing email are the same
![image](https://user-images.githubusercontent.com/90669208/150275583-0ae4adbf-6128-4002-93d7-0b9c29640364.png)
![image](https://user-images.githubusercontent.com/90669208/150275991-191d9cf3-bcf6-4d38-b179-e2f20a100dc1.png)


Pleas note that for guest users get order query request my authorization header is empty. Is this the reason? If so how do I get the auth token for guest users? 
![image](https://user-images.githubusercontent.com/90669208/150275824-a59dc8e1-537d-48b9-9f22-8bea5ffce789.png)

**Comment by kidunot89** [comment]
@brianpereradap Can you try removing the authorization header entirely from the request? Not even an empty authorization header.

**Comment by brianpereradap** [comment]
@kidunot89 tried adding an empty auth header, but it didn't work. I was using the order query.

I was able to get the guest customer order information using the customer query instead. I was referring to the following ticket https://github.com/wp-graphql/wp-graphql-woocommerce/issues/432.

![image](https://user-images.githubusercontent.com/90669208/150298699-a02f12e1-009a-4388-a84f-128d2d7d8bef.png)

I guess this would be sufficient for now. @kidunot89 thanks for responding to my queries. Really appreciate your contribution.

**Comment by kidunot89** [comment]
@brianpereradap Your not supposed to use the `orders` query for guest orders.

**Comment by alexkey89** [comment]
Hi all, I'm trying to create a headless admin panel using WPGRAPHQL for my client. I've done it already using rest api (with some hacks to add featured image url in function.php etc) & woocommerce oauth. It works with REST API but it doesn't seem to work with WPGRAPHQL. I'm simply trying to "GET" the orders but always returns null even with correct jwt token authorization there. Is there anything that could be conflicting? I'm using JWT Auth plugin for that. Do I have to use https://github.com/wp-graphql/wp-graphql-jwt-authentication for it to work? (GRAPHiQL works fine when i'm logged in in wordpress)
    
```
    Authorization: Bearer the-token
    Content-Type: application/json
```

body:
```
    query GET_ORDER {
		  order(id: "303256", idType: DATABASE_ID) {
		    id
		    orderNumber
		  }
		}
```

response:
```
{
    "data": {
        "order": null
    },
    "extensions": {
        "debug": []
    }
}
```

**Comment by FullstackWEB-developer** [comment]
> @kidunot89 tried adding an empty auth header, but it didn't work. I was using the order query.
> 
> I was able to get the guest customer order information using the customer query instead. I was referring to the following ticket #432.
> 
> ![image](https://user-images.githubusercontent.com/90669208/150298699-a02f12e1-009a-4388-a84f-128d2d7d8bef.png)
> 
> I guess this would be sufficient for now. @kidunot89 thanks for responding to my queries. Really appreciate your contribution.

Hi @brianpereradap 
I think you tried in Graphql IDE in admin page.
But did you test it in postman?
I tried but I got like this result:
![image](https://user-images.githubusercontent.com/92151436/235589477-a7642891-e0db-48fb-a9fd-c1596772aa73.png)
I used woocommerce-session correctly.

Furthermore we can see that [this issue](https://github.com/wp-graphql/wp-graphql-woocommerce/issues/467) is still unresolved.
If you have resolved this issue, please kindly let me know.
