### ISSUE TITLE
The plugin does not show "language" schema for WooCommerce products

### ISSUE THREAD

**Issue by MobyDigg** [wp-graphql/wp-graphql-woocommerce#359]
I am using `wp-graphql-polylang` and `wp-graphql-woocommerce`, but when querying products I cannot find the "language" schema. I now used a work around through an ACF select field, but it would be nice to have languages available for WooCommerce products 👍

**Comment by kidunot89** [comment]
@esamattis Any ideas? I believe the blocking statement is [here](https://github.com/valu-digital/wp-graphql-polylang/blob/master/src/PostObject.php#L65).

**Comment by esamattis** [comment]
I replied to @MobyDigg for the same question in wp-graphql-polylang issue tracker earlier https://github.com/valu-digital/wp-graphql-polylang/issues/34
