### ISSUE TITLE
Creating a WPGraphQL extension that authenticates fields with the woocommerce-session token

### ISSUE THREAD

**Issue by chrispytoes** [wp-graphql/wp-graphql-woocommerce#360]
I am trying to add my own WPGraphQL field for handling Stripe payments. I want to be able to consume and identify the current user via the `woocommerce-session` header token within my custom resolver.

Is the `woocommerce-session` JWT used for authenticating guest customers and logged-in customers? Is the JWT inside the `woocommerce-session` the same as the JWTs provided by WPGraphQL JWT Authentication? Would I need to use different authentication methods for guest and account customers?

**Comment by kidunot89** [comment]
@chrispytoes It's possible to add a [custom value the JWT](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/utils/class-ql-session-handler.php#L353-L383), currently it only consist of the customer/guest id.

**Comment by chrispytoes** [comment]
@kidunot89 Thank you, that helps.
