### ISSUE TITLE
Total count when paginating

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [wp-graphql/wp-graphql-woocommerce#365]
I may be misunderstanding how pagination works but shouldn't there be a `totalCount` when requesting products so I know how many buttons to render for pagination?

**Comment by jacobarriola** [comment]
@PaperPlaneSoftware you should check this comment for the reasoning of omitting `totalCount` in core WPGraphQL: https://github.com/wp-graphql/wp-graphql/issues/261#issuecomment-336897318

**Comment by PaperPlaneSoftware** [comment]
@jacobarriola thanks for the quick reply. I read this article [forward and backward pagination with wpgraphql](https://www.wpgraphql.com/2020/03/26/forward-and-backward-pagination-with-wpgraphql/) by @jasonbahl and while I don't completely agree with it (I think there are times when knowing the total number of posts is useful, especially if there are only a few 10's of posts) I can understand why the decision was made. 

I think it would be better if the decision for page based vs cursor based pagination was left to the developer using WPGraphQL. Is there a recommended way to do page based pagination? I guess I would have to extend the resolver somehow? Any pointers would be very much appreciated.

Cheers

**Comment by jacobarriola** [comment]
Perhaps this extension can be a good guide: https://github.com/darylldoyle/wp-graphql-offset-pagination

**Comment by PaperPlaneSoftware** [comment]
That's perfect! I guess I did have the choice all along just didn't know about that plugin. Thanks so much.
