### ISSUE TITLE
GraphQL Email

### ISSUE THREAD

**Issue by believelody** [wp-graphql/wp-graphql-woocommerce#369]
Hi guys,
Is there a way to deal with email using wp-graphql ?
Except sending reset password link, how can I send emails for example when registering an user, after receive an order ?
Can wp-graphql connect to native or others wordpress plugins email ?

Sincerely

**Comment by kidunot89** [comment]
@believelody This question probably best asked in the WPGraphQL repo, but concerning WooCommerce, it sends emails when specific hooks are triggered. WooGraphQL supports most of these in it's mutations, which simply wraps the functionality trigger these hooks. You can list of hooks [here](https://github.com/woocommerce/woocommerce/blob/6861fdab5d3ac937f8e3b8de5ce30d879b03476b/includes/class-wc-emails.php#L81-L104)

**Comment by believelody** [comment]
@kidunot89 thank you very much for list of actions, I will check that.
