### ISSUE TITLE
Custom (or additionnal) fields for Customer

### ISSUE THREAD

**Issue by believelody** [wp-graphql/wp-graphql-woocommerce#377]
**Is your feature request related to a problem? Please describe.**
I want to add some custom fields for customer like "gender" (as radio button in front) or "birthday" and also store it in database.

**Describe the solution you'd like**
Enable to add these custom fields in mutation and query functions without touching or touching less possible existing files. Also it must be displayed in admin wordpress dashboard user panel.

**Describe alternatives you've considered**
What is the best way to implement this ? Create my own custom registration mutation / query or use hook to add additionnal info ?

**Additional context**
As my application will only use customer, is it more accurate to focus my implementation towards woo-graphql or it's better to focus into wp-graphql ?
In my discovery of both wp-graphql and woo-graphql, I modify RegisterCustomerInput to accept other field than those by default , customers/customer to show it and RegisterCustomerMutation to store my custom fields but values still null. Maybe because I'm writing my code in the correct way.

![image](https://user-images.githubusercontent.com/16539960/99882314-c7a4b280-2c1f-11eb-80eb-9dff98f95f22.png)

In class-customer-register.php:
```
public static function mutate_and_get_payload() {
   ...

   /*			FROM ME			*/
   add_action( 'graphql_user_object_mutation_update_additional_data', 'graphql_register_user_mutation', 10, 5 );
   // Save customer and get customer ID.
   $customer->save();
   ...
}

/*			FROM ME			*/
function graphql_register_user_mutation( $user_id, $input, $mutation_name, $context, $info ) {
	if ( isset( $input['gender'] ) ) {
		update_user_meta( $user_id, 'gender', $input['gender'] );
	}
}
```

In class-customer.php:
```
protected function init() {
	if ( empty( $this->fields ) ) {
		$this->fields = array(
			'ID'                    => function() {
				return ( ! empty( $this->data->get_id() ) ) ? $this->data->get_id() : \WC()->session->_customer_id;
			},
                        ...
                       /*               FROM ME              */
                       'gender'              => function() {
				return ( ! empty( $this->data->get_gender() ) ) ? $this->data->get_gender() : null;
			},
                        ...
                        'last_order_id'         => function() {
				return ( ! empty( $this->data->get_last_order() ) ) ? $this->data->get_last_order()->get_id() : null;
			},
		);
	}

	parent::prepare_fields();
}
```

In class-customer-type.php:
```
public static function register() {
	register_graphql_object_type(
		'Customer',
		array(
			...
			'fields'      => array(
				'id'                    => array(
					'type'        => array( 'non_null' => 'ID' ),
					'description' => __( 'The globally unique identifier for the customer', 'wp-graphql-woocommerce' ),
				),
                               ...
                              /*                       FROM ME                           */
                              'gender'              	=> array(
					'type'        => 'String',
					'description' => __( 'Return the customer\'s gender.', 'wp-graphql-woocommerce' ),
				),
                                ...
}
```

I even add my fields in wooommerce class WC_Customer, inside $data array and getter / setter for gender field like others fields.

I saw by googling how to do that only in woocommerce but as I'm using woocommerce as backend and implement my own front, I would like to use graphql to make it possible.

**Comment by kidunot89** [comment]
@believelody have you tried the `metaData` field?

Something like this.
```
customer {
  metaData(keysIn:["gender"]) {
    id
    key
    value
  }
}
```

**Comment by believelody** [comment]
@kidunot89 oh I didn't think about that. But how can I mutate metadata since it's not a RegisterCustomerInput nor UpdateCustomerInput field ?

**Comment by kidunot89** [comment]
@believelody Currently only `order` and `cart` mutations support custom meta. If you or anyone else wants to address this issue, I welcome the help :pray:.

**Comment by believelody** [comment]
@kidunot89 ooh okay. Honestly, I'm not skilled enough to handle that. I'll find another way to resolve my problem until the feature is available. Appreciate very much your work.

**Comment by believelody** [comment]
Hi there, I decided to handle that feature. I made a pull request and it would be cool if you can check what I've done. Nothing fancy. I hope, at least, it buys you time to properly finish it. I'll close this issue.
Best regards
