### ISSUE TITLE
Add support to WooCommerce Product Add-ons plugin

### ISSUE THREAD

**Issue by aresrioja10** [wp-graphql/wp-graphql-woocommerce#378]
I would like to expose the fields of Woocommerce Product Add-ons (https://woocommerce.com/products/product-add-ons/) in GraphQL.

¿Is that possible? It exists any plugin available? Should I create my own plugin?

Thank you so much!

**Comment by RevNelson** [comment]
I also need this feature for a project I'm working on. New to the wp-graphql codebase, but I'd be happy to help out if anyone can point me in the right direction to work on this. I've read [this post](https://jacobarriola.com/post/woocommerce-graphql-product-bundles) for adding product bundle support, but what I'm looking for here isn't adding a whole new product "type", just adding some fields on a Simple Product. If someone can point out some registration hooks I should be using, I'll give it a go trying to get it working.
