### ISSUE TITLE
Checkout mutation not working (Access level to WPGraphQL\WooCommerce\Model\Order::is_private() must be public)

### ISSUE THREAD

**Issue by zamson** [wp-graphql/wp-graphql-woocommerce#379]
I upgraded to WPGraphQL WooCommerce 0.6.1 and WpGraphQL 1.0 and now my checkout mutation is not working anymore. The order is being created in WooCommerce but no response data is being sent back to the client app (only error 500 internal sever error). Did some digging in the logs and the only relevant information I could find is attached below.

`PHP Fatal error:  Access level to WPGraphQL\WooCommerce\Model\Order::is_private() must be public (as in class WPGraphQL\Model\Post) in /home/example.com/web/app/mu-plugins/wp-graphql-woocommerce/includes/model/class-order.php on line 126" 
`

Woocommerce GraphQL 0.6.1 and WP GraphQL 1.0

**Comment by w3bdesign** [comment]
@zamson 

Try commenting out the function is_private temporarily and see what happens.

I am experiencing a similar issue and I suspect that this plugin needs an update.

**Comment by zamson** [comment]
I made the function public instead of protected and now the mutation works. I'm not sure what other implications this might have so won't make a PR. @kidunot89  can you shed some light on the issue?

**Comment by kidunot89** [comment]
@zamson @w3bdesign Until v0.6.2 is released, you can use the `develop` branch. This issue was resolved [recently](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/353) back but I hadn't release it officially yet.

**Comment by w3bdesign** [comment]
Confirmed working with version 1.0 of WP GraphQL and the latest development version of WP GraphQL WooCommerce.
