### ISSUE TITLE
regularPrice and salePrice return incorrect value on VariableProduct when on sale

### ISSUE THREAD

**Issue by jacobarriola** [wp-graphql/wp-graphql-woocommerce#386]
**Describe the bug**
When a VariableProduct is on sale and all the prices are equal, the `regularPrice` and `salePrice` return incorrect values.

**To Reproduce**
1. Create a Variable Product with 1 attribute and more than one variation
2. For each variation, set a regular price at 80 and sale price at 40
3. Query for this product:

```graphql
{
  product(id: 130156, idType: DATABASE_ID) {
    ... on VariableProduct {
      onSale
      price
      salePrice
      regularPrice
    }
  }
}
```

**Expected behavior**
```javascript
{
  "data": {
    "product": {
      "onSale": true,
      "price": "$40.00 - $80.00",
      "salePrice": "$40.00", 
      "regularPrice": "$80.00"
    }
  }
}
```

**Actual behavior**
```javascript
{
  "data": {
    "product": {
      "onSale": true,
      "price": "$40.00 - $80.00",
      "salePrice": "$40.00 - $80.00", // shouldn't this be $40 and not a range since the sale prices are all equal?
      "regularPrice": "$40.00" // shouldn't this return $80, not the $40 sales price?
    }
  }
}
```

**Additional context**
WooGraphQL: `develop` branch
WPGraphQL: 0.13.x
WooCommerce: 3.6
WordPress: 5.5.3

**Comment by aresrioja10** [comment]
@kidunot89 @jacobarriola Have you fixed the bug? What branch should I clone to get the changes?

**Comment by kidunot89** [comment]
Yea, I'm just making sure it's completely tested before merging. The PR is [here](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/387)
