### ISSUE TITLE
TERM_ORDER is not sorting my terms by custom order

### ISSUE THREAD

**Issue by aresrioja10** [wp-graphql/wp-graphql-woocommerce#389]
**Describe the bug**
I'm trying to sort some attribute's terms in my Next app. By default they are sorting by name, but I want to sort them in the backend in order to have more flexibility.

If I select **Custom order** in the attribute I can sort manually the terms as you can see in the screenshot below:

<img width="749" alt="Captura de pantalla 2020-12-02 a las 13 55 21" src="https://user-images.githubusercontent.com/3605582/100875255-10712c80-34a6-11eb-85b0-50acefeda20f.png">

This example works as expected with the Storefront theme. However, I doesn't work with GraphQL

**To Reproduce**
I'm using the next query. I'm just using the *TERM_ORDER* orderby option:

```javascript
query MyQuery {
  product(idType: SLUG, id: "silla-thor") {
    id
    attributes {
      edges {
        node {
          ... on GlobalProductAttribute {
            slug
            terms(where: {orderby: TERM_ORDER}) {
              edges {
                node {
                  name
                }
              }
            }
          }
        }
      }
    }
  }
}
```

But the results are sorting by the name.

Could you help me please?

**Comment by kidunot89** [comment]
@aresrioja10 That's `MENU_ORDER` you want, not `TERM_ORDER`, I believe :thinking:

**Comment by jacobarriola** [comment]
@aresrioja10 I ran into a similar issue in that the `MENU_ORDER` isn't available in the `orderby` enum.

For now, I simply exposed the `menuOrder` field to my attributes and am sorting client-side instead.

I'm not sure why `MENU_ORDER` isn't exposed as a sort, but other core taxonomies such as category and tag don't expose it either, so perhaps there was a performance reason for doing so.

```php
namespace App\GraphQL;

use WPGraphQL\Model\Term;

add_action( 'graphql_register_types', function () {
	if ( ! function_exists( 'wc_get_attribute_taxonomy_names' ) ) {
		return;
	}
	
	$names = wc_get_attribute_taxonomy_names();
	
	if ( empty( $names ) ) {
		return;
	}
	
	if ( ! is_array( $names ) ) {
		return;
	}
	
	foreach ( $names as $name ) {
		$name = str_replace( 'pa_', '', $name );
		$name = str_replace( '-', '', ucwords( $name, '-' ) );
		
		register_graphql_field(
			"Pa{$name}",
			'menuOrder',
			[
				'type'    => 'Int',
				'The menu order for a product attribute.',
				'resolve' => function ( Term $source ) {
					$order = get_term_meta( $source->term_id, 'order', true );
					
					return ! empty( $order ) ? $order : 0;
				},
			] );
	}
} );

Nonetheless, here's my snippet for exposing the field to attributes.
```

**Comment by aresrioja10** [comment]
Hi @jacobarriola ! 

I've added your code and I can see the new menuOrder field in my GraphQL schema. However, the value is always 0.

Inspecting your code I don't really know where are you declaring the $source variable. Could you help me?

Moreover, is there any solution to expose the field for all the attributes so I don't need to repeat my code like this:

```javascript
query MyQuery {
  products {
    edges {
      node {
        attributes {
          edges {
            node {
              name
              ... on GlobalProductAttribute {
                id
                name
                terms {
                  edges {
                    node {
                      ... on PaACristal1 {
                        id
                        name
                        menuOrder
                      }
                      ... on PaALaminados1 {
                        id
                        name
                        menuOrder
                      }
                      ... on PaALaminados2 {
                        id
                        name
                        menuOrder
                      }
                      ... on PaAPorcelanico1 {
                        id
                        name
                        menuOrder
                      }
                      ... on PaATapizados1 {
                        id
                        name
                        menuOrder
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by jacobarriola** [comment]
Hey @aresrioja10 !

> However, the value is always 0.

That's odd. Silly question, but are you certain that those terms have the `order` values? Get the `termTaxonomyId` and check your db. It should be in the `wp_termmeta` table.

Another way to debug is to throw a `wp_send_json()` in the resolver.  Something like:

```php
'resolve' => function ( Term $source ) {
	$order = get_term_meta( $source->term_id, 'order', true );
					
	// Add this to see what $source is
	wp_send_json( $source );
					
	return ! empty( $order ) ? $order : 0;
},
```

That should return you back the `WPGraphQL\Model\Term` value.



>  I don't really know where are you declaring the $source variable. Could you help me?

Absolutely! The callback on all resolver functions always have 4 arguments available to us: $source, $args, $context and $info. More info here: https://www.wpgraphql.com/docs/graphql-resolvers/#resolver-arguments

> is there any solution to expose the field for all the attributes so I don't need to repeat my code like this:

A little bit, but not much. My queries are a bit more simplified. I query the attributes from within the `VariableProduct` fragment. Example:
```graphql
query FirstProduct {
  products {
    name
    nodes {
      ... on VariableProduct {
        paSizes {
          nodes {
            termTaxonomyId
            name
            menuOrder
          }
        }
        paColors {
          nodes {
            termTaxonomyId
            name
            menuOrder
          }
        }
      }
    }
  }
}
```

**Comment by aresrioja10** [comment]
It works! 

The problem was, as you said, that the terms had no value in the order field. For some reason, until you reorder them in Wordpress the value is not set.

Thank you so much @jacobarriola !
