### ISSUE TITLE
Alternative shipping data (when shipToDifferentAddress === true) and transaction ID, won't appear in WordPress

### ISSUE THREAD

**Issue by MobyDigg** [wp-graphql/wp-graphql-woocommerce#390]
**Describe the bug**
I have a checkout form, which allows the user to set a different shipping address, compared to his billing address. The object I am sending via fetch() to the server is:

```
const orderData = {
    billing: {
        address1: "109 Hills Road Valley",
        address2: "Station Road",
        city: "Example City",
        company: "Other Company GmbH",
        country: "DE",
        email: "test@email.com",
        firstName: "Firstname",
        lastName: "Lastname",
        phone: "089123456789",
        postcode: "80808",
        state: "Bavaria",
    },
    clientMutationId: "50e75f32-9f72-4e16-a5a4-41f4ff76ff2c",
    isPaid: false,
    paymentMethod: "paypal",
    shipToDifferentAddress: true,
    shipping: {
        address1: "Beispielstrasse 14",
        address2: "2. Aptartment",
        city: "Berlin",
        company: "D Company GmbH",
        country: "DE",
        email: "test@email.com",
        firstName: "Peter",
        lastName: "Pan",
        phone: "089123456789",
        postcode: "12342",
        state: "Berlin",
    },
    transactionId: "b1605b91-1d3a-4008-aa7b-290a098631bd",
}
````

**Then I am sending the orderData via the checkout mutation to the WordPress server**

```
(async () => {
    await fetch(SiteConfig.graphqlUrl, {
            method: "POST",
            headers: {
                "Content-Type": "application/json",
                "woocommerce-session": `Session ${ cart.wooSession }`
            },
            body: JSON.stringify({
                query: CHECKOUT_CART,
                variables: {
                    input: {
                        ...orderData,
                    },
                },
            }),
        })
        .then((res) => res.json())
        .then((res) => {
            setCart(() => {
                return {
                    ...finalStoreState,
                    order: res.data
                };
            });
        })
        .catch(function(error) {
            setCart((prevState) => {
                return {
                    ...prevState,
                    error,
                    checkoutProcessing: false
                };
            });
        });
})();
```

The order appears in WordPress, but without the additional shipping information. Also the transaction ID won't be saved:

![image](https://user-images.githubusercontent.com/3866561/100878381-6647d380-34aa-11eb-9d9c-d977fdd0ec78.png)

**To Reproduce**
I am working with:

- gatsby-source-wordpress-experimental@^3.1.3
- WooCommerce 4.7.1
- WpGraphQL 1.0
- WpGatsby 0.6.8
- WooGraphQL 0.7.0

**Expected behavior**
- Additional shipping data should be saved in WordPress backend
- Transaction ID should be saved inn WordPress

**Comment by kidunot89** [comment]
@MobyDigg Can you update to WooGraphQL v0.7.0 and retry?

**Comment by MobyDigg** [comment]
@kidunot89 I did update to WPGraphQL WooCommerce 0.7.0. Now the company shows in the billing address, but still nothing for the shipping data and the transaction ID. When I start the dev environment I get:

```
warn  gatsby-source-wordpress  Unable to find a single Node query for PaymentGateway
        This type will not be available in Gatsby.
```

**Comment by MobyDigg** [comment]
@kidunot89 I found out when this happens and found another bug:

1. If you do not have a shipping method selected for the respective shipping zone, the order will be saved in WooCommerce, but the shipping data won't be transferred. In my opinion, this should return an error.

![image](https://user-images.githubusercontent.com/3866561/101042685-be9bd580-357d-11eb-84d2-3c689dbfb891.png)

2. If the country of the customer is not within a shipping zone, the checkout mutation returns ``null``. Should return an error.

It works as expected, when you add a shipping zone with all selectable countries from the checkout form AND a shipping method.

**Comment by kidunot89** [comment]
I'm closing this because it should have been resolve a few releases ago. If not, we'll reopen this.
