### ISSUE TITLE
Fatal Error on Multiple AddToCart Mutations

### ISSUE THREAD

**Issue by pandabrand** [wp-graphql/wp-graphql-woocommerce#391]
**Describe the bug**
I have a workflow that needs to add multiple items to cart from one click. I have them chained with a `then` on the second  mutation it hangs then times out.

**To Reproduce**
4. PHP Fatal error:  Uncaught GraphQL\Error\UserError: Woo session transaction executed out of order in /srv/www/wordpress-one/public_html/wp-content/plugins/wp-graphql-woocommerce-0.6.2/includes/utils/class-ql-session-handler.php:195

**Expected behavior**
Both items added to cart

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OS X
 - Browser Firefox

**Smartphone (please complete the following information):**
 - Version 84b7

- WP: 5.5.3
- WC: 4.6.1
- PHP: 7.2
- WPGraphQL-WC: 0.6.2

**Additional context**

**Comment by kidunot89** [comment]
@pandabrand Have you tried [batching](https://www.apollographql.com/docs/link/links/batch-http/#gatsby-focus-wrapper)?

**Comment by pandabrand** [comment]
@kidunot89 That's it! Thanks.
