### ISSUE TITLE
Infinite Loop when using redis for object cache

### ISSUE THREAD

**Issue by dpacmittal** [wp-graphql/wp-graphql-woocommerce#392]
**Describe the bug**
When you use redis object cache using any of the various object caching plugins, addToCart Mutation gets stuck in an infinite loop.

**To Reproduce**
1. Configure redis and https://github.com/rhubarbgroup/redis-cache plugin.
2. Try addToCart mutation. It'll work for a couple of requests before it starts getting stuck.

**Expected behavior**
Should not get stuck

With the help of xdebug I located the problem spot - https://github.com/wp-graphql/wp-graphql-woocommerce/blob/b3c649da671bed974ff66b1b4e78012304e8c8f1/includes/utils/class-ql-session-handler.php#L147. It seems like transaction queue doesn't change.

**Comment by kidunot89** [comment]
@dpacmittal Could you contact me in the WPGraphQL slack? I want to speak some more on your setup.

**Comment by jacobarriola** [comment]
@kidunot89 running into this same behavior as well - FYI. Same repro steps. Besides the `addToCart` mutation hanging indefinitely, the `cart` query also hangs.

**Comment by dpacmittal** [comment]
@jacobarriola As a workaround, you can ignore the `woo_session_transactions_queue` cache group:

```php
define('WP_REDIS_IGNORED_GROUPS', [
    "counts",
    "plugins",
    "themes",
    "woo_session_transactions_queue"
    ]);
```

**Comment by kidunot89** [comment]
@dpacmittal @jacobarriola The problem seems to be that the old transaction ID aren't being popped. I'm working on a patch that invalidates stale transaction IDs. That should remedy this issue.

**Comment by kidunot89** [comment]
@dpacmittal Could you try and review this PR #398 ? If it works we can get it merged.
