### ISSUE TITLE
Cant use fragment on Products()

### ISSUE THREAD

**Issue by justlevine** [wp-graphql/wp-graphql-woocommerce#396]
**Describe the bug**
(using wp-graphql-woocommerce v0.7.0)
I'm trying to use a `Product` fragment in a `products` query:
```
fragment ThisFragment on Product {
	databaseId
	id
	name
	onSale
	purchasable
	slug
}
query PRODUCTS_QUERY {
	products(first: 50) {
		nodes {
			...ThisFragment
		}
	}
}
```
However, its the products it returns have no data beyond the `__typename`. See image below for the console log.

Interestingly, it _does_ work in Graphiql.

**To Reproduce**
Include the above code in your project.

**Expected behavior**
All the product data would be returned.

**Screenshots**
![Annotation 2020-12-07 025856](https://user-images.githubusercontent.com/29322304/101298802-575d7a00-3838-11eb-91a0-ce94bd6cbdf7.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome 
 - Version: 87.0.4280.88

**Comment by jonshipman** [comment]
The __typename isn't "Product" but the variation. In your example, change ``fragment ThisFragment on Product {`` to ``fragment ThisFragment on SimpleProduct {``

So my variables looks something like this:
```
export const LiteralProductFields = `
  databaseId
  id
  name
  onSale
  sku
`;

export const ProductLiteralTypes = `
  price
  purchasable
  content
  uri
  productCategories {
    nodes {
      id
      databaseId
      uri
      name
    }
  }
  featuredImage {
    node {
      id
      sourceUrl(size: LARGE)
    }
  }
`;

export const ProductLiteral = `
  ${LiteralProductFields}
  ... on SimpleProduct {
    ${ProductLiteralTypes}
    regularPrice
    salePrice
  }
  ... on VariableProduct {
    ${ProductLiteralTypes}
    regularPrice
    salePrice
  }
  ... on ExternalProduct {
    ${ProductLiteralTypes}
    regularPrice
    salePrice
  }
  ... on GroupProduct {
    ${ProductLiteralTypes}
  }
`;
```

**Comment by justlevine** [comment]
Thanks - using literals worked perfectly!

I know your code was just illustrative, but want to make sure: does it matter which fields you put on the ProductType vs on `Product`? Like `uri` and `content` I get, since only exist on the product type, so sure. But for fields like `price` and `purchasable`, is there a reason you put them in `ProductLiteralTypes` and not `LiteralProductFields`?
