### ISSUE TITLE
Cart contents query displays product variations when none should be present

### ISSUE THREAD

**Issue by etoler1841** [wp-graphql/wp-graphql-woocommerce#399]
**Describe the bug**
When a variable product is in the the cart, the variation gets overlayed onto all simple products in the cart instead of creating an instance of the base variable product. Even if the cart is then emptied (by removing all items manually or by using the `emptyCart` mutation), future items added to the cart will continue to inherit the variation.

As a side effect, this also prevents cart totals from being calculated correctly, as the product is used for calculations rather than the variation.

For example, the sample cart below was created by adding the Variable T Shirt product, then adding the two Simple Products. The shirt is no longer listed as an individual item.

``` json
{
  "data": {
    "cart": {
      "contents": {
        "nodes": [
          {
            "variation": {
              "attributes": [
                {
                  "label": "Size",
                  "value": "XL"
                }
              ],
              "node": {
                "name": "Variable T Shirt",
                "price": "$24.99"
              }
            },
            "product": {
              "node": {
                "name": "Some Simple Product",
                "price": "$21.56"
              }
            },
            "quantity": 1,
            "subtotal": "$21.56"
          },
          {
            "variation": {
              "attributes": [
                {
                  "label": "Size",
                  "value": "XL"
                }
              ],
              "node": {
                "name": "Variable T Shirt",
                "price": "$24.99"
              }
            },
            "product": {
              "node": {
                "name": "Another Simple Product",
                "price": "$48.30"
              }
            },
            "quantity": 1,
            "subtotal": "$48.30"
          }
        ]
      }
    }
  }
}
```

**To Reproduce**
1. Add any simple product to the cart.
2. Add any variable product to the cart using both the `productId` and `variationId` fields.
3. View the cart contents, including the `variation` and `product` fields.
4. Empty the cart, then repeat the process (preferably on a separate user account), switching the first two steps.

**Expected behavior**
When a variable product is added to the cart, its parent product should be added with that variant attached to it. The variant should then **not** be applied to any other items in the cart, including other instances of the same base product.

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 83.0

**Additional context**
The WordPress installation is running on an Ubuntu 18.04 server.

**Comment by kidunot89** [comment]
@etoler1841 Can you provide steps to recreate your issue?

**Comment by etoler1841** [comment]
I think my initial description was off by a little bit. What's actually happening is that, for any product without a variation (e.g. a simple product), if you query the `variation` field, the resolver looks for a variation with ID `0`, gets confused, and ends up querying for variations without including an ID field (meaning it just returns all variations). Then, since it's a one-to-one field, it returns the first variation it finds, which should be the first variation ever created in your database for any product.

To reproduce, just make sure you have a product variation somewhere in your database, add a simple product to your cart, and query the `variation` field on your cart contents.

**Comment by thetre97** [comment]
Just a note to say that I have just come across the same issue...
