### ISSUE TITLE
Feature: provide a way to pass "$_POST" to WordPress.

### ISSUE THREAD

**Issue by jonshipman** [wp-graphql/wp-graphql-woocommerce#408]
I would like to mention that I ran into this issue using the Square gateway (they use the SkyVerge framework for adding to WooCommerce). In their validate_fields method they check their nonce by checking a $_POST field.

This results in the checkout mutation failing.

What I propose is adding a new type alongside the MetaDataInput inside CheckoutInput that would get moved to $_POST serverside. 

```gql
mutation MyMutation($nonce: String) {
  checkout(input: {clientMutationId: "feliznavidad", postData: [{key: "wc-square-credit-card-payment-nonce", value: $nonce}]}) {
    result
  }
}
```

Then over in PHP land

```php
function wgql_square_post_update() {
	global $_POST;
	$json = file_get_contents( 'php://input' );
	$data = json_decode( $json );

	foreach ( $data['variables']['input']['postData'] as $key => $value ) {
		$_POST[ $key ] = $value;
	}
}

add_action( 'woocommerce_checkout_process', 'wgql_square_post_update' );
```

Mind you, this is just a rough working example. Ideally you'd just process it alongside the input. But the result would be to support plugins that normally use traditional REST API checks. 

I am currently employing this method on an ecommerce site and it seems to be working successfully. I am using metaData however and that ends up saving post_meta to the database. A postData field would be strictly for shoehorning variables into $_POST.

Some examples of my code using metaData:
https://github.com/jonshipman/react-wp-shop/blob/master/php/includes/square-gql.php#L120
https://github.com/jonshipman/react-wp-shop/blob/master/src/Apollo.js#L57
https://github.com/jonshipman/react-wp-shop/blob/master/src/shop/gateway/Square.js#L55
https://github.com/jonshipman/react-wp-shop/blob/master/src/shop/checkout/ExternalPaymentMethod.js#L40

If this was brought into the core, this would prevent the need to do the custom fetch with Apollo and avoid saving extra data in the db.

Thoughts?

**Comment by kidunot89** [comment]
@jonshipman This is the dilemma faced with dealing with payment gateways outside of the traditional WooCommerce checkout page. And resolving it with the best practices in mind is out of the scope of WooGraphQL. Stay tuned for the [Harmonizing With WordPress](https://woographql.com/docs/harmonizing-with-wordpress) Docs, __coming soon,__ or read @jacobarriola's [article](https://jacobarriola.com/post/headless-woocommerce-checkout-options) to learn the recommended method of checkout.
