### ISSUE TITLE
No Schema available for wp-graphql-woocommerce(v0.7) and wp-graphql(1.0.4)

### ISSUE THREAD

**Issue by mohit242** [wp-graphql/wp-graphql-woocommerce#412]
**Describe the bug**
Similar to #357 
After installing wp-graphql, the GraphiQL IDE shows the wordpress schema.
But, subsequently installing wp-graphql-woocommerce, the IDE shows no-schema and in debug mode returns the following error 
```
{
  "errors": [
    {
      "debugMessage": "The pa_packs taxonomy cannot declare the same value for \"graphql_single_name\" and \"graphql_plural_name\".",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      }
    }
  ]
}
```

**To Reproduce**
Install the latest versions of both wp-graphql-woocommerce(v0.7) and wp-graphql(v1.0.3 or v1.0.4)
wp-graphql: 1.0.4
wp-graphql-woocommerce: 0.7
wordpress: 5.6
woocommerce: 4.8.0

**Expected behavior**
After activating both plugins, the schema for wordpress and woocommerce should be available in the IDE.

**Comment by kidunot89** [comment]
@mohit242 This is due to the name of your attribute. Would it be possible to rename it `pack` instead.

**Comment by mohit242** [comment]
@kidunot89 Really thanks for the help. I am still learning about posts and taxonomies in wordpress.
Looks like a plugin I had installed earlier created the pa_packs taxonomy and did not clear it up post uninstall.

unregister the taxonomy:
```php
            add_action('init', function() {
                unregister_taxonomy_for_object_type( "pa_packs", "product" );
            }, 100);
```

**Comment by aresrioja10** [comment]
> @mohit242 This is due to the name of your `packs` product attribute. Would it be possible to rename it `pack` instead.

Hi @kidunot89 What's the problem with "packs"? Is that it ends with "s"?

**Comment by kidunot89** [comment]
@aresrioja10 Pretty much, the **Inflect** class **WooGraphQL** uses is pretty basic.

**Comment by aresrioja10** [comment]
> @aresrioja10 Pretty much, the **Inflect** class **WooGraphQL** uses is pretty basic.

Ok, I'll take care while naming my attributes. Thanks!
