### ISSUE TITLE
UpdateShippingMethod mutation - shippingMethods only get the first value of an array

### ISSUE THREAD

**Issue by andyvu92** [wp-graphql/wp-graphql-woocommerce#418]
**Describe the bug**
It works great when only 1 shipping method is set (shippingMethods: "flat_rate:1"). However, when multiple shipping methods are set as an array (shippingMethods: ["flat_rate:2", "flat_rate:1"]), only the first shipping method in the array is taken.

**To Reproduce**

``
mutation UpdateShippingMethod {
  updateShippingMethod(input: {shippingMethods: ["flat_rate:2", "flat_rate:1"]}) {
    cart {
      chosenShippingMethod
      total
      subtotal
      shippingTotal
      availableShippingMethods {
        packageDetails
        supportsShippingCalculator
        rates {
          label
          methodId
          cost
          id
          instanceId
        }
      }
      fees {
        total
      }
    }
  }
}
``

**Expected behavior**
shippingMethods should allow more than 1 shipping method to be selected. This would help for stores with drop-shipping products where each product package will have its own shipping method to be selected.

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser: Chrome
 - Version: 87.0.4280.88

**Comment by kidunot89** [comment]
@andyvu92 I believe the bug is with the cart field `chosenShippingMethod`. It only displayed the chosen shipping method for the first shipping package.
