### ISSUE TITLE
Order status not updating (may be bug, maybe I am an idiot)

### ISSUE THREAD

**Issue by depthoffocus** [wp-graphql/wp-graphql-woocommerce#419]
**Describe the bug**
I don't seem to be able to update order status via the `updateOrder` mutation.

I can update other stuff like metaData, which is great!

**To Reproduce**

If I try something like:

```graphql
mutation {
  updateOrder(input:{
    orderId: 85,
    status: ON_HOLD, 
    
  }) {
    order { 
      databaseId
      status 
    }
  }
}
```

The status never changes. I've checked by using `id` instead of `orderId`, also with no effect.

Is there something else I need to do here to make this stick?

**Expected behavior**
The status would change :-)

**Additional context**

I had a look at the code for the mutation and noted that the code for this field does not seem to save the order:
```php
// Set status.
if ( ! empty( $input['status'] ) ) {
	$order->set_status( $input['status'] );
}
```

So I have found that this workaround works, for now:

```php
   \add_action('graphql_woocommerce_after_order_update', function ($order, $input, $context, $info) {
      if(isset($input['status'])) {
        $order->save();
      }
    }, 99, 4);
```

But should this be necessary?

Thank you for the **amazing** work which is making a complex job so much easier.

**Comment by kidunot89** [comment]
@depthoffocus Sorry for the late response. This could honestly be a bug. `updateOrder` hasn't been touch in quite some time :thinking: 
I'll look into this more and get back to you ASAP.

**Comment by depthoffocus** [comment]
No worries.
 
I actually ended up writing a custom mutation for the order progress actions I need, not least so that I can add a customer-facing order note at the same time, because the underlying wp-graphql seemingly doesn't support comment meta.

I've found this all amazingly workable and I'm so impressed with this project; it's transformative. So thanks again!

**Comment by yondifon** [comment]
> No worries.
> 
> I actually ended up writing a custom mutation for the order progress actions I need, not least so that I can add a customer-facing order note at the same time, because the underlying wp-graphql method for adding comments seemingly doesn't support comment meta.
> 
> I've found this all amazingly workable and I'm so impressed with this project; it's transformative. So thanks again!

Thanks for the workaround 
Worked well for me.
