### ISSUE TITLE
Querying image on Variable Product if product has no featured image causes internal server error

### ISSUE THREAD

**Issue by heggemsnes** [wp-graphql/wp-graphql-woocommerce#423]
**Describe the bug**
Querying any image field on the Variable Product where the "main" product doesn't have a Featured image causes internal server error.

**To Reproduce**
1. Create a variable product with no featured image
2. Generate some variations
3. (optional) add a image to the variation
4. Query the product:
```graphql
query ProductBySlug($id: ID!, $idType: ProductIdTypeEnum!) {
  product(id: $id, idType: $idType) {
    slug
    ... on VariableProduct {
      databaseId
      name
      description
      image{
        sourceUrl
      }
      price
      variations {
        nodes {
          databaseId
          image{
            sourceUrl
          }
          price(format: FORMATTED)
          salePrice
          stockQuantity
          type
          onSale
          name
        }
      }
    }
  }
}
```

5. Se error "Internal Server error"

**Expected behavior**
Should return null

**Screenshots**
![image](https://user-images.githubusercontent.com/36757859/105844384-71fed480-5fd9-11eb-8aee-4e22fe7a0190.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Chrome

**Comment by kidunot89** [comment]
@heggemsnes Can you pull down the `develop` branch of WooGraphQL and tell me if you issue persist. I'm having a problem recreating your issue.

**Comment by jacobarriola** [comment]
@kidunot89 I'm able to reproduce this error in a different context.

My error occurs in a `cart` query and only when I request a variation image. 

Repro steps:

* create a variable product
* generate one variation
* do not add a featured image or an image to the variation (👈🏽 this is the issue)
* add variation to cart
* Run cart query and include a request for the image on the **variation**:

```graphql
query getCart {
    cart {
      contents {
        itemCount
        edges {
          node {
            variation {
              node {
                image {
                  sourceUrl
                }
              }
            }
          }
        }
      }
    }
  }
```

Expected results:
* image returns null


Actual results:
Server error,  no cart returns. Message:
```
"debugMessage": "Argument 1 passed to WPGraphQL\\Data\\DataSource::resolve_post_object() must be of the type int, null given, called in /home/s36/html/wp-content/mu-plugins/wp-graphql-woocommerce/includes/type/object/class-product-variation-type.php on line 236"
```


Additional Notes:
* If I add either a featured image to the variable product or an image to the variation in question, the query runs as expected.
* Querying the product (even when no images are present both on the variation and parent product) works fine:
```graphql
query getCart {
    cart {
      contents {
        itemCount
        edges {
          node {
            product {
              node {
                image {
                  sourceUrl
                }
              }
            }
          }
        }
      }
    }
  }
```

Running:
WPGraphQL: 1.1.3
WooGraphQL: 0.7
