### ISSUE TITLE
Customer account cannot query order with filter

### ISSUE THREAD

**Issue by pewpewpew-sys** [wp-graphql/wp-graphql-woocommerce#426]
**Describe the bug**
Forgive me if i'm wrong, i don't really have much experience using wordpress. 
On Customer account i can't filter out the "Orders" for example using "first: [Int]". the "Orders" query always give me "10" limit of result and the "pageInfo.hasNextPage" always "false" even if i try filter "first: 2", e.g.
query {
  orders(first: 2) {...}
}

the problem only occurs on "customer" but as ShopManager(or admin) it give correct result/behaviour with given filters.
If this is a bug, are there any workaround that someone came out with? do you mind sharing the solution please???

**To Reproduce**
1. Go to 'https://woographql.com/playground'
2. Click on 'Login As Customer'

**Expected behavior**
query should give correct result/output with given filters.

**Screenshots**
![image](https://user-images.githubusercontent.com/78291619/106375969-6b020880-63c3-11eb-8a39-86729944b66d.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser chrome
 - Version  88.0.4324.96

**Comment by pewpewpew-sys** [comment]
so i just figuring out the solution, if we need to get orders from customer using:
query {
  customer(customerId: [CUSTOMER_ID]) { 
    orders(first: 1) {...}
    }
  }
}

the output is correct.

**Comment by kidunot89** [comment]
@pewpewpew-sys Yes the root-level `orders` query is restricted to non-admin users.
