### ISSUE TITLE
How to show the order summary after the checkout to a guest customer?

### ISSUE THREAD

**Issue by aresrioja10** [wp-graphql/wp-graphql-woocommerce#432]
**Describe the bug**
I'd like to show a thank you page to my customers once they have finish the ```checkout```. 

Woocommerce generates this URL:
```...order-received/{orderNumber}/?key={orderKey}```

For logged-in customers it's ok because I can query an order by his ```orderNumber``` and, using ```JWT auth```, the user has permission to access the data.

But, what happens to guests customers? They aren't authenticated so they don't have permissions to access to the order data. 

Also, what if I want to create an account in that page? Asking the guest customer for a password I can create a new account, but how can I link it with the order?

**Comment by kidunot89** [comment]
@aresrioja10 If the `billing_email` is set in the user session, their order can be queries using the `query { customer { orders { ... } } }`.

**Comment by aresrioja10** [comment]
No customer is associated to the order if I checkout as a guest user.

**Comment by aresrioja10** [comment]
I've checked that Woocommerce list my guest user in Woocommerce > Clients but if I execute this query it doesn't appear:

```
query MyQuery {
  customers {
    edges {
      node {
        id
        email
      }
    }
  }
}
```

**Comment by kidunot89** [comment]
@aresrioja10 Have you tried using `updateCustomer` to set the `billing_email` first?

**Comment by aresrioja10** [comment]
@kidunot89 I've solved it by saving the order data in local storage from the checkout to the thank you page.

**Comment by stug111** [comment]
@kidunot89 I also faced this problem, then can query order for guest. 
But variant with call  `query { customer { orders { ... } } }` work.  
Thanks, saved my time.

**Comment by brianpereradap** [comment]
@stug111 this worked for me also. Thanks for posting.
