### ISSUE TITLE
Reviews query grabbing all reviews instead of just for individual product

### ISSUE THREAD

**Issue by craigwilcox** [wp-graphql/wp-graphql-woocommerce#433]
**Describe the bug**
When doing a query for an individual product, we get all reviews for all products. Here is an example query: 

```query MyQuery {
  wpgraphql {
    product(id: "49691", idType: DATABASE_ID) {
      name
      reviews {
        edges {
          rating
          node {
            id
            content
          }
        }
      }
    }
  }
}
```

**To Reproduce**
1. Go to GraphiQL on version 0.7.0
2. Run a query for an individual product like above.
3. Notice it is bringing in all reviews.

**Expected behavior**
Like on earlier versions, 0.5.0, the query should get reviews for just one product.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Windows 10, Chrome, but happening on all browsers.

**Smartphone (please complete the following information):**

**Additional context**
This same query works great on 0.5.0.

Thanks!

**Comment by LeeBuckle** [comment]
Same issue here.

Reviews query also pulls in unrelated post comments too. In my project, the default hello world post comment that comes as part of a wordpress install is also being pulled into reviews.

**Comment by aresrioja10** [comment]
Same issue here. And as @LeeBuckle points, it show the default Hello World post comment.

Any update on this?

**Comment by kidunot89** [comment]
@craigwilcox @LeeBuckle @aresrioja10 I forgot about this. I'll get it patch ASAP

**Comment by aresrioja10** [comment]
Thanks @kidunot89 !
