### ISSUE TITLE
addToCart mutation on custom fields

### ISSUE THREAD

**Issue by sn3h** [wp-graphql/wp-graphql-woocommerce#440]
**Is your feature request related to a problem? Please describe.**
I need to let a customer  add custom value to product parameters, i.e. custom text on tshirt, and/or change value of the product based on those values.. Attributes have predefined values and cannot be customized. 

**Describe the solution you'd like**
Set custom fields value using AFC(or other solution that adds custom fields to products, like Advanced Product Fields for WooCommerce). 

**Describe alternatives you've considered**
After multiple fails to achieve this with WC + wpgqlWC, I am considering only calling login mutation with some private function not to expose JWT and creating product configured by the costumer before adding it to basket, but it has many problems such as I don't know if the order will be finished and paid at the moment of adding it. 

**Additional context**
Images of what state is unreachable now, source is images taken from https://product-demo.studiowombat.com/
![image](https://user-images.githubusercontent.com/768656/108580798-6fb83d80-732d-11eb-946c-2b2c66396626.png)
![image](https://user-images.githubusercontent.com/768656/108580842-9fffdc00-732d-11eb-90a6-d05417d8255f.png)
baseket : ![image](https://user-images.githubusercontent.com/768656/108580887-d6d5f200-732d-11eb-8dca-f276f9612452.png)

**Comment by jasminetracey** [comment]
@sn3h Did get a workaround for this?

**Comment by kidunot89** [comment]
@sn3h You should be able to your desired functionality with WooGraphQL Pro and Product Addons, otherwise your feature request is beyond the scope of WooGraphQL. I'll be closing this issue.
