### ISSUE TITLE
Critical Error - Tested on WP GQL 1.1.5 - 1.1.0

### ISSUE THREAD

**Issue by RigTag** [wp-graphql/wp-graphql-woocommerce#442]
### **Getting a Error on the graphql URL**
```
There has been a critical error on this website.
```

**WooGraphQL 0.7.0
WP GraphQL 1.1.5 - 1.1.0**
---------------------------------------------------------------------------
Getting a Error on the graphql URL
```
{"errors":[{"debugMessage":"The pa_brands taxonomy cannot declare the same value for \"graphql_single_name\" and \"graphql_plural_name\".","message":"Internal server error","extensions":{"category":"internal"}}]}
```

**WooGraphQL 0.7.0
WP GraphQL v1.0.5 -**

---------------------------------------------------
WP: 5.6.2
WC: 5.0.0

**Comment by kidunot89** [comment]
@RigTag Try change the name of your taxonomy from `Brands` to `Brand`.

**Comment by RigTag** [comment]
> @RigTag Try changing the name of your taxonomy from `Brands` to `Brand`.

It was a attribute for byproduct..

Thank you :)

**Comment by csellis** [comment]
@RigTag Which attribute? I'm experiencing this now
