### ISSUE TITLE
0.8.0 - queries take too long to respond

### ISSUE THREAD

**Issue by jacobarriola** [wp-graphql/wp-graphql-woocommerce#446]
**Describe the bug**
Queries are taking too long to respond. For example, an http GET request to `my-domain/graphql` endpoint now takes on average ~10secs to load. Pre-0.8.0 it would load in ~1sec.

**To Reproduce**
1. Update wp-graphql-woocommerce from https://github.com/wp-graphql/wp-graphql-woocommerce/commit/e14e712dedb3e574c0b1e342f42c8650c477433b -> 0.8.0
2. Load your /graphql endpoint

**Expected behavior**
Site responds within one second.

**Actual behavior**
Site responds in 10 seconds.

**Plugin Versions**
- **WooGraphQL Version:** 0.8.0
- **WPGraphQL Version:** 1.18
- **WordPress Version:** 5.6.2
- **WooCommerce Version:** 4.7

**Comment by jacobarriola** [comment]
@kidunot89 fyi, the server kept throwing a lot of ErrorExceptions. All of them seem related to composer.

Here's one example:
https://sentry.io/share/issue/629d37d0ba644afb8332b9fadc10739c/

**Comment by kidunot89** [comment]
@jacobarriola links not working

**Comment by jacobarriola** [comment]
Sorry, I merged a lot of the issues. Try this one: https://sentry.io/share/issue/197f0570581741fca5673e8d4c9cebe6/

**Comment by kidunot89** [comment]
@jacobarriola It looks like there might be an issue with the classloader. `webonyx/graphql-php` is a dependency of WPGraphQL not WooGraphQL. Is it possible for you to run `composer dumpautoload --no-dev -o` in WooGraphQL's root directory?

**Comment by kidunot89** [comment]
@jacobarriola Found the issue. Somehow `webonyx/graphql-php` got added as a dependency package :man_facepalming:.
This is already a dependency of `wp-graphql/wp-graphql` and should never be a dependency of an extension. I'll remove the package and rebuild the v0.8.0 tag/release.

**Comment by kidunot89** [comment]
@jacobarriola The v0.8.0 release has be rebuilt, redownload it and confirm that the speed down and be eliminated.

**Comment by jacobarriola** [comment]
@kidunot89 looks like your fix resolved the issue. I'm no longer seeing the reported errors. Thanks for the quick response!
