### ISSUE TITLE
Few arguments on woocommerce_after_checkout_validation

### ISSUE THREAD

**Issue by CervarlCG** [wp-graphql/wp-graphql-woocommerce#448]
**Describe the bug**
The do_action woocommerce_after_checkout_validation on checkout mutation only pass the data to the hook and omit the errors array, i see that the plugin make a thrown if there is a error but another plugins that depends of that hook (pe. B2BKing) expect 2 arguments, data and errors, this cause a internal server error because the x function that expect 2 arguments (data and errors) only receive one.

**To Reproduce**
1. do a add_action('woocommerce_after_checkout_validation', 'my_checkout_validation_function_that_expects_data_and_errors');
3. make a checkout mutation
4. See the internal server error

**Expected behavior**
do action pass a empty errors array

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chrome

**Comment by jeebay** [comment]
@CervarlCG @kidunot89 I've put up a PR for this. This is a blocker for me at the moment as Dokan expects 2 arguments and doesn't even check whether the second is an instance of `WP_Error` before calling methods on it. WooCommerce core [passes an instance](https://github.com/woocommerce/woocommerce/blob/trunk/includes/class-wc-checkout.php#L1154-L1161) of `WP_Error` as the second param so I guess I don't blame them.
