### ISSUE TITLE
The plugin only fetches the first page

### ISSUE THREAD

**Issue by MobyDigg** [wp-graphql/wp-graphql-woocommerce#461]
I am using "gatsby-source-wordpress": "4.0.5" with 

```
schema: {
    perPage: 5,
    requestConcurrency: 2,
    previewRequestConcurrency: 2,
  },
```

…and I consistently only get 5 products:

```
success  gatsby-source-wordpress  Product - 44.073s - fetched 5
```

happens with WPGraphQL WooCommerce (WooGraphQL) 0.8.1.

@kidunot89 do you have an idea how to fix this?

**Comment by jacobarriola** [comment]
@MobyDigg I'm keeping an eye on this ticket, but I'm not sure if that plugin officially supports WC yet (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/usage-with-popular-wp-graphql-extensions.md#unconfirmed-extensions-might-still-work-but-will-have-problems)

I'm still running the plain `gatsby-source-graphql` plugin on my WC project.
