### ISSUE TITLE
Orders placed by a client is visible as a guest order, not a client's one

### ISSUE THREAD

**Issue by topheroes** [wp-graphql/wp-graphql-woocommerce#462]
Hello,

Thank you for the great plugin! 
I was wondering if I'm getting this right. In order to place an order the client should log in first.

```
mutation LoginUser {
  login( input: {
    clientMutationId: "1212",
    username: "username",
    password: "pass"
  } ) {
    authToken
    user {
      id
      name
    }
  }
}
```

We're getting authToken from the result of this mutation, which we'll use later in header as 
Authorization: Bearer ${authToken}
in all subsequent mutations.
Also woocommerce-session header is copied to our header too.

Then we'll add some items to our cart:

```
mutation cartAdd{
  addToCart(input: { productId: 101, quantity: 2, clientMutationId: "1212" }){
    
    cartItem {
      quantity
      subtotal
      subtotalTax
      tax
      total
    }
  }
}
```

Then we make a checkout:

```
mutation checkout{
    checkout( input:{clientMutationId:"1212", isPaid:false, billing:{address1: "Street", email:"PATH@MAIL.com", firstName:"Name", lastName:"Surname", postcode:"244", phone:"12892121"} paymentMethod:"cod"} ) {
        clientMutationId
         
    }
}
```

The order is visible in wordpress backend, but it's visible as a guest order. Am I doing anything wrong?

Thank you in advance!

**Comment by topheroes** [comment]
Also is there a way for a customer to list all previous orders?

Once again, thank you in advance!

**Comment by flocosnier** [comment]
Hello,

I'm facing the same issue, not being able to link an order with the customer via the checkout mutation.

Is there a solution ? 

Thank you in advance !

**Comment by Macuzzin** [comment]
Hi, same issue here. Anyone found a solution?

**Comment by flocosnier** [comment]
Hi ! Yes I solved it, it was a header issue. You have to put the customer token in the request and it should work :)

**Comment by Macuzzin** [comment]
Hi @flocosnier - thanks for your response :) Would you mind sharing in a bit more detail how you achieved this? I have my WooCommerce session stored in the GraphQL request middleware (Apollo client) and my customer token stored in a cookie. I use a Next.js API route to inject the token into the query below and the response I get is "No session found".

`import { getAuthToken } from "../../src/utils/cookie"
import client from "../../src/components/ApolloClient"
import CHECKOUT_MUTATION from "../../src/mutations/checkout"

export default async (req, res) => {
  if (req.method === "POST") {
    if (!req.headers.cookie) {
      res.status(403).json({ message: "Not Authorised" })
      return
    }

    const { orderData } = req.body

    const authToken = getAuthToken(req)

    const session = process.browser ? localStorage.getItem("woo-session") : null

    const { data, error } = await client.mutate({
      mutation: CHECKOUT_MUTATION,
      variables: {
        input: orderData
      },
      context: {
        headers: {
          authorization: `Bearer ${authToken}`
        }
      }
    })

    console.log(data)
  } else {
    res.setHeader("Allow", ["POST"])
    res.status(405).json({ message: `Method ${req.method} not allowed` })
  }
}`

**Comment by flocosnier** [comment]
Aren't you forgetting the session header ?

```
headers: {
  woocommerce-session: `Session ${session}`
  authorization: `Bearer ${authToken}`
}
```

**Comment by anikrauth** [comment]
> Hi @flocosnier - thanks for your response :) Would you mind sharing in a bit more detail how you achieved this? I have my WooCommerce session stored in the GraphQL request middleware (Apollo client) and my customer token stored in a cookie. I use a Next.js API route to inject the token into the query below and the response I get is "No session found".
> 
> `import { getAuthToken } from "../../src/utils/cookie" import client from "../../src/components/ApolloClient" import CHECKOUT_MUTATION from "../../src/mutations/checkout"
> 
> export default async (req, res) => { if (req.method === "POST") { if (!req.headers.cookie) { res.status(403).json({ message: "Not Authorised" }) return }
> 
> ```
> const { orderData } = req.body
> 
> const authToken = getAuthToken(req)
> 
> const session = process.browser ? localStorage.getItem("woo-session") : null
> 
> const { data, error } = await client.mutate({
>   mutation: CHECKOUT_MUTATION,
>   variables: {
>     input: orderData
>   },
>   context: {
>     headers: {
>       authorization: `Bearer ${authToken}`
>     }
>   }
> })
> 
> console.log(data)
> ```
> 
> } else { res.setHeader("Allow", ["POST"]) res.status(405).json({ message: `Method ${req.method} not allowed` }) } }`

How Can I get WooCommerce session??
