### ISSUE TITLE
Cursor pagination returns empty result

### ISSUE THREAD

**Issue by Kvintus** [wp-graphql/wp-graphql-woocommerce#465]
**Describe the bug**
When I try to get a second page of products, I get an empty result even though there should be data on the next page. ( Took first 5 and there is 25 products in the database )

**To Reproduce**
1. Install latest WPGraphql
2. Install wp-graphql-woocommerce 0.81
3. make a paginated query with first: <numner> and after: <endCursor> with endCursor of the previous query

**Expected behavior**
Should get the next n results after the cursor.

**Screenshots**
![image](https://user-images.githubusercontent.com/9382870/113436454-05db8b00-93e5-11eb-85a1-0cecc30717d3.png)

**Desktop (please complete the following information):**
 - OS: macOS Bigsur
 - Browser Brave
 - Version 89

**Plugin Versions**
- **WooGraphQL Version:** 0.89
- **WPGraphQL Version:** 1.3.3
- **WordPress Version:** 5.7
- **WooCommerce Version:** 5.1.0

https://user-images.githubusercontent.com/9382870/113436389-ed6b7080-93e4-11eb-8c18-eb3731f968b2.mov

**Comment by wcoppens** [comment]
We are experiencing the same. Our research found out that when you increase your `first` property with the page no. (e.g. ITEMS_PER_PAGE * PAGE_NO) and also apply the `after` property. You do get the correct response, but that is not how it supposed to work. So in your case with the video, to get the second page you could increase the value of the `first` parameter to 10. This way you get the expected response (could be a temporary workaround).

Luckily in our case we only have like 10 products in our store and we don't mind to query them all at once.

**Comment by Kvintus** [comment]
> We are experiencing the same. Our research found out that when you increase your `first` property with the page no. (e.g. ITEMS_PER_PAGE * PAGE_NO) and also apply the `after` property. You do get the correct response, but that is not how it supposed to work. So in your case with the video, to get the second page you could increase the value of the `first` parameter to 10. This way you get the expected response (could be a temporary workaround).
> 
> Luckily in our case we only have like 10 products in our store and we don't mind to query them all at once.

Yeah just came here post the same finding. We are going to use that for the time being but it's a very dirty hack, and the nature of it makes me wonder whether it is not loading all the products into the memory under the hood anyway...

**Comment by Kvintus** [comment]
Update on this... The method described above by @wcoppens works but only up to 100 products. After that the behaviour is the same, ie. no products displayed.

**Comment by PaperPlaneSoftware** [comment]
https://github.com/wp-graphql/wp-graphql/issues/1854
