### ISSUE TITLE
How can i change the shippingMethod and shippingClass in cart-object?

### ISSUE THREAD

**Issue by ax-hack** [wp-graphql/wp-graphql-woocommerce#466]
I added a 'product' using 'addToCart' method, and then i need set 'shippingMethod' and 'shippingClass' too. 
How can i make this?

**Comment by wcoppens** [comment]
@ax-hack You can using the `updateShippingMethod` mutation and also during the checkout with the `checkout` mutation. 
Please keep in mind you do need to use the woocommerce-session.

You can check the required arguments in the GraphiQL playground in Wordpress.
