### ISSUE TITLE
Add to Cart with custom Price

### ISSUE THREAD

**Issue by jacobdubail** [wp-graphql/wp-graphql-woocommerce#469]
**Is your feature request related to a problem? Please describe.**
Our products have custom pricing based upon configuration. Prices range from $9 to $190 and can vary down to the penny. So, I'm unable to use Variations.

**Describe the solution you'd like**
In a WP theme, I'm able to override product price during the add to cart action. Having the ability to post a custom price in the `addToCart` mutation would make my life a lot easier.

**Describe alternatives you've considered**
If I pass the custom price as `extraData`, am I able to parse that in PHP before the product is added to the cart? And is this the correct format? `{"price": "22.72" }`

Thank you!

**Comment by miguderp** [comment]
I finally managed to make it work on my end; PHP was probably throwing silent errors in the back so I couldn't understand what was happening but you need to unescape your `"` in order to make the `json_decode()` properly work

```
query Foo {
   addToCart(input: { productId: 123, extraData: "{\"name\":\"foo\",\"value\":\"bar\"}"} ) {
      [...]
   }
}
```

Before this, I was trying to send my JSON as `"{'name': 'foo','value': 'bar'}"` without any success.

**Comment by kidunot89** [comment]
@jacobdubail @aresrioja10 @miguderp I'm sorry for missing this issue. Yes the current format in JSON string. This will change as soon as possible. I kinda throw that part of the schema up without any forethought. My bad 😅 .

**Comment by jacobdubail** [comment]
> @jacobdubail @aresrioja10 @miguderp I'm sorry for missing this issue. Yes the current format in JSON string. This will change as soon as possible. I kinda throw that part of the schema up without any forethought. My bad 😅 .

All good. I finally figured it out. I appreciate the response!

**Comment by OisinOKeeffe** [comment]
Did you use a plugin to facilitate custom pricing? if so can you let me know which one you used? I need to charge a price based off of the customer profile and am lost as to how I might do this.

Thanks in advance for your help.

**Comment by jacobdubail** [comment]
> Did you use a plugin to facilitate custom pricing? if so can you let me know which one you used? I need to charge a price based off of the customer profile and am lost as to how I might do this.
> 
> Thanks in advance for your help.

I have a custom Next.js API route where I run custom calculations based upon the product configuration. I pass this back to the addToCart mutation in the extras parameter. I then catch that parameter in WordPress and use it as the product price.

Does that make sense?

**Comment by ardiewen** [comment]
Hey @jacobdubail, can you describe what filter / hook / action you're catching on the wordpress end? I'm looking to catch this data as well on a LineItem basis after `checkout` is submitted, during the order creation step.
