### ISSUE TITLE
Checkout mutation throws Internal Error (Non-static method cannot be called statically)

### ISSUE THREAD

**Issue by marcjcs** [wp-graphql/wp-graphql-woocommerce#472]
**Describe the bug**
Whenever the Checkout mutation is called, an internal error is returned, upon enabling the debug message, I got "Non-static method WPGraphQL\WooCommerce\Data\Mutation\Checkout_Mutation::update_session() cannot be called statically".

I've been trying to implement the checkout on my Nuxt.js website for some time now and I can't seem to find how to fix that, I checked similar projects (Nuxt, Next and Gatsby) to see if my implementation was off but it seems everything should be working correctly, I cloned some of these repos and confirmed the error still happens.

```json
{
    "errors": [
        {
            "debugMessage": "Non-static method WPGraphQL\\WooCommerce\\Data\\Mutation\\Checkout_Mutation::update_session() cannot be called statically",
            "message": "Internal server error",
            "extensions": {
                "category": "internal"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "path": [
                "checkout"
            ]
        }
    ],
    "data": {
        "checkout": null
    },
    "extensions": {
        "debug": []
    }
}
```

**To Reproduce**
Install the plugins, then try to send a valid checkout mutation.

**Expected behavior**
Checkout should be working.

**Desktop (please complete the following information):**
 - OS: Arch Linux x86_64
 - Browser Chromium
 - Version 89.0.4389.114

**Plugin Versions**
- **WooGraphQL Version:** 0.6.1 or latest (tried on both)
- **WPGraphQL Version:** 1.2.4 or latest (tried on both)
- **WordPress Version:** 5.6.0 or latest (tried on both)
- **WooCommerce Version:** 5.0.0 or latest (tried on both)

**Comment by boxxroom** [comment]
I've just come to report the same bug and can confirm this is happening.

<img width="1994" alt=" non-static-methods-called" src="https://user-images.githubusercontent.com/33870545/121725640-712a9300-cae1-11eb-82a3-b6da59e22ebf.png">

In PHP non-static methods shouldn't be invoked statically just because it is in a static method. To invoke a non-static method within a static method an instance of the underlying class should either be (re)instantiated or plucked from cache.

This actually makes (for me) the order to fail.

More than happy to create PR with the fixes in place if required.

**Comment by kidunot89** [comment]
@boxxroom @marcjcs This was patched by @manuelsampl in #507 and will be included in release **v0.10.0**

**Comment by boxxroom** [comment]
@kidunot89 

There appears to be another non-static method being called statically in the same file:

`process_order_payment($order_id, $data['payment_method']);`

called from `line #562 - public static function process_checkout($data, $input, $context, $info, &$results = null)` invoked on `line #610 - process_order_payment($order_id, $data['payment_method']);`


###Method
<img width="643" alt="method" src="https://user-images.githubusercontent.com/33870545/121952839-ad195e80-cd54-11eb-903c-b6efa8e61e57.png">

###Called
<img width="668" alt="called" src="https://user-images.githubusercontent.com/33870545/121952835-abe83180-cd54-11eb-853d-34041026b13a.png">

**Comment by boxxroom** [comment]
@kidunot89 Just thought I'd re-mention this incase the release is imminent. Again happy to send a PR for this.

**Comment by boxxroom** [comment]
@kidunot89 Just to add to this, in the same file called under the same `process_checkout` method, there is another method called statically which isn't a static method.

Method `protected function process_order_without_payment` line `551` called statically at line `651`

**Comment by lu-wei-chen** [comment]
@kidunot89 Hi there,
I came across the same issue, whereas I'm using the newer versions as below.
**Plugin Versions**
- **WooGraphQL Version:** …
- **WPGraphQL Version:*1.5.5* …
- **WordPress Version:*5.8*
- **WooCommerce Version:*5.5.2*

Also checked in the code in _class-checkout-mutation.php_  as #472 descripted, whatever should be static is static. 
Is there any other reason could possibly make it throw this error? Probably missing anything that's required in query?

I'm using Next.js. And here's my **query**:
`
mutation ($input: CheckoutInput!) {
  checkout(input: $input) {
    order {
      id
      refunds {
        nodes {
          amount
        }
      }
    }
    customer {
      id
    }
    result
    redirect
  }
}
`
**query variables**
`
{
  "input": {
    "clientMutationId": "myId",
	"billing": {
      "firstName": "LU",
      "address1": "102 hills",
      "address2": "street",
      "city": "TPE",
      "country": "TW",
      "phone": "+886955235103"
    },
    "isPaid": false,
    "shipToDifferentAddress": false,
    "paymentMethod": "cod",
    "shipping": {
      "address1": "102 hills",
      "address2": "street",
      "city": "TPE",
      "country": "TW",
      "phone": "+886955235103"
    }
  }
}
`
