### ISSUE TITLE
Cursor pagination doesn't work

### ISSUE THREAD

**Issue by PaperPlaneSoftware** [wp-graphql/wp-graphql-woocommerce#474]
Maybe I'm doing something wrong or maybe this is a problem with wp-graphql-woocommerce but cursor pagination seems broken. I'm using the latest version of wp-graphql (v1.3.5). My query looks something like this:

```graphql
query GetProducts {
    products(
      first: 4,
      after: ""
    ) {
    	edges {
        node {
          name
        }
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
```
The first time I run this (with an empty or null `endCursor`) I get products back and I get a new `endCursor`. However, if I use the returned `endCursor` by inserting it in `after` and rerun the query I get no results.

Oddly, if I then change the number of products I want returned by setting `first` to some other value it suddenly works again.

**Comment by etoler1841** [comment]
Came here to report the same issue. Rolling back WPGraphQL to v1.2.5 fixed the problem for me. I thought it might be related to the pagination fix that came out in 1.3.4, but the problem persisted even after I rolled back to 1.3.3.

**Comment by PaperPlaneSoftware** [comment]
> Came here to report the same issue. Rolling back WPGraphQL to v1.2.5 fixed the problem for me. I thought it might be related to the pagination fix that came out in 1.3.4, but the problem persisted even after I rolled back to 1.3.3.

That worked for me also.

**Comment by PaperPlaneSoftware** [comment]
v1.2.6 also works but I noticed that with this version installed my WP server crashes periodically (or it might be the database that's crashing). This happens when I rerun some GQL queries. 

v1.3.0 is completely unstable. My wordpress server constantly crashes so I'm not sure if the pagination bug exists in that version or not. 

v1.3.1 is the fist version in which the pagination bug appears. But it also seems to resolve whatever was causing my server to crash. This version appears to be completely stable, it's just the pagination bug rears it's ugly head.

**Comment by PaperPlaneSoftware** [comment]
@kidunot89 do you need some help on this issue? Any pointers to where the problem may be?

**Comment by niklaslovgren** [comment]
@PaperPlaneSoftware, thanks for reporting this. Also reproduced this behavior, and rolling back WPGraphQL to v1.2.5 did indeed work.

However, still faced an issue with fewer products than expected being returned. This seemed somewhat related to the visibility and published status of the product, e.g. private products wouldn't show up in the results but would "occupy" one of the result slots. Changing the product's status from private to published yielded expected results. However, some private products did show up in the result set, so this isn't a consistent error.

In any case: should anyone else run into this problem, a workaround is to filter out unpublished and hidden products by using a where parameter. This worked for me; YMMV.

Example (expanding on PaperPlaneSoftware's example):
```graphql
query GetProducts {
    products(
        first: 4,
        after: "",
        where: {
            "status": "publish",
            "visibility": "VISIBLE"
        }
    ) {
        edges {
            node {
                name
            }
        }
        pageInfo {
            endCursor
            hasNextPage
        }
    }
}
```

(WPGraphQL 1.2.5, WooGraphQL 0.8.1, WooGraphQL Product Bundles 0.0.4)
