### ISSUE TITLE
A simple example of a "complex" Product query

### ISSUE THREAD

**Issue by simplenotezy** [wp-graphql/wp-graphql-woocommerce#476]
I'd love to see an simple example of a complex search query, something like this:

```
{
   "post_type":"product",
   "posts_per_page":26,
   "orderby":"meta_value_num",
   "lang":"en",
   "tax_query":{
      "relation":"AND",
      "0":{
         "relation":"AND",
         "0":{
            "taxonomy":"pa_material",
            "field":"slug",
            "compare":"IN",
            "terms":[
               "gold"
            ]
         },
         "1":{
            "taxonomy":"pa_stone",
            "field":"slug",
            "compare":"IN",
            "terms":[
               "citrines"
            ]
         }
      }
   },
   "paged":1,
   "meta_query":{
      "relation":"AND",
      "0":{
         "relation":"OR",
         "0":{
            "key":"_discontinued",
            "compare":"NOT EXISTS"
         },
         "1":{
            "key":"_discontinued",
            "value":1,
            "compare":"!=",
            "type":"NUMERIC"
         }
      }
   },
   "meta_key":"total_sales",
   "order":"desc"
}
```

It's something I don't see examples on specifically. The closest I get is the "Quick Tip" located at the bottom of this page: https://woographql.com/guides/create-react-app/1-creating-the-product-list yet I don't see any actual examples of how it's done.

I also think it's something the documentation could heavily benefit from, if such examples where provided. I'd be happy to make a PR once I've seen some examples.

**Comment by simplenotezy** [comment]
Also, since this issue is now effectively a "noob" question issue, I am also curious whether it possible to return sub-query results of a given search. Let's say I have a Product Filter List, and I'd like to include options for the user to "tick off" certain categories. I don't want to show the categories which have 0 results (combined with they existing query), and also I'd like to show a number of how many products will be under such a query. Screenshot example:

![image](https://user-images.githubusercontent.com/3786627/115115794-a198f980-9f96-11eb-9af6-c8398525eb95.png)

![example product list filter](https://user-images.githubusercontent.com/3786627/115115837-dd33c380-9f96-11eb-9f2c-808a6937a3fe.gif)

**Comment by kidunot89** [comment]
@simplenotezy There are some pretty complex product queries in the unit test, like [this one](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/tests/wpunit/ProductQueriesTest.php#L310)
