### ISSUE TITLE
price(format: RAW) returns null for VariableProduct

### ISSUE THREAD

**Issue by kdotamoh** [wp-graphql/wp-graphql-woocommerce#479]
**Describe the bug**
`price(format: RAW)` returns `null` for VariableProduct

**To Reproduce**
```
query GetProductsQuery {
    products(first: 20) {
      nodes {
        id
        ... on VariableProduct {
          id
          name
          variations {
            nodes {
              price(format: RAW)
            }
          }
        }
      }
    }
  }
```

**Expected behavior**
Get price without a currency symbol

**Screenshots**
In GraphiQL the price displays with no issue but returns null in the browser:
![image](https://user-images.githubusercontent.com/21177558/115909752-75c8b880-a45b-11eb-82c5-26bd4b8b5faa.png)
![image](https://user-images.githubusercontent.com/21177558/115909766-7a8d6c80-a45b-11eb-882b-bd485f008440.png)

**Desktop (please complete the following information):**
 - OS: macOS Version 10.15.5
 - Chrome 90.0.4430.72

**Plugin Versions**
- **WooGraphQL Version:** 0.8.1
- **WPGraphQL Version:** 1.3.5
- **WordPress Version:** 5.7.1
- **WooCommerce Version:** 5.2.2 

**Additional context**
It looks like the issue was solved for SimpleProducts #207, but persists for VariableProducts.

**Comment by phidalgot** [comment]
Good afternoon, I have the same problem with next.js

**Comment by jacobarriola** [comment]
@kdotamoh I think it may be an authentication issue. I know for stock wp-graphql fields like `content` in the `Post` type, adding the `RAW` param is an authenticated request, which is why it works in GraphiQL (because you're authenticated) but `null` in the browser.

**Comment by kdotamoh** [comment]
@jacobarriola Interesting, that sounds plausible. If that's the case visitors to a website (who aren't authenticated) will be unable to view variable products. Sounds like a bug, no?

**Comment by devidw** [comment]
Still experiencing the same behaviour with variable products.

- When logged in as admin and viewing the page `raw` works
- When logged in as customer and viewing the page `raw` gives `null`

In both cases, a user is authenticated.

Sorry if I am missing something?

---

WooCommerce 7.1.0
WP GraphQL 1.12.1
WPGraphQL WooCommerce (WooGraphQL) 0.11.2
