### ISSUE TITLE
Selling locations

### ISSUE THREAD

**Issue by Jonofat** [wp-graphql/wp-graphql-woocommerce#480]
I have created a checkout page and I need to display the selling locations I specified in WooCommerce. Since I don't ship worldwide, I have only listed. a few countries there. Is this field available in the GraphQL explorer. I am struggling to find it if it is there.

The WooCommerce field is 'sell to specific countries'.

**Comment by kidunot89** [comment]
@Jonofat No this feature does not exist, but it can be implemented rather easily

**Comment by DaoQuangThiet** [comment]
> @JonofatKhông, tính năng này không tồn tại, nhưng nó có thể được thực hiện khá dễ dàng

@kidunot89 How to do it ?

**Comment by kidunot89** [comment]
@Jonofat @DaoQuangThiet This will be coming in the next release see PR #736 here
