### ISSUE TITLE
WooGraphQL in the official WordPress Plugins Repository

### ISSUE THREAD

**Issue by loureirorg** [wp-graphql/wp-graphql-woocommerce#485]
**Is your feature request related to a problem? Please describe.**
I tried to install WooGraphQL via my admin dashboard, but I couldn't find the plugin there. The plugin is not in the official WordPress plugins repository.

README says to install via zip file, but I prefer to install plugins via the official WordPress plugins repository. The reasons are many: 
- Easy to detect the plugin is outdated: I can see a huge red icon telling me the plugin is outdated;
- Easy to update: I just need to click a button;
- Automatic-updates: I can set WP to update the plugin on minor version changes automatically;
- And many others;

**Describe the solution you'd like**
Put this plugin in the official WordPress repository.

**Describe alternatives you've considered**
You can automate this task (GitHub -> WP repo) with the action `10up/action-wordpress-plugin-deploy` by 10up. I use it with my plugin, and it works perfectly.

**Additional context**
Many thanks for the great plugin. This feature is not a requirement, but it would be great if implemented.

**Comment by w3bdesign** [comment]
@loureirorg 

I believe the reason is because the plugin has not reached a version 1 release yet.

In other words, it is not yet ready for production, which is most likely why it has not been published there yet.

**Comment by kidunot89** [comment]
☝🏿 See the [roadmap](https://github.com/wp-graphql/wp-graphql-woocommerce/projects/1) for a general checklist of what's left to be implemented, but I don't update it too often and some features need to be added.
