### ISSUE TITLE
Cart not getting empty after checkout

### ISSUE THREAD

**Issue by akshaykatale99** [wp-graphql/wp-graphql-woocommerce#490]
**Describe the bug**
Cart not getting empty after checkout mutation

Using this mutation with the custom payment method.

    checkoutMutation({
                    variables: {
                        input: {
                            billing: checkoutData.customer.billing,
                            isPaid: true,
                            clientMutationId: "testcartcheckout",
                            paymentMethod: "razorpay",
                            transactionId: data.razorpay_payment_id
                        }
                    }
                })

**Expected behavior**
After checkout cart should be empty.

Tested on latest version of this plugin

**Comment by davevanhoorn** [comment]
You can use the `emptyCart` mutation on a successful checkout.
