### ISSUE TITLE
Inconsistent product page / shop page results when using upstream `contentNode` query

### ISSUE THREAD

**Issue by ardiewen** [wp-graphql/wp-graphql-woocommerce#491]
### Context

One recognized page building pattern is to use the `ContentNode` interface for all post types. The primary benefit of this is when using `wp-graphql-acf` in conjunction with multiple post types, gives us the ability to reuse fragments across these post types.

<details>
<summary>An example of why this is important...</summary>
Let's say you have custom fields called `ACF` that you want to use on `Page`, `Post`, `Product`, and `Some CPT`.

Your query / fragment combination in the past would be:
```
fragment PageAcfFields on Page_ACF {
   ...
}
fragment PostAcfFields on Post_ACF {
   ...
}
fragment ProductAcfFields on Product_ACF {
   ...
}

query GET_ALL_PAGES {
   nodes {
      ACF {
        ...PageAcfFields 
     }
   }
}
query GET_ALL_POSTS {
   nodes {
      ACF {
        ...PostAcfFields 
     }
   }
}
query GET_ALL_PRODUCTS {
   nodes {
      ACF {
        ...ProductAcfFields 
     }
   }
}
```

As you can see, this can quickly get out of hand when you scale into CPTs, and multiple shared fragments across post types.

Using the `ContentNode` interface, we can do something like this:

```
fragment ContentAcfFields {
   ...
}

query GET_ALL_CONTENT_NODES($first: Int, $after: String) {
  contentNodes(first: $first, after: $after) {
    nodes {
        __typename
        id
        uri
        ACF {
          ...ContentAcfFields
        }
    }
  }
}

```

Much better, right?
</details>

### Observed Problems

When testing this with a fresh install of wordpress + woocommerce, we can see that all the woocommerce product types including `ProductVariation`,  `SimpleProduct`, `VariableProduct`, `ExternalProduct`, `GroupProduct` become available underneath contentNode: 
<img width="1474" alt="Screen Shot 2021-05-10 at 6 01 27 PM" src="https://user-images.githubusercontent.com/39966887/117730108-da08ad80-b1b9-11eb-8a15-9c61ddfa5f8d.png">

However, when we query for all content nodes, nothing shows up! Querying for the first 100 content nodes in my sandbox yields only `Page` and `Post` post types.
<img width="1517" alt="Screen Shot 2021-05-10 at 6 05 47 PM" src="https://user-images.githubusercontent.com/39966887/117730493-67e49880-b1ba-11eb-9eb6-f78754bc5db1.png">

As a sanity check, this is what it looks like when we query for `products` instead:
<img width="1517" alt="Screen Shot 2021-05-10 at 6 07 56 PM" src="https://user-images.githubusercontent.com/39966887/117730673-b7c35f80-b1ba-11eb-80fe-a667a88108d0.png">

Not sure if this could be an upstream issue as well, so I'll create another issue in the main wp-graphql repo as well and link it here.

**Plugin Versions**
- **WooGraphQL Version:** 0.8.1
- **WPGraphQL Version:** 1.3.5
- **WordPress Version:** 5.7.1
- **WooCommerce Version:** 5.2.2

**Additional context**

**Comment by kidunot89** [comment]
@ardiewen I can't pinpoint when but this issue has been resolved
![image](https://github.com/wp-graphql/wp-graphql-woocommerce/assets/13604318/38e0f6c9-2662-4930-bfd2-ce6a82bd6d26)
