### ISSUE TITLE
Error: Name "___________________________" must not begin with "__", which is reserved by GraphQL introspection.

### ISSUE THREAD

**Issue by iqwik** [wp-graphql/wp-graphql-woocommerce#498]
**Describe the bug**
This happened only after activate plugin, when start `gatsby develop` i have an error. If deactivate -> it's working

**To Reproduce**
1. install wordpress 5.7.2
2. add and activate plugins (last and actual versions)
    - headless cms:  1.2.0
    - woocommerce: 5.3.0
    -  WP Gatsby: 1.0.10
    - WP GraphQL: 1.3.8
    - WPGraphQL JWT Authentication: 0.4.0
    - WPGraphQL WooCommerce (WooGraphQL): 0.8.1
    - WPGraphql Yoast Seo: 4.2.0
    - Yoast SEO: 16.3
3. on terminal run `gatsby develop`

**Screenshots**
![1-err](https://user-images.githubusercontent.com/44653536/119032785-40a97a80-b9b5-11eb-8993-c08fb5e39b03.png)
![2-err](https://user-images.githubusercontent.com/44653536/119032794-42733e00-b9b5-11eb-8edb-38f65e572ba6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Plugin Versions**
- **WooGraphQL Version:** 0.8.1
- **WPGraphQL Version:** 1.3.8
- **WordPress Version:** 5.7.2
- **WooCommerce Version:** 5.3.0

```
"dependencies": {
    "gatsby": "^3.5.1",
    "gatsby-core-utils": "^2.5.0",
    "gatsby-image": "^3.5.0",
    "gatsby-plugin-manifest": "^3.5.0",
    "gatsby-plugin-offline": "^4.5.1",
    "gatsby-plugin-react-helmet": "^4.5.0",
    "gatsby-plugin-sharp": "^3.5.0",
    "gatsby-source-filesystem": "^3.5.0",
    "gatsby-source-wordpress": "^5.5.1",
    "gatsby-transformer-sharp": "^3.5.0",
    "html-react-parser": "^1.2.6",
    "lodash": "^4.17.21",
    "mitt": "^2.1.0",
    "postcss": "^8.2.15",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "typeface-merriweather": "1.1.13",
    "typeface-montserrat": "1.1.13"
  },
```

How can i fix it?

**Comment by jasonbahl** [comment]
@iqwik do you have any fields in your schema that start with `__`?

WPGraphQL and WooGraphQL don't add any fields that start with `__` but it appears like something is adding it.

**Comment by TylerBarnes** [comment]
@iqwik if you can open this issue on the GatsbyJS repo with a link to a reproduction repo of the issue so we can debug it that would be super helpful https://github.com/gatsbyjs/gatsby/issues/new/choose

I think this issue doesn't belong here so it can be closed 👍

**Comment by Bright0505** [comment]
I have the same problem
It is normal when WooGraphQL is turned off
Is there any solution?

WooGraphQL 0.10.4

**Comment by NegatiV-64** [comment]
Have the same issue, sometimes this message popups in GraphQL IDE

**Comment by Bright0505** [comment]
@NegatiV-64 
I don't have this problem with my IDE, it happens in gatsby develop

**Comment by tsamantanis** [comment]
Hello guys, was this ever fixed? I just activated the plugin and now `gatsby develop` throws the error mentioned.
