### ISSUE TITLE
Not getting PayPal pop up

### ISSUE THREAD

**Issue by jasminetracey** [wp-graphql/wp-graphql-woocommerce#499]
**Describe the bug**
When i select paypal as payment option I do not get the paypal pop up. It just processes the order.

**Expected behavior**
Should get paypal popup

**Plugin Versions**
- **WooGraphQL Version: 0.8.1
- **WPGraphQL Version: 1.3.8
- **WordPress Version: 5.7.2
- **WooCommerce Version: 5.3

**Additional context**

**Comment by kidunot89** [comment]
@jasminetracey No. you should get a `redirectUrl` in the mutation output.
