### ISSUE TITLE
"The \"variation\" product type is not supported by the core WPGraphQL WooCommerce (WooGraphQL) schema."

### ISSUE THREAD

**Issue by Robak08** [wp-graphql/wp-graphql-woocommerce#502]
Hi, when running query for customer downloadableItems like this:
```
 customer {
    downloadableItems {
      nodes {
        accessExpires
        download {
          fileExists
          fileExt
        }
        downloadId
        downloadsRemaining
        url
        product {
          id
        }
      }
    }
  }
```
Whenever there is product connector in query - for corresponding product of Variable Type - server responds with error :
```
 "errors": [
    {
      "message": "The \"variation\" product type is not supported by the core WPGraphQL WooCommerce (WooGraphQL) schema.",
      "extensions": {
        "category": "user"
      },
      "locations": [
        {
          "line": 13,
          "column": 9
        }
      ],
      "path": [
        "customer",
        "downloadableItems",
        "nodes",
        0,
        "product"
      ]
    },
```

**Comment by victormattosvm** [comment]
I had a similar problem with the Order model and it was because the product was removed, so the model couldn't find it. In my case, I've added a "name" field on lineItems to display the order item name. I'm not using "product" or "variation" anymore.

**Comment by marlonjet** [comment]
I'm having the same issue, How can I solve it ?

**Comment by joshghent** [comment]
I also am facing this issue. I have narrowed it down to the `WPC Grouped Product for WooCommerce` plugin.
It brings back the error: `The \"woosg\" product type is not supported by the core WPGraphQL WooCommerce (WooGraphQL) schema.`

Thanks for a fantastic piece of software, hope I can get it working soon :)
