### ISSUE TITLE
new query Related Products

### ISSUE THREAD

**Issue by phidalgot** [wp-graphql/wp-graphql-woocommerce#503]
good night I have the following question
From which query do I get the related products or cross products of a particular product

**Comment by jacobarriola** [comment]
You can query the `related` and `upsell` fields for the `product` type.

Something like this:

```graphql
{
  products {
    nodes {
      name
      related {
        nodes {
          name
        }
      }
      upsell {
        nodes {
          name
        }
      }
    }
  }
}
```

**Comment by phidalgot** [comment]
excellent thank you very much
