### ISSUE TITLE
productCategory products orderBy not working properly 

### ISSUE THREAD

**Issue by bilelmoussa** [wp-graphql/wp-graphql-woocommerce#506]
productCategory products orderBy not working properly [PRICE,  REGULAR_PRICE,  SALE_PRICE,  TOTAL_SALES] return nodes empty array

**Comment by kidunot89** [comment]
@bilelmoussa Is this still an issue in **WooGraphQL v0.10.0**?

**Comment by arielboitas** [comment]
The same thing happens to me in v0.10.0

**Comment by ardiewen** [comment]
@bilelmoussa Not sure if you figured out a work around yet, but using the root query `products` with a category filter seems to work for now. Something like this:

```
query GetProductSummariesByCategory($id: Int!) {
  products(where: { categoryId: $id }) {
    edges {
      node {
        ...ProductSummaryFields
      }
    }
  }
}
```
