### ISSUE TITLE
How to show extraData in WooCommerce backend Order product meta

### ISSUE THREAD

**Issue by bala963** [wp-graphql/wp-graphql-woocommerce#512]
Hi!

Can i show extraData in Woo order backend?

example:

Xyz Order
1. product 
meta: extraData
2. product
meta: extraData

Thanks,

**Comment by ccarrascom** [comment]
Hi! did you get it working?

**Comment by peiris** [comment]
@bala963 Did you get this working? I'm also looking for the solution.
