### ISSUE TITLE
Session token refresh for cart with anonymous user

### ISSUE THREAD

**Issue by sn3h** [wp-graphql/wp-graphql-woocommerce#519]
**Describe the bug**
Hi, on default, when I add first product to cart, I get woocommerce-session (as session) cart, that expires in 72h (set in WP as I found out). When I add or change anything in the cart, I use header 
"woocommerce-session": `Session ${session}`
to stay in the same cart. But after 72 hours from the first product adding, the session is lost and the cart with it. There is no refreshtoken (or I can't find it) and 
customer {sessionToken} 
seems empty too (anonymous session). 
SO, the issue is, if I add something to cart, wait 71.9h and then continue to shop, my cart suddenly dissapears in the middle of the shopping and I see no way to do anything about it expect saving cart to localstorage and recreating it completely if session expires. 

Is there some way to refresh the cart session token? Let's say after each cart update, or at will. 

**To Reproduce**
just add product, then add another and session token returned in the headers is still the same, with same 
PAYLOAD:DATA

{
  ...
  "iat": constant,
  "nbf": constant,
  "exp": constant,
  ...
}

**Expected behavior**
Send new - updated - token on cart change, or return refreshToken

**Plugin Versions**
I think it's irrelevant

**Additional context**
I am using gatsby demo store as inspiration but writing my own logic in urql. Still, I am new to this so please forgive me if my issue is stupid for some reason ;) 
I have no idea if this problem stays after user login, I am not that far yet

**Comment by nonlinearcom** [comment]
Hi, I'm facing the same issue, is there any workaround for this?
