### ISSUE TITLE
Add new orderby enum to existing enum values

### ISSUE THREAD

**Issue by akshaykatale99** [wp-graphql/wp-graphql-woocommerce#520]
How can we add new orderby enum to existing enum values to ProductsOrderByEnum. i have tried graphql_enum_values filter but no luck.

**Comment by kidunot89** [comment]
@akshaykatale99 Currently, little to no Enumeration fields have filters. I welcome PRs to fix this.

_P.S. Please note #513 you meta custom may have an issue paginating in reverse until this bug is resolved._

**Comment by samora17** [comment]
+1, same doubt.
