### ISSUE TITLE
Getting a critical error when I try to install wp graphql and wp graphql woocommerce 

### ISSUE THREAD

**Issue by nisfikas** [wp-graphql/wp-graphql-woocommerce#525]

**Comment by nisfikas** [comment]
<img width="1110" alt="Στιγμιότυπο 2021-07-07, 4 21 12 μμ" src="https://user-images.githubusercontent.com/85784235/124766208-5fe97080-df3f-11eb-82e8-1e102ce3d88f.png">

**Comment by kidunot89** [comment]
@nisfikas Are you installing thru `composer`?

**Comment by nisfikas** [comment]
I tried with v0.10.2 but I am still having the same issue.
I am installing the plugin via Wordpress --> Plugins --> Add New

**Comment by menachemkorf** [comment]
@nisfikas Try running `composer install` from within the plugin directory.

**Comment by 2xSamurai** [comment]
+1 I'm having the same issue, tried uploading the plugin. Got this error. It works with v0.10.1.

**Comment by Petermhen** [comment]
Getting this error on trying to install v0.10.2 after uploading plugin via ftp & clicking "activate" in wordpress admin panel.

```
fatal error: Uncaught Error: Class 'WPGraphQL\WooCommerce\WooCommerce_Filters' not found in /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-content/plugins/wp-graphql-woocommerce-master-10.2/includes/class-wp-graphql-woocommerce.php:200 Stack trace: #0 /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-content/plugins/wp-graphql-woocommerce-master-10.2/includes/class-wp-graphql-woocommerce.php(35): WP_GraphQL_WooCommerce->setup() #1 /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-content/plugins/wp-graphql-woocommerce-master-10.2/wp-graphql-woocommerce.php(76): WP_GraphQL_WooCommerce::instance() #2 /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-includes/class-wp-hook.php(287): woographql_init(Object(WPGraphQL)) #3 /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /home/webdmgyr/cms.productionsta in /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-content/plugins/wp-graphql-woocommerce-master-10.2/includes/class-wp-graphql-woocommerce.php on line 200
There has been a critical error on this website. Please check your site admin email inbox for instructions.
```

Wordpress version 5.6.4
WP GraphQL wordpress plugin: Version 1.5.2
WP Gatsby wordpress plugin: Version 1.0.11
WooCommerce wordpress plugin: Version 4.8.0

**Comment by Petermhen** [comment]
> Getting this error on trying to install v0.10.2 after uploading plugin via ftp & clicking "activate" in wordpress admin panel.
> 
> ```
> fatal error: Uncaught Error: Class 'WPGraphQL\WooCommerce\WooCommerce_Filters' not found in 
> 
> /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-content/plugins/wp-graphql-woocommerce-master-10.2/includes/class-wp-graphql-woocommerce.php:200 Stack trace: #0 
> 
> /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-content/plugins/wp-graphql-woocommerce-master-10.2/includes/class-wp-graphql-woocommerce.php(35): WP_GraphQL_WooCommerce->setup() #1 
> 
> /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-content/plugins/wp-graphql-woocommerce-master-10.2/wp-graphql-woocommerce.php(76): WP_GraphQL_WooCommerce::instance() #2 
> 
> /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-includes/class-wp-hook.php(287): woographql_init(Object(WPGraphQL)) #3 
> 
> /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters('', Array) #4 /home/webdmgyr/cms.productionsta in 
> 
> /home/webdmgyr/cms.productionstaging.sleepsolutions.webdev.press.webdev.press/wp-content/plugins/wp-graphql-woocommerce-master-10.2/includes/class-wp-graphql-woocommerce.php on line 200
> 
> There has been a critical error on this website. Please check your site admin email inbox for instructions.
> ```
> 
> Wordpress version 5.6.4
> WP GraphQL wordpress plugin: Version 1.5.2
> WP Gatsby wordpress plugin: Version 1.0.11
> WooCommerce wordpress plugin: Version 4.8.0

Issue was solved by downloading v0.10.2 from the release page & uploading that folder via ftp then activating plugin in wordpress admin:
https://github.com/wp-graphql/wp-graphql-woocommerce/releases/tag/v0.10.2

I previously cloned the repository's master branch and uploaded that folder via ftp then clicked "activate" on the plugin in Wordpress admin, which resulted in the error.

**Comment by brianpereradap** [comment]
Is there any resolution for this? 
When the plugin is installed (v0.10.2) via composer I receive the critical error. But it works if I directly download the plugin and install it via Wordpress admin.

**Comment by commandcenterio** [comment]
i get:
`Installation failed: ={"success":true,"data":{"install":"plugin","slug":"wp-graphql","pluginName":"WPGraphQL","debug":["Downloading installation package from https:\/\/downloads.wordpress.org\/plugin\/wp-graphql.1.6.6.zip&#8230;","The authenticity of wp-graphql.1.6.6.zip could not be verified as no signature was found.","Unpacking the package&#8230;","Installing the plugin&#8230;","Plugin installed successfully."],"activateUrl":"https:\/\/staging-cmdcntrio.kinsta.cloud\/wp-admin\/plugins.php?_wpnonce=7d068308c8&action=activate&plugin=wp-graphql\/wp-graphql.php"}}
`
when installed on my staging environment on kinsta. i can access the plugin but no schemas show as well as receiving the following error when querying from the ide or querying from a local gatsby instance:
`Unexpected token = in JSON at position 0`

**Comment by babita-web** [comment]
composer install works...

**Comment by bigupjeff** [comment]
Yup, composer install is required. Missed it while hacking away.

It'd be nice to see this plugin wrapped in a bow-tie and available on the WP plugin library next to Woo and WP GraphQL.

**Comment by carlschlyter** [comment]
@kidunot89 Hi, could you tell me exactly step by step how I install and activate this plugin with composer in my project?

**Comment by CesarBenavides777** [comment]
@carlschlyter navigate to the `plugins/wp-graphql-woocommerce-develop` and run `composer install`

**Comment by pairviewwebmaster** [comment]
How do I solve this issue I keep getting that error

**Comment by CesarBenavides777** [comment]
> How do I solve this issue I keep getting that error

navigate to the `plugins/wp-graphql-woocommerce-develop` directory and run `composer install`

**Comment by CesarBenavides777** [comment]
@pairviewwebmaster 
> We are using https://pantheon.io/ for are wordpress application so don't really have access to composer through the Wordpress dashboard

I would download the plugin, run the same command locally, have it generate those files, then zip it up and re upload.

**Comment by pairviewwebmaster** [comment]
That makes sense will try that and update you

**Comment by pairviewwebmaster** [comment]
After running `compose install` on a local version of the [plugin](https://github.com/wp-graphql/wp-graphql-woocommerce)  and trying to install the zip on Wordpress i keep getting 
`
The uploaded file exceeds the upload_max_filesize directive in php.ini.
`

**Comment by pairviewwebmaster** [comment]
Not sure it is cause the file is 2.98 MB and my max file upload size is 1GB
