### ISSUE TITLE
LineItems product details is null inside Orders and Order queries

### ISSUE THREAD

**Issue by 2xSamurai** [wp-graphql/wp-graphql-woocommerce#528]
**Describe the bug**
I am trying to get the orders. But the product data inside lineItems is null. 

Following is a single node from lineItems

`"node": {
                  "databaseId": null,
                  "total": "798",
                  "totalTax": null,
                  "variationId": null,
                  "subtotalTax": null,
                  "subtotal": "798",
                  "quantity": 2,
                  "productId": null
                }`

**To Reproduce**

I am using the graphiQL IDE. Run the following query. 

`query MyQuery {
  orders {
    nodes {
      lineItems {
        nodes {
          product {
            id
          }
          databaseId
        }
      }
    }
  }
}
`

Query response. There aren't any errors. But the data is null for the fields related to product. databaseId, product, productId etc.

`{
  "data": {
    "orders": {
      "nodes": [
        {
          "lineItems": {
            "edges": [
              {
                "node": {
                  "databaseId": null,
                  "total": "798",
                  "totalTax": null,
                  "variationId": null,
                  "subtotalTax": null,
                  "subtotal": "798",
                  "quantity": 2,
                  "productId": null
                }
              },
              {
                "node": {
                  "databaseId": null,
                  "total": "2",
                  "totalTax": null,
                  "variationId": null,
                  "subtotalTax": null,
                  "subtotal": "2",
                  "quantity": 1,
                  "productId": null
                }
              },
              {
                "node": {
                  "databaseId": null,
                  "total": "18",
                  "totalTax": null,
                  "variationId": null,
                  "subtotalTax": null,
                  "subtotal": "18",
                  "quantity": 1,
                  "productId": null
                }
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {
    "debug": []
  }
}`

**Expected behavior**
To return line items(product) data of all the orders and order by ID.

**Screenshots**
![image](https://user-images.githubusercontent.com/8579190/126270691-23e1117e-4f0c-4ade-8f11-c9edc661a9d4.png)

**Desktop (please complete the following information):**
 - OS: MacOS BigSur 11.4
 - Browser Chrome Version 91.0.4472.164 (Official Build) (arm64)

**Plugin Versions**
- **WooGraphQL Version:** 0.10.0 
- **WPGraphQL Version:** 1.5.3
- **WordPress Version:** 5.7.2
- **WooCommerce Version:** 5.5.1

**Additional context**
Any help is much appreciated. Thank you.

**Comment by victors1681** [comment]
I got the same issue after upgrade WPGraphQL to  `1.5.5 ` works fine on 1.4.0

**Comment by topheroes** [comment]
Same issue.

**Comment by flocosnier** [comment]
Same issue
