### ISSUE TITLE
Cart : can't get the simple attributes of a variable product

### ISSUE THREAD

**Issue by flocosnier** [wp-graphql/wp-graphql-woocommerce#530]
I have a product with :
- 3 variations (depending on the "type" attribute)
- 2 simple attributes (color and size)

I can add it to cart with this input and the price is correct when I then retrieve the items :
`input: {clientMutationId: "54545", productId: 127, quantity: 1, variationId: 129, variation: [{attributeName: "couleur", attributeValue: "Rouge"}, {attributeName: "taille", attributeValue: "M"}]}`

However, when I want to get the cart, I can't get the simple attributes :
- The recently added "simpleAttributes" field on product object only gives me the attribute associated with the variation, not the other ones
- In the "variation" object, I only get the variation attribute

![Capture](https://user-images.githubusercontent.com/64930771/126866762-1516c823-9e8d-4f7d-9699-b9dabb16675b.PNG)

Could we have a "simpleAttributes" field on the "variation" object ?

**Comment by kidunot89** [comment]
@flocosnier Have you tried the `attributes` field on the SimpleProduct type.
```graphql
query {
  cart {
    contents {
      nodes {
        key
        product {
          node {
            attributes  {
              name
              label
            }
          }
        }
      }
    }
  }
}
```

**Comment by flocosnier** [comment]
It's a variable product so this query doesn't return anything.

I've found a way though. Basically, I had three attributes but only one to be used for the variations. Creating only the necessary variations while checking the "Used for variations" checkbox for the others, I managed to get it to work.

I don't know if it's very clear, I'll come back and take screenshots if needed !

**Comment by kidunot89** [comment]
@flocosnier The issue is that you haven't completely configure you variations. After checking all the attributes you want to use as variation attributes, you have to generate the variations. You can this in the `Variations` section, you should find a button that does just that.
