### ISSUE TITLE
This plugin failed to load properly 

### ISSUE THREAD

**Issue by globicintbh** [wp-graphql/wp-graphql-woocommerce#532]
Hi guys 

I have a problem when activate Woographql plugin , the plugin paused and get this message 

An error of type E_ERROR was caused in line 200 of the file /******//wp-content/plugins/wp-graphql-woocommerce-develop/includes/class-wp-graphql-woocommerce.php. Error message: Uncaught Error: Class 'WPGraphQL\WooCommerce\WooCommerce_Filters' not found 

any help please ???

**Comment by 2xSamurai** [comment]
@globicintbh try downloading the plugin from https://github.com/wp-graphql/wp-graphql-woocommerce/tree/v0.10.2

or downgrade to 0.10.1

I also had the same issue

**Comment by johnforte** [comment]
If you clone the repo, you need to run composer install to generate the autoloader.

**Comment by ramyareye** [comment]
@jasonbahl is there any plan to include vendor? cause it's not really usual to upload a plugin and then running `composer install`

**Comment by kidunot89** [comment]
@ramyareye @johnforte @2xSamurai @globicintbh Unless you are using a WP Bedrock setup or something similar with **johnpbloch/wordpress** through composer. I recommend downloading the most stable release [here](https://github.com/wp-graphql/wp-graphql-woocommerce/releases).

**Comment by samora17** [comment]
Hi guys,
I'm trying to play with this plugin + React / NextJS, I would like to implement it in a project in production, but Wordpress presents an error at the moment of activating this plugin,

"There has been a critical error on this website. Please check your site administrator's email inbox for instructions.
Learn more about WordPress diagnostics."

**Comment by ramyareye** [comment]
@samora17 it's because of `vendor` folder, you can download the latest version [here](https://github.com/wp-graphql/wp-graphql-woocommerce/releases/tag/v0.10.3)
I'm gonna send a pr to update Installation part
