### ISSUE TITLE
Incompatible with WPGraphQL 1.6.1

### ISSUE THREAD

**Issue by jenewland1999** [wp-graphql/wp-graphql-woocommerce#533]
**Describe the bug**
The schema fails to load in the GraphiQL view inside the WP admin dashboard when the current version of WPGraphQL WooCommerce is used with WPGraphQL v1.6.0 released.

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a fresh install of WordPress with WooCommerce, WPGraphQL 1.6.1 and WPGraphQL Woo Commerce
2. Visit the GraphiQL editor within the WP admin dashboard
3. See that the schema isn't loading on the left-hand side.

**Expected behaviour**
The schema should load (along with the documentation too).

**Screenshots**
![image](https://user-images.githubusercontent.com/34895363/127714834-39ec019f-a95e-406f-8928-3390f7d72077.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 21H1 (OS Build 19043.1081) 64-bit
 - Browser: Chrome
 - Version: 92.0.4515.107 (Official Build) (64-bit)

**Plugin Versions**
- **WooGraphQL Version:** 0.10.2
- **WPGraphQL Version:** 1.6.1
- **WordPress Version:** 5.8
- **WooCommerce Version:** 5.5.2

**Comment by TheAggressive** [comment]
Same issue here

**Comment by foadms** [comment]
I have the same problem.

**Comment by foadms** [comment]
If anybody found a solution please share. Thank you.

**Comment by mohsenkhanpour** [comment]
Hey everyone, 
this PR fixed the problem for me!
https://github.com/wp-graphql/wp-graphql-woocommerce/pull/534

You can clone
https://github.com/jasonbahl/wp-graphql-woocommerce/tree/feature/wp-graphql-v1.6-compatibility
then do `composer install` and copy to plugins folder.

**Comment by LeeBuckle** [comment]
Looks like things are underway to fix this issue, just popping these here in case it helps at all.

When this plugin is active, this error comes up in the console:
![Screenshot 2021-08-05 at 23 15 04](https://user-images.githubusercontent.com/80564456/128430843-0df3d5b7-7770-4bcd-93d1-edc783587919.png)

It seems to cause a problem with Advanced Custom Fields too, as this error appears in the ACF Field Group edit page, but works fine when WPGraphQL Woo is deactivated:
![Screenshot 2021-08-05 at 23 26 13](https://user-images.githubusercontent.com/80564456/128430984-3cf9ec06-326f-4701-b33e-7e771f4267bb.png)
