### ISSUE TITLE
Attributes IDs for variations return 0

### ISSUE THREAD

**Issue by Robak08** [wp-graphql/wp-graphql-woocommerce#540]
**Describe the bug**
Returned attributeId of variations attributes property always returns 0, no matter the attribute itself. Introduced with v1.6.0 of wp-graphql.

**To Reproduce**
1. Create product with more than one variation
2. Assign different attributes to variants
3. Query the products for variations like: 
```
... on VariableProduct {
	variations {
		nodes {
			attributes {
				nodes {
					attributeId
				}
			}
		}
	}
}
```
4. All attributeIds returns as 0

**Expected behavior**
Distinct Id for each attribute

**Screenshots**
![Screenshot 2021-08-14 233535](https://user-images.githubusercontent.com/17516948/129460656-a6efdf11-1d47-4b68-9e39-dd4bb20a162f.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser MS Edge
 - Version 92

**Plugin Versions**
- **WooGraphQL Version: 0.10.3
- **WPGraphQL Version: 1.6.3
- **WordPress Version: 5.8
- **WooCommerce Version: 5.5.2

**Comment by Robak08** [comment]
UPDATE: Weirdly enough, after updating real-media-library to newest version  4.14.2 from 4.13.x attributeId started to show properly. Although I'm totally not sure if it's even connected. So I'll leave issue as it is, but might be hard to reproduce it.

**Comment by kidunot89** [comment]
@Robak08 Not all product attributes are global attributes. Some are local to the product itself, this attributes don't have `attributeId` only an `id` for client-side caching.
Global product attributes are just taxonomies and there possible values are terms. The Term IDs of these values are what `attributeId` are.
