### ISSUE TITLE
Addtocart variation mutation help

### ISSUE THREAD

**Issue by TheAggressive** [wp-graphql/wp-graphql-woocommerce#555]
So I've been playing with how to add to cart a product with a variation (example: size: large, color: black) for a couple days but can't seem to figure out how to go about it. 

Can someone post an example so I can see where I'm going wrong with the mutation? Is there any tricks?

Thank you!

**Comment by jacobarriola** [comment]
Hey there!

No tricks that I'm aware of. I'm curious as to what your mutation looks like.

Here's a simple example of adding a variation to the cart:

```graphql
mutation ADD_TO_CART {
    addToCart(input: {productId: 123 quantity: 1}) {
      cart {
        total
      }
    }
}
```

Hope this helps!

**Comment by TheAggressive** [comment]
@jacobarriola thanks for the response. My mutation currently looks similar to what you had posted.

But I'm lost about say a shirt product. It comes in different colors and sizes. What does the mutation look like to pass in the size and color that the user would select? Kinda lost about how to structure the mutation in that regard.

**Comment by jacobarriola** [comment]
@TheAggressive ah!

So if you're dealing with a variable product, you simply pass in the variation id of the product in which you want to add.

For instance, let's assume some conditions:

1. you have a variable product called `shirt`, with a product ID of `1`
2. there's one attribute for the shirt called `size`. 
3. there are three sizes for `shirt`: `small`, `medium` and `large`

Therefore, you'll have 3 variations, each with their own product ids:
1. variation a: small shirt => productId 2
2. variation b: medium shirt => productId 3
3. variation c: large shirt => productId 4

You'll be responsible for writing the logic on your application (web or native) to capture the correct ID given what attributes a user chooses. Once you have the variation id, then you can send along the `addToCart` mutation along with the variation id of the product.

**Comment by TheAggressive** [comment]
@jacobarriola Thank you for the help!! Appreciate it!

So if I'm understanding correctly. So a mutation would like this

```graphql
mutation ADD_TO_CART($input: AddToCartInput!) {
  addToCart(input: $input) {
    cart {
      subtotal
      total
      shippingTotal
      contents {
        itemCount
        edges {
          node {
            extraData {
              key
              value
            }
          }
        }
        nodes {
          variation {
            attributes {
              attributeId
              name
              value
            }
          }
          product {
            node {
              name
              sku
              databaseId
              ... on SimpleProduct {
                id
                name
                price
              }
              ... on GroupProduct {
                id
                name
                price
              }
              ... on VariableProduct {
                id
                name
                price
              }
            }
          }
        }
      }
    }
  }
}
```

```graphql
{
  "input": {
    "productId": 31,
    "quantity": 1,
    "clientMutationId": "clientid344233230kkd0e043fde",
    "variation": [
    	{"attributeName": "size", "attributeValue": "Large" }
    ]
  }
}
```
With the Variations in Woocommerce that look like this

![Screenshot 2021-09-20 115332](https://user-images.githubusercontent.com/10968229/134058488-8ecd6123-e392-4a5b-8514-a93b8358bb8d.jpg)

Does that look right?

**Comment by jacobarriola** [comment]
@TheAggressive You don't need to add the `variation` array in the `input`. `productId` and `quantity` should be enough.

**Comment by TheAggressive** [comment]
@jacobarriola wouldn't you need the variation array to specify the size since it's default is any (small, medium, large, etc)?

**Comment by jacobarriola** [comment]
I'm not sure about the any values. We generally create unique variations for all the attribute combinations. That way we have unique variation ids for everything.

**Comment by TheAggressive** [comment]
@jacobarriola understood, if each variation is specified then only the product id of the variant is needed. If it's not specified then additional info will need passed. 

Enjoyed your video btw on headless that's linked in your post about headless woocommerce. A question about checkout. Does the checkout happen on the front end when you're using stripe API or does the checkout happen on backed when a new order is created? 

Thanks again for your help! Headless is something new to me but a fun challenge.

**Comment by jacobarriola** [comment]
> Does the checkout happen on the front end when you're using stripe API or does the checkout happen on backed when a new order is created?

There's a `checkout` mutation available in the schema. In it, you send along the `_stripe_source_id` that you get back from the Stripe JS client and set the `paymentMethod` to `stripe`.

WooGraphQL will use that `paymentMethod` to actually run the payment process. Under the hood WooCommerce saves this source as order meta, which is later used by the Stripe WordPress plugin to actually handle the payment.

Here's what that mutation would look like: https://jacobarriola.com/post/headless-woocommerce-stripe-checkout-graphql#step-4-send-graphql-mutation-to-woocommerce

I also wrote a post about the two options for checkout: https://jacobarriola.com/post/headless-woocommerce-checkout-options

Have fun!
