### ISSUE TITLE
Assign orders to customers who are already authenticated

### ISSUE THREAD

**Issue by jacobdubail** [wp-graphql/wp-graphql-woocommerce#559]
**Is your feature request related to a problem? Please describe.**
I would like to assign orders to customers who have already logged in (cookie authentication). I see in the checkout mutation I can send a username/password, but by the time the customer hits checkout, I no longer have access to the credentials. I am including credentials headers in each request.

**Describe the solution you'd like**
I would appreciate if the plugin could automatically detect a logged in session and assign a new order accordingly. When I view new orders currently, I see the correct email address and billing details, but the Customer dropdown says "guest".

**Describe alternatives you've considered**
I've considered using the WooCommerce rest api client  @woocommerce/woocommerce-rest-api, but that's extra baggage I'd like to avoid.

Thank you!

**Comment by jacobdubail** [comment]
Looks like I may be able to run an `updateOrder` mutation and set the `customerId` that way. It would be convenient if `customerId` was an input field for the `checkout` mutation too, but I can work around it for now.

**Comment by kidunot89** [comment]
@jacobdubail See first asterisk [here](https://github.com/wp-graphql/wp-graphql-woocommerce#what-can-you-do-with-this-extension). If you already know about session token JWT, other than that you can just disable the custom session handler by passing `define( 'NO_QL_SESSION_HANDLER`, true );` somewhere, this will make WooGraphQL use the default session handler that using cookies.
