### ISSUE TITLE
updateOrder not update order status

### ISSUE THREAD

**Issue by brandonqcode** [wp-graphql/wp-graphql-woocommerce#562]
**Describe the bug**
The updateOrder mutation is not updating the order status sending in UpdateOrderInput **status**, just update sending **isPaid** true.

**To Reproduce**
1. Mutation to run.
`mutation UpdateOrder($input: UpdateOrderInput!) {
  updateOrder(input: $input) {
    order {
      status
    }
  }
}`

2. Input to send.
`{
  "input": {
    "orderId": 84808,
    "status": "FAILED"
  }
}`

**Expected behavior**
I expect that the order status update to the **status** enum sended, in this case is "FAILED" but it returns me the actual order status.

**Screenshots**
![image](https://user-images.githubusercontent.com/87135018/135929496-9ac6281a-15f8-4cf2-9ff1-8547fcf61525.png)
![image](https://user-images.githubusercontent.com/87135018/135929537-3a5ab52e-4df4-4c87-ace8-ccfcdc642628.png)
![image](https://user-images.githubusercontent.com/87135018/135929553-fd78c13a-3a3e-4db0-8d35-be400cea19c8.png)

**Plugin Versions**
- **WooGraphQL Version:** 0.10.2
- **WPGraphQL Version:** 1.1.8
- **WordPress Version:** 5.6.1
- **WooCommerce Version:** 5.0.0

**Comment by mrstevedev** [comment]
I am having the same issue.

A mutation sending an input "status":"COMPLETED" does not update the order status. The return field for status remains unchanged.
