### ISSUE TITLE
Persistent customer cart

### ISSUE THREAD

**Issue by Kestutis** [wp-graphql/wp-graphql-woocommerce#577]
**Is your feature request related to a problem? Please describe.**
I have a problem when customer leaves cart without checkout and comes back later. 

**Describe the solution you'd like**
I'm looking a way to persist customer cart. When customer login, add some products to cart and logout, I need to retrieve same cart content next time customer logins(from same or other machine). 

**Describe alternatives you've considered**
Right now each time customer logins new `sessionToken` is generated. I've tried to just copy/paste `sessionToken` from previous session and functionality I'm looking works. If this can not be supported by `wp-graphql-woocommerce` it-self, probably I can save `sessionToken` as user meta data and use instead of one freshly generated. Or this would be a bad solution?

**Comment by kidunot89** [comment]
@Kestutis The recommend practice is to store the **sessionToken** client-side and use that token indefinitely. If you wish to start a new session, reauthenticate the user with a mutation like `login` and retrieve a **sessionToken** token.

**Comment by Kestutis** [comment]
If someone interested I solved my question following way:
```php
add_filter('graphql_customer_session_token', 'my_graphql_customer_session_token', 10, 1);
function my_graphql_customer_session_token($sessionToken) {
    $userId = get_current_user_id();
    $userMetaDataKey = '_my_session_token';
    if ($userId > 0) {
        $userSessionToken = get_user_meta($userId, $userMetaDataKey , true);
        if ($userSessionToken) {
            return $userSessionToken;
        }
        update_user_meta($userId, $userMetaDataKey, $sessionToken);
    }
    return $sessionToken;
}
```
