### ISSUE TITLE
Query Country / Regions

### ISSUE THREAD

**Issue by TheAggressive** [wp-graphql/wp-graphql-woocommerce#581]
Making a checkout form and It would be nice to be able to query the countries available to ship to so then you could map the entries and make a select form field and populate it with the country name and it's value recognized by woo (examples below)

**Name**: "United States (US)", **Value**: "US"
**Name**: "United Kingdom (UK)", **Value**: "GB"
**Name**: "Swaziland", **Value**: "SZ"
...and so on for the other countries/regions

If it's already there somewhere, I couldn't locate it. Currently have to hard code every entry.

**Comment by RobinGiel** [comment]
@TheAggressive Normally you can set the countries that you allow to ship in your woo-commerce settings in Wordpress. and for the query I use something like this: 

```

import { gql } from "@apollo/client";

/**
 * GraphQL countries query.
 */
const GET_COUNTRIES = gql`query GET_COUNTRIES{
  wooCountries {
    billingCountries {
      countryCode
      countryName
    }
    shippingCountries {
      countryCode
      countryName
    }
  }
}`;

export default GET_COUNTRIES;

```

**Comment by TheAggressive** [comment]
Thanks @RobinGiel 

I don't see `wooCountries` by default on the IDE options. Are you extending WPGraphQL to include those?

I think it would be nice to have that info by default without having to extend the GraphQL but I did the same to achieve this.

**Comment by RobinGiel** [comment]
@TheAggressive  indeed, I'm using this plugin to achieve that -> https://github.com/imranhsayed/headless-cms
