### ISSUE TITLE
No strings to enums conversion for orderby object in whereArg when quering products from client-side.

### ISSUE THREAD

**Issue by Robak08** [wp-graphql/wp-graphql-woocommerce#582]
**Describe the bug**
Querying products like so: 
```
query productFilter(
		$first: Int
		$after: String
		$where: RootQueryToProductConnectionWhereArgs
	) {
		products(first: $first, after: $after, where: $where) {
			${productFields}
		}
	}
```
where $where object contains "orderby" throws error ex.:
```
"[GraphQL] Variable "$where" got invalid value {"orderby":{"field":"PRICE","order":"ASC"}}; Expected type ProductsOrderbyInput to be an object at value.orderby.field.
[GraphQL] Variable "$where" got invalid value {"orderby":{"field":"PRICE","order":"ASC"}}; Expected type ProductsOrderbyInput to be an object at value.orderby.order."
```
due to not converted values of orderby object itself. This happens also for posts queries containing ordeby - so I'm not sure if it's sanitation problem here or at main wp-graphql. 

Other whereArgs like taxonomyFilter without orderby get their string values converted to enums properly. 

**To Reproduce**
1. query products with where variable containing  strings
```
where: { orderby: { field: "DATE", order: "ASC" } };
```
```
query productFilter(
		$first: Int
		$after: String
		$where: RootQueryToProductConnectionWhereArgs
	) {
		products(first: $first, after: $after, where: $where) {
			${productFields}
		}
	}
```
2.  See thrown error by GraphQL

**Expected behavior**
String values from client to be converted to enums.

**Screenshots**
![Screenshot 2021-11-08 103247](https://user-images.githubusercontent.com/17516948/140717810-3ed21647-7524-44b4-8d4d-aa88d7ce8ec5.jpg)

Desktop (please complete the following information):
OS: Windows 11
Browser MS Edge
Version 95
Plugin Versions
**WooGraphQL Version: 0.10.6
**WPGraphQL Version: 1.6.7
**WordPress Version: 5.8.1
**WooCommerce Version: 5.8

**Comment by jasonbahl** [comment]
I believe orderby wants an array, like: `where: { orderby: [{ field: "DATE", order: "ASC" }] }`

Can you try that and report back?

**Comment by Robak08** [comment]
Yep, that did the trick. And it's even in the docs schema. Though IDE got me on wrong track here, since there is no array there. Thank You gonna close it.

![image](https://user-images.githubusercontent.com/17516948/140976164-96eafdef-7dc3-4a11-a59d-509682a8099a.png)
