### ISSUE TITLE
Ciritcal bug - Product types

### ISSUE THREAD

**Issue by stevezehngut** [wp-graphql/wp-graphql-woocommerce#583]
**Describe the bug**
I think I have discovered a bug with WooGraphQL (v0.10.3+). It looks like graphQL is not recognizing product types and throwing errors like "This product of ID x is not a xyz product”.

**To Reproduce**
1. Create a fresh install of WordPress.
2. Install and activate WooCommerce.
3. Create a sample simple product.
3. Install and activate the latest wp-graphql and wp-graphql-woocommerce plugins.
4. Go to the GraphiQL IDE.
5. Create a query that gets a simpleProduct. Example:

query MyQuery {
  simpleProduct(id: "12", idType: DATABASE_ID) {
    id
    name
  }
}

6. This will display an error message like "message": "This product of ID 12 is not a SimpleProduct product".

**Expected behavior**
The result should be successful.
<img width="1462" alt="Screen Shot 2021-12-02 at 10 57 22 AM" src="https://user-images.githubusercontent.com/4950846/144485541-746d3c6b-2b76-4e01-ac9b-6b95b4d53f5f.png">

**Screenshots**
Attached.

**Desktop (please complete the following information):**
 - Device: MacBook Pro (16")
 - OS: 12.0.1
 - Browser: Firefox
 - Version: 94.0.2

**Plugin Versions**
- **WooGraphQL Version: 0.10.6
- **WPGraphQL Version: 1.6.7
- **WordPress Version: 5.8.2
- **WooCommerce Version: 5.9.0

**Additional context**
I will create a pull request for this.

**Comment by kidunot89** [comment]
@stevezehngut Just want to confirm that this was only effecting the individual product type queries like `simpleProduct`, `variableProduct`, ...etc?
