### ISSUE TITLE
Product Attributes: some "RootQuery to TermType" connections not on schema

### ISSUE THREAD

**Issue by j-miguel** [wp-graphql/wp-graphql-woocommerce#587]
For the colors attribute I get the `paColors` type as well as the `allPaColors`  `RootQueryToPaColorsConnection`.

But for the sizes attribute I only get the `paSizes` type but there is no `allPaSizes` connection.

Context:

I'm currently trying to get a list of all options by product attribute and apply a filter by multiple attribute options.

Plugin Versions
- WooGraphQL Version: 0.10.6
- WPGraphQL Version: 1.6.10
- WooCommerce Version: 5.8.0

**Comment by kidunot89** [comment]
@j-miguel Not sure where the `allPaColors` is coming from, but it's not probably not **WooGraphQL**

**Comment by j-miguel** [comment]
I was experiencing some strange behaviors with wp-graphql but after reinstalling it and related plugins now I can find the other Root connections (under `paSizes` for example) as well.

The `allPaColors` is still there and I'm also not sure where it's coming from but all is well now.
Thanks for your attention
