### ISSUE TITLE
Updating $_POST object with checkout mutation

### ISSUE THREAD

**Issue by Robak08** [wp-graphql/wp-graphql-woocommerce#590]
Hi, 
I was wondering how to perfom updating $_POST object with custom field from CheckoutInput (either metaData or custom registered). I'm thinking this should be done somewhere in 'woocommerce_checkout_process' action. Thing is that one of third party shipping plugins for Woocommerce is validating certain shipping method by checking if $_POST has exact field value.

Any help would be appreciated. 

PS. I think I can get around that and just assign it to metaData and using 'local pickup' shipping method - but that would mean there's no validation on that field from plugin.

**Comment by kidunot89** [comment]
@Robak08 It's not possible with WooGraphQL or good practice to alter the $_POST server-side, but this is a similar issue I've run into when trying to adding the `checkout` mutation and support for payment gateways. It's common practice in WooCommerce for third-party plugin to look for custom meta in $_POST during checkout. To get around you typical pass the meta through filters from the mutation resolver, but that's not always possible. In that case you would be force to rewrite the inaccessible logic in filters for the `checkout` mutation.

**Comment by Robak08** [comment]
@kidunot89 Thx for answer, this is exacly what I ended up doing.
