### ISSUE TITLE
Under product category "filter product not working"

### ISSUE THREAD

**Issue by rizveejack** [wp-graphql/wp-graphql-woocommerce#594]
I want to filter SIMPLE products on a category but the filter not working..

query PRODUCT_BY_CATEGORY($id: ID!, $after: String = "", $first: Int = 12) {
  productCategory(id: $id, idType: SLUG) {
    id
    name
    slug
    products(after: $after, first: $first, where: {type: SIMPLE}) {
      edges {
        node {
          id
          type
          productId: databaseId
          averageRating
          slug
          image {
            id
            uri
            title
            sourceUrl
          }
          name
          ... on SimpleProduct {
            price
            regularPrice
            id
          }
        }
      }
      pageInfo {
        hasNextPage
        endCursor
      }
    }
  }
}

**Comment by kidunot89** [comment]
@rizveejack Is this still an issue in `v0.14.1`

**Comment by kidunot89** [comment]
This was resolved in v0.18.3
