### ISSUE TITLE
Query with simpleProduct not the same as product

### ISSUE THREAD

**Issue by Bowriverstudio** [wp-graphql/wp-graphql-woocommerce#607]
**Describe the bug**
Hello all I'm running this query and expecting the results to be the same - but am not getting the result as expect:
```graphql
query MyQuery {
  product(id: "t-shirt-with-logo", idType: SLUG) {
    id
    type
    name
    slug
  }
  simpleProduct(idType: SLUG, id: "t-shirt-with-logo") {
    id
  }
}
```
Results in:
```json
"data": {
    "product": {
      "id": "cHJvZHVjdDo0NDM=",
      "type": "SIMPLE",
      "name": "T-Shirt with Logo",
      "slug": "t-shirt-with-logo"
    },
    "simpleProduct": null
  },
```
I expected the simpleProduct to have data.  The same results happen with other single products, and using any of the idType.  What am I doing wrong here?

**To Reproduce**
Import the sample woocommerce data and run the above query

**Plugin Versions**
- **WooGraphQL Version:**0.10.4
- **WPGraphQL Version:**1.6.12
- **WordPress Version:5.9
- **WooCommerce Version:6.2

**Comment by kidunot89** [comment]
@Bowriverstudio Can you confirm this is still an issue. I'm not able to recreate your issue.
