### ISSUE TITLE
Product Add-Ons support on wp-graphql-woocommerce 

### ISSUE THREAD

**Issue by brianpereradap** [wp-graphql/wp-graphql-woocommerce#617]
We require the ability to add product addons for woocommerce products. We are using the following plugin to enable the product addon feature
https://woocommerce.com/products/product-add-ons/

After Setting up the plugin, we noticed that we are unable to do the following via wp graphql
1. Query the product addons using a given product ID
2. Add the product addons to the cart along with the product
3. Cart query to retrieve the product addon information (with price)
4. Totals re-calculation based on configured values on the addon

What I have achieved so far:
* Added a new graphql type which helps to query the configured product addons by passing a product id
* I have still not been able to achieve 2,3,4 points mentioned above 

If someone has come up with an alternative approach to achieve to handle product addons, please share your work.

**Comment by kidunot89** [comment]
@brianpereradap You're next steps would be 

2. Add the needed fields to the  **AddToCartInput** type. Then use filters within the `addToCart` resolver to process them.
3.Add needed query fields to **CartItem** type.
4. You shouldn't need to worry about total re-calculation if the add-ons are being added to the cart/session data the way the plugin expects.

You may need to write a custom update mutation for `add-ons` in the cart but that should be it.
