### ISSUE TITLE
Disable query customer.orders by billing email

### ISSUE THREAD

**Issue by pcraciunoiu** [wp-graphql/wp-graphql-woocommerce#621]
**Describe the bug**

It looks like the `customer.orders` array is queried by billing email. So, if a user changes their email address, their past orders are no longer available. That seems like a bug to me. If this must be kept for some reason that I'm not aware of, would you at least provide a way to disable it?

**To Reproduce**
1. Place an order as a customer. Query for your orders with GraphQL - order shows up.
2. Change your email address
3. Query for the orders again. Order does not show up.

**Expected behavior**

The order should still show up.

**Plugin Versions**

- **WooGraphQL Version:** any up to now, current v0.11 . Code is here: https://github.com/wp-graphql/wp-graphql-woocommerce/blob/6dbdcb5ae8839d84576569c4288350e96acfd4b3/includes/connection/class-orders.php#L116-L122

**Comment by kidunot89** [comment]
@pcraciunoiu This was done to facilitate a means to querying orders for guest who don't have a Customer/User ID to fallback on, but you maybe correct. It should default to the billing email if the Customer/User ID is unavailable 🤔.
