### ISSUE TITLE
Cart list items is empty when addToCart Mutation is succesfull

### ISSUE THREAD

**Issue by theodesp** [wp-graphql/wp-graphql-woocommerce#626]
**Describe the bug**
I'm using the WPGraphQL UI to test adding items in the cart and then retrieving them. When I add a mutation it works ok. However whenever I try to retrieve the cart items back it returns an empty list.

**To Reproduce**
1. Add a few products
2. Use WPGraphQL UI addToCart mutation to add a few items:

4. Use WPGraphQL UI cart query to retrieve the current cart.
5. See that the cart is empty

**Expected behavior**
When retrieving items form the cart it should show the list of added products.

**Screenshots**

**Mutation addToCart**
<img width="1115" alt="Screenshot 2022-05-22 at 21 11 32" src="https://user-images.githubusercontent.com/328805/169713934-7671d021-9416-44c5-93cc-80c92ead71b5.png">

**Querying the cart after the mutation**
<img width="1120" alt="Screenshot 2022-05-22 at 21 12 57" src="https://user-images.githubusercontent.com/328805/169713976-4172462c-8cf1-4553-aeb3-f157ec63e665.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Plugin Versions**
- **WooGraphQL Version:** 0.11.0
- **WPGraphQL Version:** 1.8.2
- **WordPress Version:** 5.9
- **WooCommerce Version:** 6.5.1

**Additional context**

**Comment by theodesp** [comment]
I actually pinpointed the WPGraphQL Version that this issue does not happen:
When using **WPGraphQL Version: 1.6.12** It not have this issue and I can see the cart contents.

<img width="1616" alt="Screenshot 2022-05-23 at 10 28 41" src="https://user-images.githubusercontent.com/328805/169789145-84b127f8-dd57-4401-9442-3e7678254f9d.png">
<img width="1287" alt="Screenshot 2022-05-23 at 10 30 58" src="https://user-images.githubusercontent.com/328805/169789417-1c2b3727-a4a1-4ee2-8d5c-3a417272ea47.png">


I'm pinging @jasonbahl  for this as well

**Comment by jasonbahl** [comment]
If I understand correctly, you're saying that this works with WPGraphQL v1.6.12, but not in WPGraphQL v1.7+?

I don't see anything suspicious in v1.7 regarding connection resolvers, so my guess is that the change affecting this is the change to the GraphiQL IDE. 

In 1.7 we changed the GraphiQL IDE to execute as a public user by default instead of an authenticated user. You can click the avatar next to the Play button to execute as a logged in user. 

Does this change the behavior?

**Comment by theodesp** [comment]
@theodesp Running as an authenticated user fixed this issue thank you!

<img width="1109" alt="Screenshot 2022-05-23 at 20 33 32" src="https://user-images.githubusercontent.com/328805/169892944-83a5d8a1-600c-4418-9983-576ef21f6216.png">
!
