### ISSUE TITLE
WooGraphQL Documentation Update

### ISSUE THREAD

**Issue by NavePnow** [wp-graphql/wp-graphql-woocommerce#629]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to search the related queries documents using graphql IDE in Wordpress.

**Describe the solution you'd like**
Support details about woocommerce related graphql documents in the website.

**Comment by kidunot89** [comment]
@NavePnow Sorry, about the docs. The docs have been stalled due to my lack of time to update them, but I hope to change this in the future.
Are there any topics in particular that you'd like documentation on?
