### ISSUE TITLE
Add custom field to mutation

### ISSUE THREAD

**Issue by brokieb** [wp-graphql/wp-graphql-woocommerce#632]
**Is your feature request related to a problem? Please describe.**
Some customers wan't to add TAX number to order.

**Describe the solution you'd like**
I wan't add taxNumber field to CustomerAddressInput, and after fill this field in mutation, this data is not saved

**Additional context**

```
add_filter('graphql_input_fields', function($input_fields, $type_name) {
    if ($type_name === "CustomerAddressInput") {
        $input_fields['vatNumber'] = [
            'type' => 'String',
            'description' => __('vat number field.', 'wp-graphql'),
        ];
    }

    return $input_fields;
}, 10, 2);
```

**Comment by kidunot89** [comment]
@brokieb This can be done by doing `register_graphql_field()` on `CustomerAddressInput` but this you have to hook into a filter like [this one](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/data/mutation/class-order-mutation.php#L96) to process it.

**Comment by kidunot89** [comment]
@jensej your code has some errors. Use `order->get_id()` not `order->id`.

**Comment by jensej** [comment]
> @jensej your code has some errors. Use `order->get_id()` not `order->id`.

@kidunot89 
nothing has changed, looks like the hook won't turn on

**Comment by kidunot89** [comment]
@jensej What mutation are you running?

**Comment by johnakisk0700** [comment]
@kidunot89 
Hello, I'm also struggling with the same thing with the checkout mutation. I don't have any previous wordpress experience and can't seem to work out how the ecosystem works and where to write these hooks. It would be really helpful if you could reference me some guides.

**Comment by kidunot89** [comment]
@johnakisk0700 You `register_graphql_field` call needs a `resolve` callback. See an example [here](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/type/object/class-cart-type.php#L112-L120)
