### ISSUE TITLE
Error at plugin activation

### ISSUE THREAD

**Issue by szvest** [wp-graphql/wp-graphql-woocommerce#635]
The plugin produces the following error at activation :

_**Fatal error: Uncaught Error: Call to undefined function WPGraphQL\WooCommerce\Functions\setup_minor_integrations() in /Users/.../Local Sites/.../app/public/wp-content/plugins/wp-graphql-woocommerce-develop/includes/class-wp-graphql-woocommerce.php on line 196**_ 

1. Download wp-graphql-woocommerce plugin
2. Click on 'activate'
4. See error above

**Plugin Versions**
- **WooGraphQL Version: 0.11.1
- **WPGraphQL Version: 1.8.6
- **WordPress Version: 6.0
- **WooCommerce Version: 6.6.1

**Comment by fredericbarry** [comment]
@szvest Did you run `composer install` in the plugin's directory? That solved the error for me.

**Comment by szvest** [comment]
> @szvest Did you run `composer install` in the plugin's directory? That solved the error for me.

That solved it! Thanks @fredericbarry!
