### ISSUE TITLE
Invalid payment method: Paypal

### ISSUE THREAD

**Issue by gabriel-frattini** [wp-graphql/wp-graphql-woocommerce#640]
**Describe the bug**

Im not able to have paypal as a payment method when im executing a checkout mutation.
Cash on delivery (cod) is working fine as a payment method but even though i have paypal setup in woocommerce and enabled as a payment method its just not working

**To Reproduce**

This is the mutation im sending to woocommerce
```

const CHECKOUT = gql`
  mutation CHECKOUT_MUTATION($input: CheckoutInput!) {
    checkout(input: $input) {
      clientMutationId
      order {
        id
        orderKey
        refunds {
          nodes {
            amount
          }
        }
        status
      }
      result
      redirect
    }
  }
`

```

And this is the input

```
  const [checkout] = useMutation(CHECKOUT)

  async function handleOrder() {
    try {
      await checkout({
        variables: {
          input: {
            billing: {
              address1: "109 Hills Road Valley",
              address2: "Station Road",
              city: "Example City",
              company: "Other Company GmbH",
              country: "DE",
              email: "test@email.com",
              firstName: "Firstname",
              lastName: "Lastname",
              phone: "089123456789",
              postcode: "80808",
              state: "Bavaria",
            },
            clientMutationId: "50e75f32-9f72-4e16-a5a4-41f4ff76ff2c",
            isPaid: false,
            paymentMethod: "paypal",
            shipToDifferentAddress: true,
            shipping: {
              address1: "Beispielstrasse 14",
              address2: "2. Aptartment",
              city: "Berlin",
              company: "D Company GmbH",
              country: "DE",
              email: "test@email.com",
              firstName: "Peter",
              lastName: "Pan",
              phone: "089123456789",
              postcode: "12342",
              state: "Berlin",
            },
            transactionId: "b1605b91-1d3a-4008-aa7b-290a098631bd",
          },
        },
      })
    } catch (error) {
      console.error(error)
    }
  }
```

And before the checkout im sending a AddToCart mutation to get the woo-session cookie

```

const ADD_TO_CART = gql`
  mutation ATC($input: AddToCartInput!) {
    addToCart(input: $input) {
      cart {
        subtotal
        total
        shippingTotal
        contents {
          itemCount
          nodes {
            product {
              node {
                ... on SimpleProduct {
                  name
                  price(format: RAW)
                }
                ... on VariableProduct {
                  name
                  price(format: RAW)
                }
              }
            }
          }
        }
      }
    }
  }
`

```

**Expected behavior**

Checkout mutation should be succesful with paypal as payment method

**Desktop (please complete the following information):**
 - OS: Windows

**Plugin Versions**
- **WooGraphQL Version:**  0.10.7
- **WPGraphQL Version:** 1.8.6
- **WooCommerce Version:** 6.6.1
- **gatbsy-source-wordpress:** 6.17.0
- **Woocommerce Paypal Payments:**  1.9.0

**Additional context**

If i go to settings for paypal payments under woocommerce and click on "Paypal card Processing" it says "Unfortunately, the card processing option is not yet available in your country. [Advanced credit and debit country and currency availability.]" 
I live in sweden but i was able to use the paypal SDK directly from their client so i dont know if thats the reason.

**Comment by kidunot89** [comment]
@gabriel-frattini Make sure your running this in WPGraphQL Debug Mode so you can see the proper error details. And I'm almost positive the `id` for the gateway you want to use isn't `paypal`. That's the `id` for the default paypal payment gateway.

You can be sure by querying the available payment gateways.
```graphql
query {
  paymentGateways {
    nodes {
      description
      icon
      id
      title
    }
  }
}
```
