### ISSUE TITLE
Checkout Mutation Fails

### ISSUE THREAD

**Issue by oseisaac** [wp-graphql/wp-graphql-woocommerce#645]
I know it says no session found for user. 
But is kinda contrary because I'm using the login from the plugin
QUERY
mutation checkout {
  checkout(
    input: {billing: {firstName: "fdgfdgdf", email: "test@gmail.com"}, clientMutationId: "894655", paymentMethod: "stripe", metaData: {key: "_stripe_source_id", value: "sec_HKirFDpxgCZGruGMEASVWk2k4JOHcxEk"}}
  ) {
    clientMutationId
    customer {
      id
    }
    order {
      date
      id
    }
  }
}
Result
{
  "errors": [
    {
      "message": "Sorry, no session found.",
      "extensions": {
        "category": "user"
      },
      "locations": [
        {
          "line": 30,
          "column": 3
        }
      ],
      "path": [
        "checkout"
      ],
      "trace": [
        {
          "file": "/code/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php",
          "line": 1092,
          "call": "WPGraphQL\\WooCommerce\\Mutation\\Checkout::WPGraphQL\\WooCommerce\\Mutation\\{closure}(array(4), instance of WPGraphQL\\AppContext, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/src/Utils/InstrumentSchema.php",
          "line": 151,
          "call": "WPGraphQL\\Registry\\TypeRegistry::WPGraphQL\\Registry\\{closure}(null, array(1), instance of WPGraphQL\\AppContext, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 623,
          "call": "WPGraphQL\\Utils\\InstrumentSchema::WPGraphQL\\Utils\\{closure}(null, array(1), instance of WPGraphQL\\AppContext, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 550,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveFieldValueOrError(instance of GraphQL\\Type\\Definition\\FieldDefinition, instance of GraphQL\\Language\\AST\\FieldNode, instance of Closure, null, instance of GraphQL\\Type\\Definition\\ResolveInfo)"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 474,
          "call": "GraphQL\\Executor\\ReferenceExecutor::resolveField(GraphQLType: RootMutation, null, instance of ArrayObject(1), array(1))"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 857,
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'checkout')"
        },
        {
          "call": "GraphQL\\Executor\\ReferenceExecutor::GraphQL\\Executor\\{closure}(array(0), 'checkout')"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 859,
          "function": "array_reduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 490,
          "call": "GraphQL\\Executor\\ReferenceExecutor::promiseReduce(array(1), instance of Closure, array(0))"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 263,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeFieldsSerially(GraphQLType: RootMutation, null, array(0), instance of ArrayObject(1))"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/ReferenceExecutor.php",
          "line": 215,
          "call": "GraphQL\\Executor\\ReferenceExecutor::executeOperation(instance of GraphQL\\Language\\AST\\OperationDefinitionNode, null)"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Executor/Executor.php",
          "line": 156,
          "call": "GraphQL\\Executor\\ReferenceExecutor::doExecute()"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/GraphQL.php",
          "line": 162,
          "call": "GraphQL\\Executor\\Executor::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of WPGraphQL\\WPSchema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of WPGraphQL\\AppContext, array(1), 'checkout', null)"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Server/Helper.php",
          "line": 311,
          "call": "GraphQL\\GraphQL::promiseToExecute(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of WPGraphQL\\WPSchema, instance of GraphQL\\Language\\AST\\DocumentNode, null, instance of WPGraphQL\\AppContext, array(1), 'checkout', null, array(29))"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Server/Helper.php",
          "line": 211,
          "call": "GraphQL\\Server\\Helper::promiseToExecuteOperation(instance of GraphQL\\Executor\\Promise\\Adapter\\SyncPromiseAdapter, instance of GraphQL\\Server\\ServerConfig, instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/vendor/webonyx/graphql-php/src/Server/StandardServer.php",
          "line": 136,
          "call": "GraphQL\\Server\\Helper::executeOperation(instance of GraphQL\\Server\\ServerConfig, instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/src/Request.php",
          "line": 693,
          "call": "GraphQL\\Server\\StandardServer::executeRequest(instance of GraphQL\\Server\\OperationParams)"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/src/Router.php",
          "line": 463,
          "call": "WPGraphQL\\Request::execute_http()"
        },
        {
          "file": "/code/wp-content/plugins/wp-graphql/src/Router.php",
          "line": 265,
          "call": "WPGraphQL\\Router::process_http_request()"
        },
        {
          "file": "/code/wp-includes/class-wp-hook.php",
          "line": 307,
          "call": "WPGraphQL\\Router::resolve_http_request(instance of WP)"
        },
        {
          "file": "/code/wp-includes/class-wp-hook.php",
          "line": 331,
          "call": "WP_Hook::apply_filters(null, array(1))"
        },
        {
          "file": "/code/wp-includes/plugin.php",
          "line": 524,
          "call": "WP_Hook::do_action(array(1))"
        },
        {
          "file": "/code/wp-includes/class-wp.php",
          "line": 398,
          "function": "do_action_ref_array('parse_request', array(1))"
        },
        {
          "file": "/code/wp-includes/class-wp.php",
          "line": 770,
          "call": "WP::parse_request((empty string))"
        },
        {
          "file": "/code/wp-includes/functions.php",
          "line": 1330,
          "call": "WP::main((empty string))"
        },
        {
          "file": "/code/wp-blog-header.php",
          "line": 16,
          "function": "wp()"
        },
        {
          "file": "/code/index.php",
          "line": 17,
          "function": "require('/code/wp-blog-header.php')"
        }
      ]
    }
  ],
  "data": {
    "checkout": null
  },
  "extensions": {
    "debug": [],
    "tracing": {
      "version": 1,
      "startTime": 1658842851.247935,
      "endTime": 1658842851.259348,
      "duration": 11412,
      "execution": {
        "resolvers": []
      }
    }
  }
}

**Comment by kidunot89** [comment]
@oseisaac See this 👉🏿 https://github.com/wp-graphql/wp-graphql-woocommerce/issues/147
