### ISSUE TITLE
Unable to filter product with attribute and attributeterm

### ISSUE THREAD

**Issue by codehouseno** [wp-graphql/wp-graphql-woocommerce#654]
**Describe the bug**
When querying a product's variations, there isn't possible to filter by attributes. The response is always an empty array. 

**To Reproduce**
- Either try in graphiQl or by code:
- Fetch product by id
   ... on VariableProduct {
     variations(where: {attribute: "pa_color", attributeTerm: "red"}) {
       ..
    }
}

**Expected behavior**
The respond should be variations of a product, what have color red (or any other color defined by term)

**Screenshots**
![Skjermbilde 2022-09-02 kl  09 21 33](https://user-images.githubusercontent.com/40666574/188081520-7926b3f0-7e36-45ee-bcb5-cef4f7514d78.png)

**Desktop (please complete the following information):**
 - OS: iOs
 - Browser:  chrome

**Smartphone (please complete the following information):**
 - Device: Desktop
 - OS: iOs 12.3.1
 - Browser Chrome

**Plugin Versions**
- **WooGraphQL Version: 0.11.2
- **WPGraphQL Version:1.9.1
- **WordPress Version:6.0.2
- **WooCommerce Version:6.8.2

**Comment by veegandhi** [comment]
Facing the same issue when filtering by variation's `databaseId` .

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/11186508/194052730-2fa5f187-f12e-46d7-902f-d5434c354c88.png">


**Plugin Versions**

WooGraphQL Version: 0.11.2
WPGraphQL Version:1.11.1
WordPress Version:6.0.2
WooCommerce Version:6.9.2

**Comment by kidunot89** [comment]
@codehouseno

`attribute` and `attributeTerm` are only used for filtering products not product variations. To achieve you desire results do the following or loop thru all the variations

```graphql
query {
  paColor(id: "red", idType: SLUG) {
    variations(where: {parent: 119}) {
      nodes {
        name
        guid
        databaseId
        attributes {
          nodes {
            value
          }
        }
        stockQuantity
        stockStatus
        price(format: FORMATTED)
        regularPrice(format: FORMATTED)
        salePrice(format: FORMATTED)
      }
    }
  }
}
```
