### ISSUE TITLE
Question: How to get all eligible shipping methods for current cart

### ISSUE THREAD

**Issue by KeetTechSol** [wp-graphql/wp-graphql-woocommerce#655]
Hi, our store use postcode restrictions for shipping methods. How can I get the eligible shipping methods for the current cart after updating customer billing and shipping details

Thank you

**Comment by kidunot89** [comment]
` query {
    cart {
      availableShippingMethods {
        ... 
      }
    }
  }
`
See more about the `cart` query [here](https://woographql.com/schema/query/cart)
