### ISSUE TITLE
Decimal Product Quantities

### ISSUE THREAD

**Issue by mruknowme** [wp-graphql/wp-graphql-woocommerce#656]
Is it possible to force edit field type for the schema?
I installed plugin 'Decimal Product Quantities' but GraphqQL Schema still requires quantity in `addToCart` to be `Int`.

**Comment by kidunot89** [comment]
@mruknowme You'd have to deregister and register the `quality` field across the schema.

**Comment by mruknowme** [comment]
Thanks for the information, will read about it and give it a try

**Comment by mruknowme** [comment]
Just confirming that your suggestion worked, though I also had to de-register and register with Float additionally the following:
```php
  deregister_graphql_field('CartItemQuantityInput', 'quantity');
  deregister_graphql_field('LineItem', 'quantity');
  deregister_graphql_field('LineItemInput', 'quantity');
  deregister_graphql_field('CartToCartItemConnection', 'itemCount');
```
