### ISSUE TITLE
Filtering by multiple categories Using AND rather than OR

### ISSUE THREAD

**Issue by dialformonkey** [wp-graphql/wp-graphql-woocommerce#657]
Hi looking for a way to filter for products containing both categories.

**Comment by kidunot89** [comment]
@dialformonkey 
```graphql
query {
   products(where: { categoryIn: [*} }) {
     ...product fields
   }
  }
```
See more about the `products` query's `where` input [here](https://woographql.com/schema/definition/-root-query-to-product-connection-where-args)

**Comment by dialformonkey** [comment]
@kidunot89 

Doesn't seem to work for my use case. Categories on the product belong to two separate parents. I managed to pull up some data using the taxonomy filter with an OR operator. However im unable to query when i use the AND. attached the query result for you to check below. Could share the URL if you require via slack maybe?

<img width="1522" alt="Screen Shot 2022-09-16 at 7 08 50 AM" src="https://user-images.githubusercontent.com/62189575/190541107-c98c71ae-26e4-402e-8e5d-1f4278347f7b.png">
<img width="1541" alt="Screen Shot 2022-09-16 at 7 09 21 AM" src="https://user-images.githubusercontent.com/62189575/190541164-38b8cdc4-23c2-43d4-9e93-93d5538e3f0c.png">

**Comment by dialformonkey** [comment]
A taxonomy filter array seems to solve this problem
