### ISSUE TITLE
Question: What is difference between `createOrder` and `checkout` mutations?

### ISSUE THREAD

**Issue by vorasudh** [wp-graphql/wp-graphql-woocommerce#661]
In my case, I would like WP to handle payment, so I prefer using the `checkout` mutation that returns a `redirect` URL for making payment. However, in `createOrder` mutation, one can add `currency`, `coupons`, etc to the order which is missing in the `checkout` mutation.

Therefore, I am confused about which to use and when?

**Comment by vorasudh** [comment]
ahh Okay. understood. checkout mutation returns `redirect` URL that can be used to make payment. After payment, we can programmatically redirect to whichever page we want.

**Comment by kidunot89** [comment]
@vorasudh The difference is `checkout` reads the user session to generate the order, while `createOrder` required all order detail be provided on the spot.
