### ISSUE TITLE
Product where categoryIn returns empty after update 

### ISSUE THREAD

**Issue by Julhol-droid** [wp-graphql/wp-graphql-woocommerce#662]
**Describe the bug**
I updated the Plugin from 0.10.7 to  0.11.2. In the previous Version I was able to query products with "where categoryIn" clause. Like this: 

```
query CategoryIn {
  products(where: {categoryIn: ["add-on", "merch"]}) {
    nodes {
      name
    }
  }
}
```

Before the update to 0.11.2. the Products were returned correctly, but now the returned nodes are empty.
If I use the category where it works correctly. However with this Setup I am only able to query for one Category.

```
query OneCategory {
  products(where: {category: "add-on"}) {
    nodes {
      name
    }
  }
}
```

**To Reproduce**
1. Create a Product in Woocommerce and add the category "Add-on"
2. Create a second Product in Woocommerce and add the category "merch"
3. Try to query it via the "CategoryIn" query listed above.

**Expected behavior**
The "CategoryIn" query should return both products.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome, but I think it has nothing to do with the browser.
 - Version 105.0.5195.127 (Offizieller Build) (64-Bit) (cohort: Stable) 

**Smartphone (please complete the following information):**
 - Didn't try it on Phone

**Plugin Versions**
- **WooGraphQL Version: ** 0.11.2.
- **WPGraphQL Version:** 1.11.3
- **WordPress Version: ** 6.0.1
- **WooCommerce Version: ** 6.9.4

Thanks for helping.

**Comment by Julhol-droid** [comment]
Ok I noticed, that if I downgrade WPGraphql from 1.11.3 to 1.9.1 (my prev version) it works. So it has something to do with WP Graphql I think.

**Comment by creative-andrew** [comment]
I am getting the same problem.

**Comment by creative-andrew** [comment]
@kidunot89 @jasonbahl any update on this?

**Comment by hofewo** [comment]
same problem here. The latest working version of WPGraphQL that doesn't have this problem for me is 1.10.0 (working with WooGraphQL 0.11.2)

**Comment by khalibloo** [comment]
Having the same issue. It also affects the products query, when trying to filter by product IDs.

**Comment by kidunot89** [comment]
@khalibloo @hofewo @creative-andrew @Julhol-droid Can you confirm this issue in `v0.12.1`?

**Comment by creative-andrew** [comment]
I can confirm it is working.

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/18492002/217569007-21144872-fb3f-4bd9-bd8e-64d5740643fb.png">

**Comment by claudio-uey** [comment]
I am facing this issue. I have wp-graphql-woocommerce v0.18.2, wp-graphql v1.17.0.
