### ISSUE TITLE
Fetch Payment Gateways

### ISSUE THREAD

**Issue by vorasudh** [wp-graphql/wp-graphql-woocommerce#665]
**Describe the bug**
I have set up 2 payment methods - `Cash on Delivery` and `RazorPay`. `RazorPay` is available for all types of shipping methods whereas `Cash on Delivery` is available for only 1 type of shipping method - Free shipping. Now only the `Razorpay` method is returned with the below query (no matter what shipping method is used). If I remove the restriction of shipping method for Cash on Delivery, then both payment gateways are returned.

Can you guide me in case I have configured something wrong? Or is this a bug?

**NOTE**: The shipping methods get applied automatically based on the shipping address.

**To Reproduce**
```
query GetPaymentGateways {
  paymentGateways {
    nodes {
      id
      title
      icon
      description
    }
  }
}
```

**Expected behavior**
With the above query, both razor pay and Cash on Delivery methods should be returned.

**Plugin Versions**
- **WooGraphQL Version:** 0.11.2
- **WPGraphQL Version:** 1.12.1
- **WordPress Version:** 6.1
- **WooCommerce Version:** 7.0.1

**Comment by kidunot89** [comment]
If I remember correctly, payment gateways are restricted by the current location of the end-user. This is determined by the shipping address saved for current user attached to the user session, I think WooCommerce core get around this by using geolocation detection if no shipping address is set, and WooGraphQL, at the moment, doesn't provided a pass-thru to use this functionality, so you'd have to do some kind geolocation detection on client and update the user shipping address with the retrieved field _(typically `country`, `state/province`, and `postcode/zip`)_ using the `updateCustomer` mutation. Then on the following `paymentGateways` queries should have `cod` in the results if the end-user is within the correct shipping zone.

**Comment by kidunot89** [comment]
@vorasudh Any updates on this.

**Comment by kidunot89** [comment]
Since there has been no response on this, I'm closing this.
