### ISSUE TITLE
Documentation looks incorrect

### ISSUE THREAD

**Issue by AVert** [wp-graphql/wp-graphql-woocommerce#668]
**Describe the bug**
Layout of your schema Documentation is broken
is it impossible to read 
Seems class hljs-* loose some of its properties and not break lines 

**To Reproduce**
1. Open browser
2. Go to: https://woographql.com/schema/query/cart

**Expected behavior**
Separate field name on every line

**Screenshots**
![image](https://user-images.githubusercontent.com/316002/203434909-e852d1f4-3401-49ab-836a-a77568f7c8ca.png)
![image](https://user-images.githubusercontent.com/316002/203435076-9aae1fa8-2eef-48a9-95c9-e06bba5c26f1.png)

**Desktop (please complete the following information):**
 - Linux Mint
 - Browser Crome And Firefox

**Comment by AVert** [comment]
if add 
![image](https://user-images.githubusercontent.com/316002/203435924-13a2666f-d86a-496d-bdac-b6205616c9d8.png)
looks more correct
![image](https://user-images.githubusercontent.com/316002/203435986-ce178a66-d708-43cb-abab-e70d16143c14.png)

**Comment by kidunot89** [comment]
@AVert Done, thanks for the report. I'm still trying to perfect the styling. Bear we me just a little longer. 🙏🏿
