### ISSUE TITLE
WPGRAPHQL_WOOCOMMERCE_VERSION  doesn't match plugin version

### ISSUE THREAD

**Issue by jmotes** [wp-graphql/wp-graphql-woocommerce#677]
**Describe the bug**
WPGRAPHQL_WOOCOMMERCE_VERSION  doesn't match plugin version

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Plugin Versions**
**WooGraphQL Version: 0.12.0
**WPGraphQL Version: 1.13.6
**WordPress Version: 6.1.1
**WooCommerce Version: 7.1.1

**Additional context**
N/A

**Comment by kidunot89** [comment]
Merged and correct in the current version.
