### ISSUE TITLE
WooGraphQL appears to have been installed without it's dependencies

### ISSUE THREAD

**Issue by vstrelianyi** [wp-graphql/wp-graphql-woocommerce#678]
I have WPGraphQL  Version 1.13.6 installed

I have activated the plugin  WPGraphQL WooCommerce (WooGraphQL) ver 0.12.0 and getting this error message

WooGraphQL appears to have been installed without it's dependencies. It will not work properly until dependencies are installed. This likely means you have cloned WPGraphQL from Github and need to run the command `composer install`.

**Comment by BenParr64** [comment]
I am getting the same issue

**Comment by mfs-bldmghty** [comment]
I am as well. But during the composer require I didn't get any errors / warnings. 

$ composer require wp-graphql/wp-graphql wp-graphql/wp-graphql-woocommerce

Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]? yes

Using version ^1.13 for wp-graphql/wp-graphql
Using version ^0.12.0 for wp-graphql/wp-graphql-woocommerce
./composer.json has been updated                           
Running composer update wp-graphql/wp-graphql wp-graphql/wp-graphql-woocommerce
Loading composer repositories with package information
Updating dependencies
Lock file operations: 4 installs, 1 update, 0 removals
  - Locking appsero/client (v1.2.1)
  - Locking ivome/graphql-relay-php (v0.6.0)
  - Locking webonyx/graphql-php (v14.9.0)
  - Locking wp-graphql/wp-graphql (v1.13.7)
  - Downgrading wp-graphql/wp-graphql-woocommerce (dev-master 23c7f30 => v0.12.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 4 installs, 1 update, 0 removals
  - Downloading webonyx/graphql-php (v14.9.0)
  - Downloading ivome/graphql-relay-php (v0.6.0)
  - Downloading appsero/client (v1.2.1)
  - Downloading wp-graphql/wp-graphql (v1.13.7)
  - Installing webonyx/graphql-php (v14.9.0): Extracting archive
  - Installing ivome/graphql-relay-php (v0.6.0): Extracting archive
  - Installing appsero/client (v1.2.1): Extracting archive
  - Installing wp-graphql/wp-graphql (v1.13.7): Extracting archive
  - Downgrading wp-graphql/wp-graphql-woocommerce (dev-master 23c7f30 => v0.12.0): Extracting archive
2 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
4 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
No security vulnerability advisories found

**Comment by mfs-bldmghty** [comment]
Well... apparently, it updated WPGraphQL to a version that isn't stable. :(

**Comment by kidunot89** [comment]
When using WooGraphQL with composer its recommended that somewhere in your application, you call
```php
require_once `vendor/autoload.php`
```
before the plugin is loaded.

If your using a setup like `johnpbloch/wordpress` package, Roots WP Bedrock, or SpinupWP this already done by your WP installation so shouldn't be needed.
