### ISSUE TITLE
An error from the plugin causes the application to disconnect from Wordpress using GraphQL and Apollo Client

### ISSUE THREAD

**Issue by WojciechPolec** [wp-graphql/wp-graphql-woocommerce#682]
### **Describe the bug**

We have a problem in an online store using the WPGraphQL WooCommerce (WooGraphQL) plugin. It manifests itself in such a way when we want to add a product to the basket when we are logged in and authorized, we cannot do it because on the GraphQL and Wordpress side we get ERROR, which causes us to lose communication and the operation cannot be performed.

**Error from debug.log:**
"PHP Fatal error:  Uncaught GraphQL\Error\UserError: Woo session transaction executed out of order in /public_html/wp-content/plugins/wp-graphql-woocommerce-2/includes/utils/class-session-transaction-manager.php:220"

I edited the plugin and commented out this line in the plugin code. Then everything started working as it should.

### **Expected behavior**
Operations performed via GraphQL and Apollo Client using the wp-graphql-woocommerce plugin should not lose connection due to an error. The code under the path /public_html/wp-content/plugins/wp-graphql-woocommerce-2/includes/utils/class-session-transaction-manager.php:220 breaks the connection and makes it impossible to perform other operations. Commenting out this solved the problem for me temporarily.

### **Plugin Versions and other**
- **WooGraphQL Version:** 0.11.2
- **WPGraphQL Version:** 1.11.2
- **WordPress Version:** 6.1.1
- **WooCommerce Version:** 6.3.1
- **Gatsby Version:** 4.17.2
- **GatsbySourceWordpress Version:** 6.10.2
- **React Version:** 17.0.1
- **Node Version:** 14.17.0
- **ApolloClient Version:** 3.6.9

### **Additional context**
Is this a bug? Is the problem elsewhere? I temporarily solved the problem by commenting out some plugin code but this is not an optimal solution and problematic if we want to update the plugin.

**Comment by vorasudh** [comment]
I am also facing the exact same issue - #684. I will take your suggestion and comment out the line.

**Comment by vorasudh** [comment]
I tried commenting out the code, but this results in all requests receiving a **403** response code. This basically means, no data is displayed on the webpage.

**Comment by WojciechPolec** [comment]
Anybody got any ideas how to solve this problem? Or some plugin update will solve it?

**Comment by C4MS** [comment]
I just experienced the same issue, after running out of memory while doing some tests, the user doing the request will receive the same error on all further requests by the server, I had to remove all transients as a quick fix which is not ideal on a production site
`wp transients delete --all`

**Comment by kidunot89** [comment]
@C4MS @WojciechPolec @vorasudh Are you correctly setting the `sessionToken` from under the `customer` query in the `woocommerce-session` HTTP header in your GraphQL request. It should be format like the ``Session ${sessionToken}``. Remember always prefix the token with `Session `.
```graphql
query {
  customer {
    sessionToken
  }
}
```

**Comment by kidunot89** [comment]
@C4MS @WojciechPolec @vorasudh Any updates on this?
