### ISSUE TITLE
TotalSales always return null

### ISSUE THREAD

**Issue by WojciechPolec** [wp-graphql/wp-graphql-woocommerce#683]
### **Describe the bug**
TotalSales always return null. I wanted to make Bestsellers on the store, but I can't get information about the totalSales of a given product using GraphQL. It always returns null. I have this problem at the GraphQL IDE level in Wordpress and at the application level in GraphQL. It prevents me from continuing to work on bestsellers.

### **Expected behavior**
I expected to get information on how much a given product was sold.

### **Screenshots**
![image](https://user-images.githubusercontent.com/70173962/208861920-e0a77566-f0dd-4d94-a997-24cce3de362c.png)

### **Plugin Versions and other**
- **WooGraphQL Version:** 0.11.2
- **WPGraphQL Version:** 1.11.2
- **WordPress Version:** 6.1.1
- **WooCommerce Version:** 6.3.1
- **Gatsby Version:** 4.17.2
- **GatsbySourceWordpress Version:** 6.10.2
- **React Version:** 17.0.1
- **Node Version:** 14.17.0
- **ApolloClient Version:** 3.6.9

### **Additional context**
Could this be fixed? Or is there any other way to get the totalSales of a given product in order to make a bestseller list?

**Comment by scottyzen** [comment]
Hi @WojciechPolec,

It's returning null because you're running the query as a guest user. Try toggling the button below to switch to an authenticated user and run it again.

![Screenshot 2022-12-21 at 09 14 41](https://user-images.githubusercontent.com/5116925/208868085-e7326911-759f-496b-b9a0-024909769c7f.jpg)

**Comment by WojciechPolec** [comment]
Thanks! It worked.

![image](https://user-images.githubusercontent.com/70173962/208870809-812ea9d8-24a0-44bb-b55e-cea56b9817e8.png)

But what does it look like on the application side? How can I apply this on the application side? Only logged in and authorized users will be able to see Bestsellers? I want to make a page with best-selling products and in the category view, sorting by bestsellers.

**Comment by WojciechPolec** [comment]
Is it possible to change it on the plugin or Wordpress side so that information about totalSales is public and also for non-logged in users?

**Comment by WojciechPolec** [comment]
I checked several solutions and I come to the conclusion that in a Gatsby based store, WooCommerce, and
wp-graphql-woocommerce, the product's totalSales information cannot be fetched unless you are logged in. I would like the functionalities that will be needed by totalSales to be also available to users who are not logged in. Apollo Client mutations also start working with totalSales if we are logged in. If the customer is not logged in then totalSales is null and returns errors.

So is there any way to make totalSales a public value? Or it could have been downloaded in gatsby-node.js or in a template for an unauthorized user? If not, how can I authorize for this particular query?

Is there a hook that would allow you to influence totalSales and change its privacy rules?

With such plugin settings, I don't see a solution for not logged in customers in the store to be able to sort by best-selling products and view the list of bestsellers.

Thank you in advance for your help.

**Comment by scottyzen** [comment]
Add this to your function.php file.

```php
add_filter( 'graphql_product_fields', function( $fields ) {
    $fields['totalSales'] = [
        'type' => 'Int',
        'resolve' => function( $source, $args, $context, $info) {
            return $source->get_total_sales();
        },
    ];
    return $fields;
} );
```

**Comment by WojciechPolec** [comment]
It works! Thank you very much for your help. I'm closing this issue.
