### ISSUE TITLE
Internal Server Error when executing mutation

### ISSUE THREAD

**Issue by vorasudh** [wp-graphql/wp-graphql-woocommerce#684]
**Describe the bug**
For user authentication, I am using `wp-graphql-jwt-authentication` plugin. When trying to execute any `mutation` with an authorization header set, I get the error code **500** - internal server error. When trying to execute a `query`, I get results but with the error code **403**. After looking at the server logs (see below) it seemed to originate from this plugin and not `wp-graphql-jwt-authentication`

**To Reproduce**
1. Login using login mutation from `wp-graphql-jwt-authentication`
2. Use the received `authToken` in the header to execute any mutation

**Expected behavior**
The mutation should get executed and return a result.

**Error Log**

```
PHP Fatal error: Uncaught GraphQL\Error\UserError: Woo session transaction executed out of order in abc@abc.com/wp-content/plugins/wp-graphql-woocommerce/includes/utils/class-session-transaction-manager.php:220
Stack trace:
#0 abc@abc.com/wp-includes/class-wp-hook.php(310): WPGraphQL\WooCommerce\Utils\Session_Transaction_Manager->pop_transaction_id(Object(GraphQL\Executor\ExecutionResult))
#1 abc@abc.com/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array)
#2 abc@abc.com/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 abc@abc.com/wp-content/plugins/wp-graphql/src/Router.php(536): do_action('graphql_process...', Object(GraphQL\Executor\ExecutionResult), Object(GraphQL\Executor\ExecutionResult), '', 'mutation AddToCart...', NULL, 403)
#4 abc@abc.com/wp-content/plugins/wp-graphql/src/Router.php(275): WPGraphQ in abc@abc.com/wp-content/plugins/wp-graphql-woocommerce/includes/utils/class-session-transaction-manager.php on line 220
```

**Plugin Versions**
- **WooGraphQL Version:** 0.12.0
- **WPGraphQL Version:** 1.13.7
- **WordPress Version:** 6.1.1
- **WooCommerce Version:** 7.2.2

**Comment by kidunot89** [comment]
@vorasudh Can you share some info about how your using the auth token client-side?

**Comment by kidunot89** [comment]
I've gain some new insight into this issue. Make your your using `woocommerce-session` token. And you have the support for Authorization header in your Apache or Nginx server config. Read more [here](https://woographql.com/docs/handling-user-authentication) and [here](https://github.com/wp-graphql/wp-graphql-jwt-authentication#http_authorization)
