### ISSUE TITLE
orders query shippingTotal(format: RAW) 

### ISSUE THREAD

**Issue by AVert** [wp-graphql/wp-graphql-woocommerce#688]
### Description

query orders  
shippingTotal(format: RAW)  return null

### Steps to reproduce

query MyQuery {
    orders(where: {customerId: 44}) {
    nodes {
      currency
      databaseId
      status
      date_created: date
      date_modified: modified
      shipping_total: shippingTotal(format: RAW)
      customer_note: customerNote
      payment_method_title: paymentMethodTitle
    }
  }

### WPGraphQL Version

1.12.2

### WordPress Version

6.1.1

### PHP Version

7.4.32

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

### Please confirm that you have disabled ALL plugins except for WPGraphQL.

- [ ] Yes
- [ ] My issue is with compatibility with a specific WordPress plugin, and I have listed all my installed plugins (and version info) above.

**Comment by jasonbahl** [comment]
@AVert I've transferred this issue to the WPGraphQL for WooCommerce repo

**Comment by kidunot89** [comment]
@justlevine I've made an exception for product and line item prices. 
@AVert This has been patched as of WooGraphQL v0.12.1
