### ISSUE TITLE
@kidunot89 Is there a way to sync the guest cart to the user cart when the user logs in?

### ISSUE THREAD

**Issue by sarkis1997** [wp-graphql/wp-graphql-woocommerce#691]
@kidunot89 Is there a way to sync the guest cart to the user cart when the user logs in?

_Originally posted by @guilhermejbranco in https://github.com/wp-graphql/wp-graphql-woocommerce/issues/285#issuecomment-674071474_
      

Is there already a solution for this?

**Comment by kidunot89** [comment]
Using the `login` mutation while providing the `woocommerce-session` HTTP header should result in the session being updated. Retrieving the `woocommerce-session` HTTP header from the resulting response will be the modified session token for the recently logged in user. Be sure to use the response header and not the `sessionToken` from `login` mutation output. Using that one will erase the old session.

**Comment by kidunot89** [comment]
@sarkis1997 ☝🏿
