### ISSUE TITLE
Is it possible send a complete local cart to the woocommerce cart?

### ISSUE THREAD

**Issue by sarkis1997** [wp-graphql/wp-graphql-woocommerce#693]
I am handling the cart with localstorage for speed purposes. Is it possible to send a complete cart to the woocommerce cart (new session and existing session)? I think that this would be on the checkout page, once checking out, sending the local cart and getting the updated cart to pass to checkout.

**Comment by kidunot89** [comment]
@sarkis1997 Have you tried the `fillCart` mutation, or persisting the Apollo Cache instead of just storing the cart in localstorage.

**Comment by w3bdesign** [comment]
@sarkis1997 

What about handling the cart locally with a state manager and running a mutation in the background to handle the synchronization of the cart?

**Comment by kidunot89** [comment]
@sarkis1997 The `fillCart` mutation is what you want then
