### ISSUE TITLE
Filter product attributes by product categories and/or other product attributes

### ISSUE THREAD

**Issue by ninie1205** [wp-graphql/wp-graphql-woocommerce#708]
**Is your feature request related to a problem? Please describe.**
Is there any possibility of filtering product attributes by product categories and/or other product attributes?

**Describe the solution you'd like**
Implement `productCategory` and `terms` options in the `terms` graphql schema where one can filter by taxonomies

**Describe alternatives you've considered**
There's no alternative whatsoever at this moment, not even a REST API endpoint 

**Additional context**
- A mega-menu that shows a list of available product attributes related to the current category
- A sidebar filter that updates itself each time the user changes filters

**Comment by kidunot89** [comment]
@ninie1205 This is because product categories and product attributes have no direct associate in core WooCommerce, and because of this it is out of the scope of WooGraphQL. Sorry.
