### ISSUE TITLE
QL_Session_Handler causes critical error if set_customer_session_cookie is called.

### ISSUE THREAD

**Issue by creative-andrew** [wp-graphql/wp-graphql-woocommerce#709]
**Describe the bug**
The `QL_Session_Handler` doesn’t call the `WC_Session_Handler ` [parent constructor](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/utils/class-ql-session-handler.php#L59).
This causes the [$_cookie](https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-session-handler.html#source-view.61) to be undefined.

Some plugins can potentially call the `set_customer_session_cookie` method available in `QL_Session_Handler` through inheritance.
https://woocommerce.github.io/code-reference/files/woocommerce-includes-class-wc-session-handler.html#source-view.157

This creates a critical error.

`Uncaught ValueError: setcookie(): Argument #1 ($name) cannot be empty in /plugins/woocommerce/includes/wc-core-functions.php:1095`

**Expected behavior**
Calling `set_customer_session_cookie` should not create a critical error. 

**Additional context**
[Slack thread](https://wp-graphql.slack.com/archives/CCYJRDN4A/p1677507151442049)

**Comment by kidunot89** [comment]
@creative-andrew The was fixed with your PR.
