### ISSUE TITLE
Make compatible with official woocommerce deposits plugin

### ISSUE THREAD

**Issue by zack-rose** [wp-graphql/wp-graphql-woocommerce#715]
Hi there,

Are there any plans to make wp-graphql-woo compatible with the official woocommerce deposits plugin? ie you can add to cart as a deposit item not just as a full price item? and then when you go to checkout page it recognises its a deposit item and charges the right price and the order in the backend also shows this.

I assume you'd need a new AddToCart mutation that would add deposit items to the cart. I checked but extraData on AddToCart at the moment can only be a string but this doesn't allow to add the necessary meta data for woo to recognise a deposit item.

Thanks

**Comment by kidunot89** [comment]
No there isn't. WooGraphQL is limited to the scope of WooCommerce core's functionality. If it's not in the main WooCommerce plugin, it's not likely to get direct support in WooGraphQL.
