### ISSUE TITLE
Cant get product info unless user is logged in

### ISSUE THREAD

**Issue by barrynerd** [wp-graphql/wp-graphql-woocommerce#719]
**Describe the bug**
I am new to graphql, not new to wordpress and woocommerce. Am looking to build nextjs front ends with wp/woo backend.

Currently installed: 

WPGraphQL 1.14.0
WPGraphQL WooCommerce (WooGraphQL) 0.12.0 

I can do queries successfully on posts and pages in wpgrapiql and also via my nextjs frontend.

But similar queries only work if I select "switch to the logged in user" in wpgraphiql (meaning the green dot is showing). 

Otherwise it returns a null data element.
I get the same result doing the queries via postman, so it doesn't seem to be a setup issue.

Any guidance from experienced users will be very appreciated! 

**To Reproduce**

In wpgraphiql, execute this query for posts:
```
{
  posts (first:2) {
    nodes {
      id
      title
    }
  }
}

```
Results are as expected whether the user logged in option is on or off

But if you do a very similar query on products, results are only as expected if the user logged in toggle is on (green dot showing).

```
{
  products (first:2) {
    nodes {
      id
      name
    }
  }
}

```
If the user is not logged in via the toggle, this is what is returned:

```
{
  "errors": [
    {
      "message": "The \"\" product type is not supported by the core WPGraphQL WooCommerce (WooGraphQL) schema.",
      "extensions": {
        "category": "user"
      },
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "products",
        "nodes",
        0
      ]
    }
  ],
  "data": {
    "products": null
  },
  "extensions": {
    "debug": [
      {
        "type": "DUPLICATE_TYPE",
        "message": "You cannot register duplicate Types to the Schema. The Type 'DefaultNoSidebarsTemplate' already exists in the Schema. Make sure to give new Types a unique name.",
        "type_name": "DefaultNoSidebarsTemplate",
        "stack": [
          "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:666",
          "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/access-functions.php:184",
          "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:308",
          "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:332",
          "/home/abcdef/public_html/wordpress/wp-includes/plugin.php:517",
          "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:569",
          "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:308",
          "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:332",
          "/home/abcdef/public_html/wordpress/wp-includes/plugin.php:517",
          "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:267",
          "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry.php:38",
          "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/WPGraphQL.php:785",
          "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Request.php:158",
          "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Router.php:465",
          "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Router.php:275",
          "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:308",
          "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:332",
          "/home/abcdef/public_html/wordpress/wp-includes/plugin.php:565",
          "/home/abcdef/public_html/wordpress/wp-includes/class-wp.php:399",
          "/home/abcdef/public_html/wordpress/wp-includes/class-wp.php:780",
          "/home/abcdef/public_html/wordpress/wp-includes/functions.php:1332",
          "/home/abcdef/public_html/wordpress/wp-blog-header.php:16",
          "/home/abcdef/public_html/wordpress/index.php:17"
        ]
      }
    ],
    "queryAnalyzer": {
      "keys": "**someRandomSeemingKeyValue* graphql:Query list:variableproduct list:externalproduct list:groupproduct list:simpleproduct",
      "keysLength": 157,
      "keysCount": 6,
      "skippedKeys": "",
      "skippedKeysSize": 0,
      "skippedKeysCount": 0,
      "skippedTypes": []
    }
  }
}

```
It is unclear to me why this doesn't just work. Not sure if is a bug, or a setting I don't understand, or something else I am misunderstanding.

Similarly, if I make the same query via Postman, I get a similarly unsatisfactory response:

```
{
    "errors": [
        {
            "message": "The \"\" product type is not supported by the core WPGraphQL WooCommerce (WooGraphQL) schema.",
            "extensions": {
                "category": "user"
            },
            "locations": [
                {
                    "line": 3,
                    "column": 5
                }
            ],
            "path": [
                "products",
                "nodes",
                0
            ]
        }
    ],
    "data": {
        "products": null
    },
    "extensions": {
        "debug": [
            {
                "type": "DUPLICATE_TYPE",
                "message": "You cannot register duplicate Types to the Schema. The Type 'DefaultNoSidebarsTemplate' already exists in the Schema. Make sure to give new Types a unique name.",
                "type_name": "DefaultNoSidebarsTemplate",
                "stack": [
                    "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:666",
                    "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/access-functions.php:184",
                    "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:308",
                    "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:332",
                    "/home/abcdef/public_html/wordpress/wp-includes/plugin.php:517",
                    "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:569",
                    "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:308",
                    "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:332",
                    "/home/abcdef/public_html/wordpress/wp-includes/plugin.php:517",
                    "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Registry/TypeRegistry.php:267",
                    "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Registry/SchemaRegistry.php:38",
                    "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/WPGraphQL.php:785",
                    "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Request.php:158",
                    "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Router.php:465",
                    "/home/abcdef/public_html/wordpress/wp-content/plugins/wp-graphql/src/Router.php:275",
                    "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:308",
                    "/home/abcdef/public_html/wordpress/wp-includes/class-wp-hook.php:332",
                    "/home/abcdef/public_html/wordpress/wp-includes/plugin.php:565",
                    "/home/abcdef/public_html/wordpress/wp-includes/class-wp.php:399",
                    "/home/abcdef/public_html/wordpress/wp-includes/class-wp.php:780",
                    "/home/abcdef/public_html/wordpress/wp-includes/functions.php:1332",
                    "/home/abcdef/public_html/wordpress/wp-blog-header.php:16",
                    "/home/abcdef/public_html/index.php:17"
                ]
            }
        ],
        "queryAnalyzer": {
            "keys": "**someRandomSeemingKeyValue* graphql:Query list:variableproduct list:externalproduct list:groupproduct list:simpleproduct",
            "keysLength": 157,
            "keysCount": 6,
            "skippedKeys": "",
            "skippedKeysSize": 0,
            "skippedKeysCount": 0,
            "skippedTypes": []
        }
    }
}

```

**Expected behavior**

Getting posts and products with similar queries should work, whether the user is logged in or not.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser chrome
 - Version Version 111.0.5563.64 (Official Build) (64-bit)

**Plugin Versions**

WPGraphQL 1.14.0
WPGraphQL WooCommerce (WooGraphQL) 0.12.0 
Wordpress 6.1.1
Woocommerce 7.5.1

**Comment by kidunot89** [comment]
@barrynerd Looks like you have not core product types in you listing. Type this
```graphql
{
  products (first:2 where: { typeIn: [SIMPLE, VARIABLE, GROUPED, EXTERNAL]}) {
    nodes {
      id
      name
    }
  }
}
```

**Comment by barrynerd** [comment]
Won't get to my laptop until tomorrow, but yeah, that's almost certainly true. That's pretty insightful, what in the error messages I shared tipped you off?

Assuming it's true, what can I do? Change parameters on the post types? Dig through the code and fix it for these cases then submit a pull request?

Maybe it's an issue that I need new code to implement graphql for the extra post types? Or can I configure dot.env to skip those post types, since I probably won't need it for the current application?

Something else maybe?

Really grateful for any more guidance that you might have.

**Comment by barrynerd** [comment]
@kidunot89  You are the hero of the internet today!!!!! I Giant high five!!!!! 

Explanation of fix below. 

Any idea why this matters? It seems super unrelated to the task at hand to me. It seems like a big mystery to me. Maybe it's a bug? In any case fixing this really obscure error that comes from parsing a php comment line that I would have assumed only ever mattered to wp admin functions has me working again. Amazing, I expected this to be ongoing for a long time.

Just in case anyone ever ends up here on a search, here's the deal:

I had 2 page-xxx.php template files in my child theme root that had the same "/* Template Name:" line. I made sure they had different names there in the code, and the actual query in the  bug report magically started working as expected.

**Comment by kidunot89** [comment]
@barrynerd I wrote the error message, so it's was immediately obvious what the issue was, to answer you question depending the product types. I maybe able to help you soon, WooGraphQL Pro is being launched soon _(within the next month)_ with support WooCommerce Subscription, Composite Products, Bundle Products, and Product Addons. So you if your using one of those types I recommend getting a license at launch, other than that you can use the filter in my example to continue filtering them out.

However I not gonna lie I don't like that you don't have any other option, and I feel like subbing the missing type with an existing should be possible. Like reading if you don't have WooGraphQL Pro, you can substitute the Subscription type with the Simple type. If you want reformat this issue as feature request for that, or open a new issue with that as the feature request I would not be opposed it.

**Comment by kidunot89** [comment]
@barrynerd I wrote the error message so I knew the issue immediately. You can also use the `supportedTypesOnly` argument.
```graphql
{
  products (first:2 where: { supportedTypesOnly: true }) {
    nodes {
      id
      name
    }
  }
}
```

**Comment by kidunot89** [comment]
@barrynerd As of `v0.12.4` enabling the `unsupported` type option in **WooGraphQL settings tab** on the **WPGraphQL settings page** should prevent this error from being thrown when `restricted/private` products are queried.
