### ISSUE TITLE
How to redirect to proper cart?

### ISSUE THREAD

**Issue by inqrt** [wp-graphql/wp-graphql-woocommerce#721]
I've managed to properly add a product to a cart (logging in with JWT, getting and setting woocommerce-session etc.) but I cannot figure out how to redirect to the correct cart properly (as a guest) - is there a `?session=` parameter or anything like this that I can add to `/cart`?

Thanks for your help!

**Comment by inqrt** [comment]
**Update**

I've tried as follows:

1. Execute `fetch()` with mutation for adding stuff to cart - works ✅
2. Set a ref() with the woocommerce-session header's value - works ✅
3. in last `then()` I executed another `fetch()` that executes a `login` mutation with the woocommerce-session - works ✅ (I guess)
4. Redirect to `/cart` via `window.location.href` - cart empty 🤯

**Comment by kidunot89** [comment]
@inqrt You have to process the `?session_id` param using filters. See @jacobarriola's example [here](https://jacobarriola.com/post/hosted-woocommerce-checkout-headless-application#load-the-session-in-woocommerce). This logic is same no matter what page your trying to offload the session too.

**Comment by inqrt** [comment]
Thanks for your reply @kidunot89 , I'm gonna try that 👍

**Comment by inqrt** [comment]
Works like a charm - thank you again @kidunot89 (also for your outstanding work with wp-graphql-woocommerce 👏)
