### ISSUE TITLE
"You do not have the appropriate capabilities to perform this action" on mutation updateCustomer

### ISSUE THREAD

**Issue by Thomashh2k** [wp-graphql/wp-graphql-woocommerce#744]
**Describe the bug**
"You do not have the appropriate capabilities to perform this action" on mutation updateCustomer

**To Reproduce**
1. This happened on user with roles customer and admin. The authentication header is also included in the API-Call ("woocommerce-session": "Session {token}")
2. The Query looks like this: 
 `mutation UpdateUserInfo($input: UpdateCustomerInput = {id: "", firstName: "", lastName: "", shipping: {}, billing: {}}) {
  updateCustomer(input: $input) {
    clientMutationId
    authToken
    refreshToken
  }
}`

**Expected behavior**
What i expected was that i could edit customers by themselves with this mutation i don't know if its supposed to be like this.
But if it is a normal behavior how can i make a page in my app where customers can edit themselves

**Plugin Versions**
- **WooGraphQL Version: 0.12.5**
- **WPGraphQL Version: 1.14.2**
- **WordPress Version: 6.1.1**
- **WooCommerce Version: 6.9.2**

**Additional context**
Sorry for grammar issues/misspellings English is not my first language.
Anyway if the info is not enough please let me know i will try my best to respond as fast as i can.

**Comment by kidunot89** [comment]
@Thomashh2k Don't use the `id` field. That's for `admin` only.
