### ISSUE TITLE
How can i process checkout with Stripe Payment Element and how do I verify a order has actually been paid?

### ISSUE THREAD

**Issue by talon2295** [wp-graphql/wp-graphql-woocommerce#754]
I'm developing the frontend with React and the payment is processed by [Stripe Payment Element](https://stripe.com/docs/payments/payment-element).
My backend is Wordpress, WooCommerce, WPGraphQL, WooGraphQL and WooCommerce Stripe Gateway.

### First Question, Process checkout with Stripe
The payment flow work correctly, i generate a payment intent on server and on frontend the client pay with `stripe.confirmPayment`.
Once the form complete the payment stripe redirect to page `/order_confirmed`, there i get the payment intent from url and i perform the checkout mutation.
```
mutation Checkout {
    checkout(input: {paymentMethod: "stripe", metaData: [{key: "_stripe_intent_id", value: "pi_XXXXX" }]}}) { 
        result
        order {
            status
        }
    }
}
```
The order status is always **FAIL**.
What i'm doing wrong?

### Second Question, Verify order paid
If a checkout is performed with **isPaid: true**, no payment validation is done on the backend.
Is there an action I can connect to in order to do a manual validation?

Thanks in advance.

**Comment by talon2295** [comment]
To solve the first issue i add the flag `isPaid` on mutation set to `true`
```graphql
mutation Checkout {
    checkout(input: {${_shipping}, ${_billing}, paymentMethod: "${paymentMethod}", isPaid: true, transactionId: "${paymentId}", metaData: [{key: "_stripe_intent_id", value: "${paymentId}"}]}) {
        result
    }
}
```
Now the problem was to check if the payment is succesfully done, i solved it by adding an action on `woocommerce_order_status_changed` to verify it on stripe.

```php
use Stripe\Stripe;
use Stripe\PaymentIntent;
use Stripe\Customer;

function verify_order_payment_on_status_change( $order_id, $old_status, $new_status ) {
    // Get the order object
    $order = wc_get_order( $order_id );

	if(/*$old_status === "pending" && */$new_status === "processing") {
		if($order) {
			$options         = get_option( 'woocommerce_stripe_settings' );
			$secret_key      = $options['secret_key'] ?? '';
			$test_secret_key = $options['test_secret_key'] ?? '';
	
			$stripeKey = 'yes' === $options['testmode'] ? $test_secret_key : $secret_key ;
			
			Stripe::setApiKey($stripeKey);
	
			try {
				$paymentIntentId = $order->get_meta('_stripe_intent_id');
				if(!$paymentIntentId) {
					$order->update_status('failed');
					$order->add_order_note( "Payment intent non presente" );
				}
				else {
					$paymentIntent = PaymentIntent::retrieve($paymentIntentId);
					if($paymentIntent->status !== "succeeded") {
						$order->update_status('failed');
						$order->add_order_note( "Pagamento FALLITO: ".$paymentIntentId );
					}
					else {
						$order->add_order_note( "Pagamento AUTORIZZATO: ".$paymentIntentId );
						$chargeId = $paymentIntent->latest_charge; // Retrieve the charge ID
						$order->add_order_note( "ChargeID: ".$chargeId );
						$order->set_transaction_id($chargeId) ;
					}
				}	
			} catch (Exception $e) {
				$order->update_status('failed');
				$note_content = 'ERROR '.$e->getMessage();
    			        $order->add_order_note( $note_content );
			}
		}
	}

    // Save the order
    $order->save();
}
add_action( 'woocommerce_order_status_changed', 'verify_order_payment_on_status_change', 10, 3 );
```
Maybe is better to check if the payment amount is equal to the order one, but i keep it that way for now

**Comment by zaironjacobs** [comment]
I added a hook listener in `functions.php` where `Stripe` can send updates.
After that I do something similar to your `verify_order_payment_on_status_change` function, difference is I fetch the order by `payment_intent_id`.

**Comment by alexookah** [comment]
@zaironjacobs 

can you share you function for this? Would be very helpful!

**Comment by alexookah** [comment]
@zaironjacobs  @talon2295 

Also Question: 
is it necessary to define the checkout `isPaid: true`? doesn't stripe webhook do that?

**Comment by talon2295** [comment]
@alexookah sorry but it's been a while since this project.
I remember I had to define `isPaid: true`, otherwise, the order state would not change to `pending`, and the WooCommerce action would not be triggered.

But i'm not really sure of that.
