### ISSUE TITLE
UpdateCustomer not working

### ISSUE THREAD

**Issue by niezle-ziolko** [wp-graphql/wp-graphql-woocommerce#784]
Hello,

I have a problem because I want to create a customer panel in which he can change his email address and change his account password. Unfortunately, but I can't find anywhere the appropriate mutation of GraphQL.

I tried to perform it as it was described in this [documentation](https://woographql.com/docs/using-customer-data-and-mutations)  however it does not work.

Do you perhaps have an example with the help of which I could put such a panel on my site?

Best regards

**Comment by kidunot89** [comment]
@niezle-ziolko I've identified an bug providing the update of WP core user fields through the use of `updateCustomer`.

Until this bug is resolved I recommend using `updateUser` to update WP core user fields.
