### ISSUE TITLE
Restore Customers Cart on Login?

### ISSUE THREAD

**Issue by MonPetitUd** [wp-graphql/wp-graphql-woocommerce#786]
Is it possible to restore a customer's cart session after they either logout and log back in (or when they login on a different device) as per WooCommerce's typical operation?

It appears the login mutation implementation can only provide a brand new session or persist the existing logged out session?

**Comment by kidunot89** [comment]
To continue a previously existing session from the DB. Do the `cart` query after running the `login` mutation without a session token.

Do not retrieve the `sessionToken` from the `login` mutation, that will always start a new session. Instead you should run the `cart` query and it should return the cart items from the last session saved in the DB, to continue that session retrieve the session token from the `woocommerce-session` HTTP response header.

**Comment by MonPetitUd** [comment]
Thanks @kidunot89 that process worked.

**Comment by kidunot89** [comment]
@MonPetitUd Good to hear. I'll try to better document the details mentioned here in the future.
