### ISSUE TITLE
Provide guest user authentication

### ISSUE THREAD

**Issue by kidunot89** [wp-graphql/wp-graphql-woocommerce#79]
**Describe the bug**
Cart items for guest users have no way of being persisted. This is due to the fact that there is current no way to identifying individual guest users client-side.

**To Reproduce**
1. Add an item to the cart using a cart mutation
2. Refresh the browser page
3. Query the cart

**Expected behavior**
Cart items should be persisted between request.

**Comment by jake-101** [comment]
How do you login as a guest or create a session. It requires JWT?

**Comment by kidunot89** [comment]
See [#88](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/88)
