### ISSUE TITLE
Internal Server Error when querying product variation attributes

### ISSUE THREAD

**Issue by jacobaul** [wp-graphql/wp-graphql-woocommerce#792]
**Describe the bug**
When querying the attributes of a product variation, an internal server error is thrown.
`Call to a member function get_name() on string`

**To Reproduce**
Run a minimal query which includes variation attributes e.g.
```
query GetAttrs{
  productVariation(id: "123456", idType: DATABASE_ID) {
    attributes {
      nodes {
        id
      }
    }
  }
}
```

**Plugin Versions**
- **WooGraphQL Version:**  0.16.0
- **WPGraphQL Version:** 1.16.0
- **WordPress Version:**  6.3.1
- **WooCommerce Version:** Both 7.3 & 8.0.1

**Additional context**
[error_trace.txt](https://github.com/wp-graphql/wp-graphql-woocommerce/files/12491711/error_trace.txt)

**Comment by anikrauth** [comment]
Same Problem, I just created new issue with details #793

**Comment by kidunot89** [comment]
Upgrade to `v0.17.0` or higher, this issue has been resolved.
