### ISSUE TITLE
 Internal Server Error when querying product variation attributes WooGraphQL Version: 0.16.0

### ISSUE THREAD

**Issue by anikrauth** [wp-graphql/wp-graphql-woocommerce#793]
**Describe the bug**
When I try to query the attributes of a product variation it throws the " Internal Server Error".

The same query works for WooGraphQL Version:  0.15.0
Here is the query I run, 

`query NewQuery {
  products {
    nodes {
      id
      databaseId
      sku
      slug
      name
      onSale
      image {
        sourceUrl
      }
      galleryImages {
        nodes {
          id
          sourceUrl
        }
      }
      attributes {
        nodes {
          id
          label
          options
          variation
        }
      }
      productCategories {
        nodes {
          id
          name
          slug
        }
      }
      ... on SimpleProduct {
        id
        name
        price
        stockStatus
        salePrice
        regularPrice
      }
      ... on VariableProduct {
        id
        name
        featuredImage {
          node {
            sourceUrl
          }
        }
        regularPrice
        salePrice
        price
        stockStatus
        stockQuantity
        variations {
          nodes {
            id
            databaseId
            name
            image {
              sourceUrl
            }
            price
            salePrice
            regularPrice
            slug
            stockQuantity
            attributes {
              nodes {
                attributeId
                name
                value
              }
            }
          }
        }
      }
    }
  }
}`

![WhatsApp Image 2023-09-02 at 20 31 36](https://github.com/wp-graphql/wp-graphql-woocommerce/assets/62432660/c2302519-830e-4435-9ca5-9fc1baa78388)

**Plugin Versions**
- **WooGraphQL Version:** …  0.16.0
- **WPGraphQL Version:** … 1.16.0
- **WordPress Version:** 6.3.1
- **WooCommerce Version:** 8.0.3

**Additional context**

**Comment by kidunot89** [comment]
@anikrauth Please upgrade to v0.17.0. WooGraphQL v0.16.0 had some breaking changes that were reverted in v0.17.0
