### ISSUE TITLE
Woo session transaction executed out of order

### ISSUE THREAD

**Issue by davidfaber** [wp-graphql/wp-graphql-woocommerce#817]
**Describe the bug**
Whenever I login using JWT Auth and try to do a migration, I get an error thrown by wp-graphql-woocommerce/includes/utils/class-session-transaction-manager.php on line 220.

I tried to figure out what is happening and why there's nothing in the transaction queue and I found out, that the `customer_id` in the  `QL_Session_Handler` changes right after the second call of `Session_Transaction_Manager::update_transaction_queue` because after that call `QL_Session_Handler::save_if_dirty` is called. This is when some random customer_id is replaced with the actual logged in customer-id. Therefore `Session_Transaction_Manager::

In my opinion the hook `graphql_after_resolve_field` simply triggers to late, meaning after the creation of the transaction queue.

**To Reproduce**
1. Login using the JWT Authentication `login`
2. Try to add something to the cart
3. BOOM! 500

**Expected behavior**
The correct customer-id should be loaded BEFORE the transaction-queue is created

**Screenshots**
This are my var_dumps:
<img width="773" alt="Screenshot 2023-11-10 at 17 03 23" src="https://github.com/wp-graphql/wp-graphql-woocommerce/assets/282859/22f8fd67-0cbe-4134-a0e9-c0f7252e79d9">

**Plugin Versions**
- **WooGraphQL Version:** v0.18.0 - v0.18.3
- **WPGraphQL Version:** v1.17.0
- **WPGraphQL JWT Authentication Version:** v0.7.0
- **WordPress Version:** v6.3.1
- **WooCommerce Version:** v8.1.1

**Additional context**
This is NOT a duplicate of #682 and #684

Thanks in advance!

**Comment by davidfaber** [comment]
Okay. Further investigation shows, the issue lies in the woocommerce-session-token. It seems my session token does not contain the correct user-id.
The Session-Token I use is the one returned by the login-mutation in customer.

Very strange.

**Comment by davidfaber** [comment]
With the last commit in mind I found a solutions that works:
```
        add_filter('graphql_woocommerce_cart_session_before_token_sign', function ($token) {
            if (is_user_logged_in()) {
                $token['data']['customer_id'] = get_current_user_id();
            }

            return $token;
        });
```

This way I generate a jwt-token containing the correct customer-id to start with.

So... the bug lies in `JWT_Auth_Schema_Filters` in the fieldResolve for sessionToken starting from line 197. When using the login-mutation, the customer-id is not set  after the login went through and before setting the session-token is generated.

**Comment by justlevine** [comment]
Note: this also affects Headless Login for WPGraphQL, assumedly for the same reasons though I've yet to try @davidfaber 's [workaround](https://github.com/wp-graphql/wp-graphql-woocommerce/issues/817#issuecomment-1810295336)
