### ISSUE TITLE
Order products by stock status

### ISSUE THREAD

**Issue by Nessario** [wp-graphql/wp-graphql-woocommerce#824]
**Is your feature request related to a problem?**
It's been often a request from clients to order the products by stock status so the in stock products will always be listed first. 

**Describe the solution you'd like**
A more ideal way to handle this would be if products `orderby` would include stock status as a part of the default options.

**Describe alternatives you've considered**
Been trying two approaches:
* Making use of `post_clauses` hook but that didn't lead to a clean/maintainable solution. 
* Trying to make use of `graphql_woocommerce_products_add_sort_fields` hook to update the default options, but with latest updates it seems that it isn't possible anymore.

**Comment by kidunot89** [comment]
@Nessario The function that calls that hooks is no longer in used and new one with have to be added [here](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/data/connection/class-product-connection-resolver.php#L255-L264).

With that hook, you would just have to register a new enumeration value to [this type](https://github.com/wp-graphql/wp-graphql-woocommerce/blob/develop/includes/type/enum/class-products-orderby-enum.php) using the hook in the linked code,  and you should be all good
