### ISSUE TITLE
Get Stripe's client_secret into FE

### ISSUE THREAD

**Issue by RomualdasT** [wp-graphql/wp-graphql-woocommerce#825]
At the moment it is impossible to use Stripe Payments with headless Woocommerce, because we don't have a way to get client_secret to use in stripe.ConfirmPaymet() method.

Have you guys never considered to create some endpoint to get such data?

Or am I missing something and it is possible to do other way?

**Comment by kidunot89** [comment]
@RomualdasT At the moment of writing this, the WooCommerce Stripe Gateway, only accepts Stripe credentials like sources and token directly from the `$_POST` and doesn't support alternative methods or filters. Further any alternative approach should be addressed and maintained in within [that plugin](https://github.com/woocommerce/woocommerce-gateway-stripe) as it falls outside of the scope of WPGraphQL WooCommerce.
