### ISSUE TITLE
productCategories returns incorrect products of categories

### ISSUE THREAD

**Issue by bkstorm** [wp-graphql/wp-graphql-woocommerce#890]
**Describe the bug**
The list of products of a category is not correct.

**To Reproduce**
1. Create 2 categories: Category 1 and Category 2
2. Create 2 products: Product 1 and Product 2
3. Add Product 1 to the Category 1, Product 2 to the Category 2.
4. Execute productCategories api.

**Expected behavior**
Product 1 should belong to the Category 1, Product 2 should belong to the Category 2.

**Actual behavior**
Product 1 belongs to both Category 1 and Category 2.
Product 2 belongs to both Category 1 and Category 2.

**Screenshots**
<img width="1741" alt="Screenshot 2024-09-16 at 13 33 29" src="https://github.com/user-attachments/assets/58d7a050-61ab-4088-b31b-94396687e09f">
<img width="1740" alt="Screenshot 2024-09-16 at 13 33 50" src="https://github.com/user-attachments/assets/904671c9-401e-472e-ba1d-2b35e4f8407c">
<img width="1721" alt="Screenshot 2024-09-16 at 13 34 05" src="https://github.com/user-attachments/assets/37b55fc1-dc00-4ac5-b23d-67f92ea7cc26">
<img width="1663" alt="Screenshot 2024-09-16 at 13 34 48" src="https://github.com/user-attachments/assets/7779592f-213f-489e-8ab3-c26eceeb8ebc">

**Desktop (please complete the following information):**
 - OS: Sonoma 14.6.1
 - Browser: Edge Version 128.0.2739.79 (Official build) (x86_64)

**Plugin Versions**
- **WooGraphQL Version:** 0.19.0
- **WPGraphQL Version:** 1.28.1
- **WordPress Version:** 6.6.2
- **WooCommerce Version:** 9.3.1

**Comment by kidunot89** [comment]
@bkstorm Have you tried this with the latest version `v0.21.x`

**Comment by bkstorm** [comment]
> @bkstorm Have you tried this with the latest version `v0.21.x`?

I tried with v0.21, it did not work.

**Comment by UPSxACE** [comment]
Same problem. In v0.21.0 it does return some products right(apparently), but it doesn't return all of them, nor the pageInfo correctly

**Comment by dominio50** [comment]
For some reason the products that you query from inside the productCategories typem, requires you to still provide the categoryId(databaseId) in the where clause in the product query.

`products(first: 12, after: $after, where: { categoryId: $databaseId, stockStatus: IN_STOCK, status: "PUBLISH" }) {      }`

**Comment by dominio50** [comment]
> For some reason the products that you query from inside the productCategories type, requires you to still provide the categoryId(databaseId) in the where clause in the product query.
> 
> `products(first: 12, after: $after, where: { categoryId: $databaseId, stockStatus: IN_STOCK, status: "PUBLISH" }) { }`

This seems to have been fixed in the newer versions of the plugin

**Comment by bkstorm** [comment]
I tried again with v0.21.0 today, and it works as expected. It seems like there is something wrong with my code, not wp-graphql, so I will close this issue. Thanks!
