### ISSUE TITLE
I cant see the category thumbnail 

### ISSUE THREAD

**Issue by NuruddinBadawi** [wp-graphql/wp-graphql-woocommerce#93]
**Describe the bug**

The category thumbnail is not exist in the data schema

**Comment by kidunot89** [comment]
Sorry, I didn't even know that product categories had an associated image. I'll look into it and roll it into the next release if I can.

**Comment by zamson** [comment]
Sorry to open up this old issue but it seems like the thumbnail wasn't added. Still missing from productCategory as far as I can tell.
