### ISSUE TITLE
Support update of multiple quantities in cart in a single mutation

### ISSUE THREAD

**Issue by mlipscombe** [wp-graphql/wp-graphql-woocommerce#94]
**Is your feature request related to a problem? Please describe.**
Currently, only a single `CartItem` can be updated at a time when calling `updateItemQuantity`.  Given that it's a common operation to have a list of quantities and an "update cart" button on a shopping cart page, this is awkward.

**Describe the solution you'd like**
`updateItemQuantity`, or a new mutation like `updateItemQuantities`, should accept an array of `CartItem` keys and quantities, to allow for updating the cart quantities in a single mutation.

**Describe alternatives you've considered**
Multiple top level mutations, but this is really awkward in Apollo -- for example, using the `<Mutation>` component is a non-starter, and additional code is needed to generate multiple named mutations and then parse the results.

**Comment by kidunot89** [comment]
I have considered this, but haven't gone far beyond that. I do think is it's necessary however and will add an `updateItemQuantities` mutation in the next release.
